### PR TITLE
feat(quota,swift): swift driver for image storage

### PR DESCRIPTION
**Pull request by holyhope**
This Pull Request adds image storage support for Swift back-end.

### CODE REVIEW

**Comment by holyhope** [comment]
Hello,
I am not sure how to get configuration for image storage driver.
Currently I get it from environment variables.

Tell me if there is any other proper way to get config :)

**Comment by holyhope** [comment]
It seems that there is an issue with Travis. How to handle this please?

```
465 1.11s$ travis_setup_go
466 error: GIMME_GO_VERSION not recognized as valid
467   got: -r
468 error: no GIMME_GO_VERSION supplied
469   ex: GIMME_GO_VERSION=1.4.1 /usr/local/bin/gimme 
470   ex: /usr/local/bin/gimme 1.4.1 
471 Failed to run gimme
472 The command "travis_setup_go" failed and exited with 86 during .
```

**Comment by reasonerjt** [comment]
@holyhope is it PR trying to show the storage usage when the backend is swift?

**Comment by mhurtrel** [comment]
@reasonerjt Yes indeed (@pierre-peronnet-ovh  is off for a few day); That was the goal here : show quota when swift is used as backend)

**Comment by xaleeks** [comment]
This is a big change and need some time for review.  In any case, we don't want to customize UI based on specific storage backends, this could be troublesome for maintenance.  Do you have any UI mockups to go along with this for further evaluation? @holyhope @mhurtrel

**Comment by xaleeks** [comment]
@holyhope Hi do you have an update on this? please lmk

**Comment by holyhope** [comment]
Hello,

I am back again.

> In any case, we don't want to customize UI based on specific storage backends, this could be troublesome for maintenance

I understand that point, and to be honest you are probably right.
Since we are now using S3 back-end instead of Swift, we do not need this feature anymore.

If anyone is interested, please update this pull request, otherwise we can close it.

**Pull request closed without merging**
