### PR TITLE
Update the Registry Landscape

### PR DESCRIPTION
**Pull request by kacole2**
Updated registry landscape with more features and added GitLab as a column.

Signed-off-by: Kendrick Coleman <kendrickc@vmware.com>

### CODE REVIEW

**Comment by kacole2** [comment]
@michmike as requested

**Comment by michmike** [comment]
@kacole2  this is awesome. thanks for updating. maybe include one line at the top indicating the last time this landscape was surveyed and what version of Harbor was considered. :)

thanks
/approve
/lgtm

**Comment by michmike** [comment]
we also need a line item for support of "other types of artifacts"

**Comment by kacole2** [comment]
Date and Harbor version asked. " Artifact Repository (rpms, git, jar, etc)" is on line 2

**Pull request merged**
