### PR TITLE
fix: add retry on the caller of v2DeleteManifest instead within v2DeleteManifest

### PR DESCRIPTION
**Pull request by zyyw**
Thank you for contributing to Harbor!

# Comprehensive Summary of your change

# Issue being fixed
Fixes #(issue)

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Comment by dkulchinsky** [comment]
@zyyw I'm going to build this on top of v2.7.1 (this is the version we are currently running) and will take it for a spin

**Review by wy65701436 — APPROVED** [review]
lgtm

**Comment by dkulchinsky** [comment]
@zyyw @wy65701436 I running local build with this change in our sandbox, AFAICT this works as expected, I'm doing additional tests in the next ~12 hours so will provide more feedback, but looking at the implementation I think this is good to go!

one more question: once this is merged, I'm assuming this fix can be cherry-picked into 2.7 & 2.8 releases? we're still not ready to upgrade to 2.8 since we have work around switching charts from chartmuseum to OCI and would be great to have this fix in 2.7

**Comment by zyyw** [comment]
@dkulchinsky , thank you for the feedback. Really appreciate it!

We think this is essentially an enhancement, not a bug fix. I'm afraid we will not back port this change to 2.7 & 2.8 releases.

**Review by MinerYang — APPROVED** [review]
lgtm

**Comment by dkulchinsky** [comment]
> @dkulchinsky , thank you for the feedback. Really appreciate it!
> 
> We think this is essentially an enhancement, not a bug fix. I'm afraid we will not back port this change to 2.7 & 2.8 releases.

Hey @wy65701436, that's unfortunate 😕 I'm curious why you consider this an enhancement only and not a bug fix?

I think I've shown in my [analysis](https://github.com/goharbor/harbor/issues/18381#issuecomment-1477840214) in the original issue that the current behavior is improperly handling 404 when it is returned inside the retry loop which I'm sure you'll agree is not correct behavior and is fixed by this change.

The fix is small and adresses a real issue, I think it would be beneficial (not just for my sake) to include it as a fix and backport it to the current stable versions (2.7 & 2.8).

**Comment by wy65701436** [comment]
@dkulchinsky Since the root cause of this problem could be either a network issue or a storage problem, in the harbor side, we simply added a retry mechanism to temporarily conceal the problem. It is important to note that this is not a bug in Harbor, but rather a failure tolerance in the garbage collector (GC).

**Comment by dkulchinsky** [comment]
> @dkulchinsky Since the root cause of this problem could be either a network issue or a storage problem, in the harbor side, we simply added a retry mechanism to temporarily conceal the problem. It is important to note that this is not a bug in Harbor, but rather a failure tolerance in the garbage collector (GC).

Thanks @wy65701436, I agree that the retry mechanism was added a while back to allow GC to be more resilient with temporal issues in the upstream backend storage or network and it has improved GC considerably.

My main point here is there was a gap in the retry implementation where a specific edge case was not correctly handled and is now addressed by this PR, I believe it would be highly beneficial to backport this small and low risk change to 2.7 & 2.8, and happy to work on the PRs if that helps.

**Pull request merged**
