### PR TITLE
Update ROADMAP.md

### PR DESCRIPTION
**Pull request by qnetter**
Thank you for contributing to Harbor!

# Comprehensive Summary of your change
Updated roadmap to reflect issues currently being tracked and prioritized for 2.6 and post-2.6.

# Issue being fixed
Fixes #(14890)

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [ ] Accepted the DCO. Commits without the DCO will delay acceptance.
- [ ] Made sure tests are passing and test coverage is added if needed.
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Comment by qnetter** [comment]
DCO can now be signed via web interface, but it needs to be enabled for the repo. See https://github.blog/changelog/2022-06-08-admins-can-require-sign-off-on-web-based-commits/

**Comment by Vad1mo** [comment]
@qnetter, I don't see the option in the setting. This means I don't have enough permission to do so.

**Review by Vad1mo — APPROVED** [review]

**Review by renmaosheng — APPROVED** [review]

**Comment by renmaosheng** [comment]
Hi Roger, you need to sign DCO before merging, thanks.

**Comment by qnetter** [comment]
Thanks. There is now a setting that can be enabled in the GitHub.com web interface by maintainers that will allow contributors via the website, like me, to add a Signed-off-by: header. I wish someone would do so for our projects, so I don't have to move to the CLI for this one little reason.

**Review by Vad1mo — APPROVED** [review]

**Pull request merged**
