### PR TITLE
http2 enabled and ciphers changed to get an A+ rating instead of B fr…

### PR DESCRIPTION
**Pull request by mcsage**
http2 enabled and ciphers changed to get an A+ rating instead of B from ssllabs

Thank you for contributing to Harbor!

# Comprehensive Summary of your change

# Issue being fixed
Fixes #(issue)

Please indicate you've done the following:
- [ ] Well Written Title and Summary of the PR
- [ ] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [ ] Accepted the DCO. Commits without the DCO will delay acceptance.
- [ ] Made sure tests are passing and test coverage is added if needed.
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Comment by zyyw** [comment]
We may have concerns during ssl handshake phase if the cipher changed. 

Could you please make this config as optional in addition to the default behavior as it is?

**Comment by OrlinVasilev** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=demo.goharbor.io

**Comment by OrlinVasilev** [comment]
@zyyw @wy65701436 @mcsage is that still valid ?

**Comment by mcsage** [comment]
I think it's still valid. I made it optional.

**Comment by wy65701436** [comment]
@YangJiao0817 please help to test it, cc @stonezdj

**Comment by wy65701436** [comment]
@zyyw @MinerYang Should this be considered a Helm impact? If so, I would prefer to include it in version 2.9.

**Comment by stonezdj** [comment]
Link to issue https://github.com/goharbor/harbor/issues/16367

**Review by wy65701436 — APPROVED** [review]
lgtm

**Comment by MinerYang** [comment]
We probably need consider the changes in the [nginx /nginx.https.conf.jinja](https://github.com/goharbor/harbor/blob/ca9e2d2f07e112c1b4b8db88249450b1d52be5bf/make/photon/prepare/templates/nginx/nginx.https.conf.jinja#LL62C5-L62C16) not just [portal/nginx.conf.jinja](https://github.com/goharbor/harbor/blob/main/make/photon/prepare/templates/portal/nginx.conf.jinja)

**Comment by MinerYang** [comment]
Will submit another follow-up PR to add in [nginx /nginx.https.conf.jinja](https://github.com/goharbor/harbor/blob/ca9e2d2f07e112c1b4b8db88249450b1d52be5bf/make/photon/prepare/templates/nginx/nginx.https.conf.jinja#LL62C5-L62C16) as well as take care of the prepare migration part

**Comment by OrlinVasilev** [comment]
@mcsage great to see that merged :) congrats :) and welcome to the club!

**Pull request merged**
