### PR TITLE
distribution add patch 3632

### PR DESCRIPTION
**Pull request by kmlebedev**
https://github.com/distribution/distribution/pull/3632

Thank you for contributing to Harbor!

# Comprehensive Summary of your change

# Issue being fixed
Fixes #(issue)

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Comment by kmlebedev** [comment]
@Vad1mo  Hi, I have a similar story here https://github.com/goharbor/harbor/pull/16322, the distribution has not been released for a long time, and the pathstyle for s3 has been deprecated for a long time

**Review by Vad1mo — APPROVED** [review]

**Comment by kmlebedev** [comment]
```
wget https://github.com/distribution/distribution/pull/3632.patch
2022-08-26 12:27:39 (11,7 MB/s) - ‘3632.patch’ saved [6415]

git apply 3632.patch
error: patch failed: docs/configuration.md:118
error: docs/configuration.md: patch does not apply
error: docs/storage-drivers/s3.md: No such file or directory
error: patch failed: registry/storage/driver/s3-aws/s3.go:473
error: registry/storage/driver/s3-aws/s3.go: patch does not apply
error: patch failed: registry/storage/driver/s3-aws/s3_test.go:41
error: registry/storage/driver/s3-aws/s3_test.go: patch does not apply

```

**Comment by stonezdj** [comment]
It is hard to maintain patch of upstream, we prefer to pick up the release which integrates the commit. thanks for your contribution, we'll close this PR.

**Comment by kmlebedev** [comment]
@stonezdj  I understand everything, but why close the PR before you upgrade the registry version from v2.8.0 to v2.8.1 in the build scripts?
https://github.com/goharbor/harbor/blob/e9a125a1ec42a5f8e5aeefdb470dac3dbb408403/Makefile#L122

**Comment by kmlebedev** [comment]
@wy65701436 Let's open a PR?

**Pull request closed without merging**
