### PR TITLE
[CHERRY-PICK]fix(replication): huawei adapter multi authorization

### PR DESCRIPTION
**Pull request by chlins**
Signed-off-by: chlins <chlins.zhang@gmail.com>

### CODE REVIEW

**Comment by vlandemaine-orange** [comment]
Hello, anyone can approves this PR ? @zhoumeina @jwangyangls 

Thanks

**Comment by vlandemaine-orange** [comment]
Any updates?

**Comment by chlins** [comment]
@bitsf @ywk253100 This is a cherry-pick, fix to release-1.10, please take time to look at it.

**Comment by reasonerjt** [comment]
@steven-zou it misses 1.10.3 please clarify if this is needed for 1.10.4

**Comment by bitsf** [comment]
The CI fails, it seems like some dependencies are using some new syntax from higher golang version, while 1.10.x is using golang 1.12.12, and gomod is not used when run UT

**Pull request merged**
