### PR TITLE
fix(replication): huawei adapter multi authorization

### PR DESCRIPTION
**Pull request by chlins**
Issue: https://github.com/goharbor/harbor/issues/9874
Signed-off-by: chlins <chlins.zhang@gmail.com>

### CODE REVIEW

**Comment by bitsf** [comment]
What's this change used for? Can you explain the code

**Comment by bitsf** [comment]
@ywk253100 have a look about this, it seems about the regression with your pr #8134

**Comment by bitsf** [comment]
you can also cherry-pick to 1.10.0 branch too, there will be a new patch release

**Comment by vlandemaine-orange** [comment]
Hi,

Still not working on the v1.10.1, same error :

`2020-02-17T13:33:08Z [ERROR] [/replication/transfer/image/transfer.go:320]: failed to check the existence of the manifest of image xxx/xxx:v1.0 on the destination registry: [401][{"errors":[{"errorCode":"SVCSTG.SWR.4010000","errorMessage":"Authenticate Error"}]}]
2020-02-17T13:33:08Z [ERROR] [/replication/transfer/image/transfer.go:143]: [401][{"errors":[{"errorCode":"SVCSTG.SWR.4010000","errorMessage":"Authenticate Error"}]}]`

Is this fix available on the v1.10.1 release?

Regards

**Comment by chlins** [comment]
@vlandemaine-orange hi, this pr just merged into master, I'm sorry to forget to put this pr to v1.10, I will cherry-pick it to v1.10, so maybe you can check it in v1.10 next patch release(if has).

**Comment by chlins** [comment]
@bitsf @ywk253100 Please review the pr cherry-pick to v1.10, thanks. https://github.com/goharbor/harbor/pull/10754

**Comment by Iverson-lena** [comment]
Still not working on the v1.10.4, same error.
We are eager to integrate this issue into version 10.0.4,thanks.

**Pull request merged**
