### PR TITLE
Refactor ping method into util pkg

### PR DESCRIPTION
**Pull request by yunkunrao**
Signed-off-by: yunkunrao <yunkunrao@gmail.com>

### CODE REVIEW

**Comment by yunkunrao** [comment]
This PR is related with #15340

**Review by ywk253100 — APPROVED** [review]

**Comment by chlins** [comment]
@yunkunrao hi, could you rebase main branch and resolve the conflicts?

**Comment by yunkunrao** [comment]
> @yunkunrao hi, could you rebase main branch and resolve the conflicts?

Sure.

**Review by chlins — APPROVED** [review]
lgtm

**Pull request merged**
