### PR TITLE
Fix cross account issue

### PR DESCRIPTION
**Pull request by vincentni**
Signed-off-by: Vincent Ni <kangqini@amazon.com>

Thank you for contributing to Harbor!

# Comprehensive Summary of your change
The original fix (https://github.com/goharbor/harbor/pull/17533) sometimes results in unmarshalling issue of the request response. The proposed changes here allow Harbor to fetch the token for the right account and thus solves the cross account authentication issue.

# Issue being fixed
Fixes [#(issue)](https://github.com/goharbor/harbor/issues/15388)

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Comment by chlins** [comment]
@vincentni Hi, could you please join the CNCF harbor slack channel: `#harbor` and `#harbor-dev`?

**Comment by vincentni** [comment]
> 

Sure, I'm in `#harbor-dev` now. Just PMed you.

**Review by chlins — APPROVED** [review]
lgtm

**Comment by vincentni** [comment]
@bitsf @stonezdj may I have another approval to get this PR merged?

**Review by Vad1mo — APPROVED** [review]

**Comment by randrusiak** [comment]
When this fix will be added to release?

**Pull request merged**
