### PR TITLE
Refine API swagger document wording

### PR DESCRIPTION
**Pull request by quickwind**
Refine API swagger document wording

Signed-off-by: Wallace Wei wallacewei@live.cn

### CODE REVIEW

**Comment by quickwind** [comment]
@ywk253100 我看文档说是不是要签一个CLA？还是这种文档改动不需要？

**Comment by ywk253100** [comment]
@quickwind DCO is needed in the commit message.

**Comment by clouderati** [comment]
Hi @quickwind – many thanks for the contribution. Can you please rebase so that we can merge?

**Comment by steven-zou** [comment]
@quickwind 

PR is also outdated, please rebase it and submit it again. We'll merge it after review. Thanks!
Don't forget to [sign-off](https://probot.github.io/apps/dco/) your commit.

**Comment by clouderati** [comment]
Hi @quickwind – can you please rebase so that we can merge? Thanks!

**Pull request closed without merging**
