### PR TITLE
fix invalid access action

### PR DESCRIPTION
**Pull request by orblazer**
Hello,
This PR fix 2 invalid access action.

- When we get repository via [GET]`/projects/{project_name}/repositories/{repository_name}` its ask `list` instead of `read`
- When we list scanner candidates of project [GET]`/projects/{project_name_or_id}/scanner/candidates` its ask `create` instead of `list`

Thanks.

### CODE REVIEW

**Comment by heww** [comment]
Only project admin can access this API `/projects/{project_name_or_id}/scanner/candidates`, so it doesn't use the (scanner, read) permission.

**Comment by MinerYang** [comment]
@orblazer,
As it mentioned above, the repository part looks correct but not the scanner part.
Would you like to revise this PR?
Thanks!

**Review by wy65701436 — APPROVED** [review]
lgtm

**Comment by wy65701436** [comment]
@orblazer please help to resolve the coflict, then let me merge it, thanks.

**Comment by wy65701436** [comment]
@orblazer please help to sync the latest code to resolve the CI failure, then let me merge it, thanks.

**Comment by wy65701436** [comment]
@orblazer sure, you can go ahead to file an PR or fix the DCO of this one, the change LGTM

**Comment by wy65701436** [comment]
@orblazer would you mind to resolve the DCO problem? then we can go ahead to merge it.

**Comment by orblazer** [comment]
Hello @wy65701436, as i have said, i have make new PR #18188 for accept DCO on original commit.

**Pull request closed without merging**
