### PR TITLE
docs/README.md: update old url

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <764524258@qq.com>

### CODE REVIEW

**Comment by daixiang0** [comment]
any input?

**Comment by daixiang0** [comment]
any update?

**Comment by daixiang0** [comment]
any update?

**Comment by daixiang0** [comment]
any update?

**Comment by daixiang0** [comment]
any update?

**Comment by daixiang0** [comment]
any update?

**Comment by daixiang0** [comment]
any update?

**Comment by daixiang0** [comment]
any update?

**Comment by daixiang0** [comment]
any update?

**Comment by daixiang0** [comment]
Hi, @ywk253100 any input?

**Comment by daixiang0** [comment]
@wy65701436 mind have a look?

**Comment by daixiang0** [comment]
@wy65701436 mind have a look?

**Comment by daixiang0** [comment]
@nlowe thanks for review, seems you are busy at developing something import.
Could this merge?

**Comment by nlowe** [comment]
The merge checks require two approvals, so we need at least one more. I'll post a message in slack to see if we can get someone else to take a look at this.

**Pull request merged**
