### PR TITLE
support external redis sentinel cluster

### PR DESCRIPTION
**Pull request by jeremyxu2010**
In my scenario, I use external [redis sentinel cluster](https://redis.io/topics/sentinel) and postgresql cluster based on [stolon](https://github.com/sorintlab/stolon) to ensure the HA of redis and posgresql.

But I found harbor do not support [redis sentinel url](https://github.com/exponea/redis-sentinel-url), eg. `redis+sentinel://localhost:26379,otherhost:26479/mymaster/0`

So I implemented this feature.

### CODE REVIEW

**Comment by reasonerjt** [comment]
@jeremyxu2010 Have you verified the `core` component using sentinel to store session, and `registry` using sentinel to store the layer's metadata?

**Comment by jeremyxu2010** [comment]
@reasonerjt oh, I will add them.

**Comment by jeremyxu2010** [comment]
> @jeremyxu2010 Have you verified the `core` component using sentinel to store session, and `registry` using sentinel to store the layer's metadata?

@reasonerjt 
I reviewed beego's code, its new version supports multiple modes to access redis, including redis sentinel. see [here](https://github.com/astaxie/beego/blob/develop/session/redis_sentinel/sess_redis_sentinel.go). So  upgrade beego to the new version?
I also reviewed docker registry's code, unlucky it does not support redis sentinel. I will post a new PR to [docker/distribution](https://github.com/docker/distribution) soon. 

`https://github.com/docker/distribution/blob/master/registry/handlers/app.go`

```golang
func (app *App) configureRedis(configuration *configuration.Configuration) {
	if configuration.Redis.Addr == "" {
		dcontext.GetLogger(app).Infof("redis not configured")
		return
	}

	pool := &redis.Pool{
		Dial: func() (redis.Conn, error) {
			// TODO(stevvooe): Yet another use case for contextual timing.
			ctx := context.WithValue(app, redisStartAtKey{}, time.Now())

			done := func(err error) {
				logger := dcontext.GetLoggerWithField(ctx, "redis.connect.duration",
					dcontext.Since(ctx, redisStartAtKey{}))
				if err != nil {
					logger.Errorf("redis: error connecting: %v", err)
				} else {
					logger.Infof("redis: connect %v", configuration.Redis.Addr)
				}
			}

			conn, err := redis.DialTimeout("tcp",
				configuration.Redis.Addr,
				configuration.Redis.DialTimeout,
				configuration.Redis.ReadTimeout,
				configuration.Redis.WriteTimeout)
			if err != nil {
				dcontext.GetLogger(app).Errorf("error connecting to redis instance %s: %v",
					configuration.Redis.Addr, err)
				done(err)
				return nil, err
			}

			// authorize the connection
			if configuration.Redis.Password != "" {
				if _, err = conn.Do("AUTH", configuration.Redis.Password); err != nil {
					defer conn.Close()
					done(err)
					return nil, err
				}
			}

			// select the database to use
			if configuration.Redis.DB != 0 {
				if _, err = conn.Do("SELECT", configuration.Redis.DB); err != nil {
					defer conn.Close()
					done(err)
					return nil, err
				}
			}

			done(nil)
			return conn, nil
		},
		MaxIdle:     configuration.Redis.Pool.MaxIdle,
		MaxActive:   configuration.Redis.Pool.MaxActive,
		IdleTimeout: configuration.Redis.Pool.IdleTimeout,
		TestOnBorrow: func(c redis.Conn, t time.Time) error {
			// TODO(stevvooe): We can probably do something more interesting
			// here with the health package.
			_, err := c.Do("PING")
			return err
		},
		Wait: false, // if a connection is not available, proceed without cache.
	}

	app.redis = pool

	// setup expvar
	registry := expvar.Get("registry")
	if registry == nil {
		registry = expvar.NewMap("registry")
	}

	registry.(*expvar.Map).Set("redis", expvar.Func(func() interface{} {
		return map[string]interface{}{
			"Config": configuration.Redis,
			"Active": app.redis.ActiveCount(),
		}
	}))
}
```

**Comment by jeremyxu2010** [comment]
I have create a new [PR](https://github.com/docker/distribution/pull/2886) to docker/distribution project. Hope upstream can accept it.

**Comment by jeremyxu2010** [comment]
@reasonerjt We have discussed, `support external redis sentinel cluster` this feature does not need to be supported. We are internally preparing to adopt the [redis smartproxy solution](https://github.com/hackerthon2019/redis-ha), which can solve the high availability problem of redis and does not require the harbor to make corresponding changes.

**Comment by reasonerjt** [comment]
@jeremyxu2010 per the latest comment, I'll close this PR, we are well aware that this is a valid requirement, but it involve some dependency from upstream softwares, so we need more time to coordinate and figure out a workable solution, thanks for your contribution and update !

**Comment by bitsf** [comment]
implement by https://github.com/goharbor/harbor/pull/11155

**Pull request closed without merging**
