### PR TITLE
Ignore the not found error when trying to delete scheduled policies

### LINKED ISSUE #14292: Harbor replication issues since upgrade to OSS version:v2.1.3
What can we help you?

We're running Harbor on Kubernetes v1.18.15. We recently upgraded Harbor from Helm chart v1.4.6 (Harbor OSS version:v2.0.6) to Helm chart v1.5.3 (Harbor OSS version:v2.1.3)

Since the upgrade, we've noticed a number of errors re replication:

- One of the replication rules can't be disabled, we get an `Internal Server Error` in the UI, which on the `jobservice` logs translates to:
```
[ERROR] [/jobservice/api/handler.go:288]: Serve http request 'POST /api/v1/jobs/d353946f090203dbc8ca5035' error: 404 {"code":10010,"message":"object is not found","details":"d353946f090203dbc8ca5035"}
```

- Another replication rule, which is currently trying to replicate artifacts to a destination Harbor instance, and uses a robot account for authentication, errors out complaining about said robot account not existing:

```
failed to do the prepare work for pushing/uploading resources: http error: code 404, message {"errors": [{"code":"NOT_FOUND","message":"user robot$XXXXX not found"
```

... but the robot account does exist, and this was working fine before.

In terms of configuration, we're currently using external components for Harbor database (RDS Postgres), chart/image persistence (S3 bucket) and caching layer (Redis Elasticache).
I've tried stuff such as Harbor restarts, Redis flushing, GC runs... to no avail.

### LINKED ISSUE #14548: Getting Internal Server Error when deleting or modifying schedule of a replication policy
This seems to be related to https://github.com/goharbor/harbor/issues/13342 which was closed as fixed in v2.1.2, also reported there but figured it's better to have a new issue since we're having this issue in v2.1.4.

**Expected behavior and actual behavior:**
I should be able to delete or modify the schedule of an existing replication policy, however in some cases when trying to delete a replication or modify its schedule we get an `Internal Server Error` message.

When trying to update such a replication policy we get the following error:
```
{"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"failed to update the policy 224: failed to unschedule the policy 224: job not found"}]}
```

When trying to delete that same policy we get a similar error:
```
{"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"failed to delete the policy 224: job not found"}]}
```

**Steps to reproduce the problem:**
We can't be sure what is causing this situation, and it doesn't seem to affect all replication policies so it's hard to reproduce in a consistent way.

**Versions:**
Please specify the versions of following systems.

- harbor version: `v2.1.4`

**Additional context:**

Checking the Postgres DB, I see the policy definition:
```
coredb=# select * from replication_policy where id=224;
 id  |     name      | dest_registry_id | enabled |                      description                      | deleted |                             trigger                              |                                 filters                                  | replicate_deletion | start_time |       creation_time        |        update_time         | creator | src_registry_id | dest_namespace | override
-----+---------------+------------------+---------+-------------------------------------------------------+---------+------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------+------------+----------------------------+----------------------------+---------+-----------------+----------------+----------
 224 | thanos-thanos |                0 | t       | Replicates thanos/thanos from quay to harbor external | f       | {"type":"scheduled","trigger_settings":{"cron":"0 30 11 * * *"}} | [{"type":"name","value":"thanos/thanos"},{"type":"tag","value":"v0.**"}] | f                  |            | 2021-03-01 22:36:29.153409 | 2021-03-30 18:14:31.763016 |         |              44 | external       | f
```

I also looked at the `replication_schedule_job` table:
```
coredb=# select * from replication_schedule_job where policy_id=224;
 id  |  status  | policy_id |          job_id          |       creation_time        |        update_time
-----+----------+-----------+--------------------------+----------------------------+----------------------------
 176 | finished |       224 | 0a20cd84dd2b73951c0e36e2 | 2021-03-01 22:36:29.155303 | 2021-03-23 11:30:00.288882
 223 | finished |       224 | 6ef4ff89ecde521cca20a0af | 2021-03-29 20:44:50.329304 | 2021-03-30 11:30:00.685209
```

`policy_id`=224 had two entries and I was only able to find the latter (`id`=223) in Redis:

`id`=223 `job_id`=6ef4ff89ecde521cca20a0af

```
127.0.0.1:6379[1]> hgetall {harbor_job_service_namespace}:job_stats:6ef4ff89ecde521cca20a0af
 1) "id"
 2) "6ef4ff89ecde521cca20a0af"
 3) "name"
 4) "IMAGE_REPLICATE"
 5) "kind"
 6) "Periodic"
 7) "unique"
 8) "0"
 9) "status"
10) "Scheduled"
11) "ref_link"
12) "/api/v1/jobs/6ef4ff89ecde521cca20a0af"
13) "enqueue_time"
14) "1617050690"
15) "run_at"
16) "0"
17) "cron_spec"
18) "0 30 11 * * *"
19) "web_hook_url"
20) "http://harbor-core:80/service/notifications/jobs/replication/223"
21) "numeric_policy_id"
22) "1617050690"
23) "parameters"
24) "{\"policy_id\":224,\"url\":\"http://harbor-core:80\"}"
25) "update_time"
26) "1617050690"
27) "revision"
28) "1617050690"
29) "ack"
30) "{\"status\":\"Scheduled\",\"revision\":1617050690,\"check_in_at\":0}"
```

However, not the first one (is this what's causing the error?):

`id`=176, `job_id`=0a20cd84dd2b73951c0e36e2
```
127.0.0.1:6379[1]> hgetall {harbor_job_service_namespace}:job_stats:0a20cd84dd2b73951c0e36e2
(empty array)
```

I looked at another job with a similar issue:
```
coredb=# select * from replication_schedule_job where policy_id=239;
 id  |  status  | policy_id |          job_id          |       creation_time        |        update_time
-----+----------+-----------+--------------------------+----------------------------+---------------------------
 191 | finished |       239 | f5822ec7ede4bf281b4d2fcb | 2021-03-01 22:45:36.409146 | 2021-03-29 19:00:04.35506
```

and this one too is missing the key in redis:
```
127.0.0.1:6379[1]> hgetall {harbor_job_service_namespace}:job_stats:f5822ec7ede4bf281b4d2fcb
(empty array)
```

Any suggestions how to fix this? or how to have the system reconcile the two databases? or I'm missing something?

### PR DESCRIPTION
**Pull request by ywk253100**
Ignore the not found error when trying to delete scheduled policies
fixes #14292
fixes #14548

Signed-off-by: Wenkai Yin <yinw@vmware.com>

### CODE REVIEW

**Comment by dkulchinsky** [comment]
@ywk253100 thanks for this fix! a question though, from what we can tell - replication policies in this condition although defined in the postgres database are not being scheduled, this fix will allow us to delete and possibly modify the schedule (to get the jobservice schedule fixed) but if this is not done by the administrator - they will remain in sort of a broken state where they are defined, showing up in the UI but in reality not actually running when they supposed to.

I guess I'm trying to understand the root cause of this condition? what happens that causes jobservice to drop this job from Redis? and perhaps some reconciliation process is needed to make sure jobservice and its datasource (Redis) are always aligned  with the policy definition in postgres db which as I understand it - is the source of truth.

**Comment by ywk253100** [comment]
@dkulchinsky Agree with you. We should take the database as the source of the truth and this is already in our plan cc @steven-zou

**Review by steven-zou — APPROVED** [review]
LGTM

**Review by wy65701436 — APPROVED** [review]
lgtm

**Comment by dkulchinsky** [comment]
> @dkulchinsky Agree with you. We should take the database as the source of the truth and this is already in our plan cc @steven-zou

Thank you, is there an issue where this is tracked? so I can follow along.

**Pull request merged**
