### PR TITLE
add membership=true back for gitlab replication adapter

### LINKED ISSUE #20401: Cannot to create pull-based replication from gitlab to Harbor
Harbor version: built from main branch

Root cause analysis: 
Due to the merge of this [PR](https://github.com/goharbor/harbor/pull/20153), users cannot perform pull-based replication from gitlab to Harbor. It failed with error message like below:
```
{"message":"500 Internal Server Error"}
```
Screenshot 2024-05-07 at 8 48 41 PM

This issue is also discussed here:
* https://gitlab.com/gitlab-org/gitlab/-/issues/353510

### PR DESCRIPTION
**Pull request by zyyw**
Thank you for contributing to Harbor!

# Comprehensive Summary of your change

# Issue being fixed
Fixes #20401 

Please indicate you've done the following:
- [ ] Well Written Title and Summary of the PR
- [ ] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [ ] Accepted the DCO. Commits without the DCO will delay acceptance.
- [ ] Made sure tests are passing and test coverage is added if needed.
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Comment by zyyw** [comment]
@lxShaDoWxl @chlins Could you please help to review it? Thanks

**Review by chlins — APPROVED** [review]
Lgtm

**Review by wy65701436 — CHANGES_REQUESTED** [review]
Remove could resolve the 500, but we need to figure out the meaning of search_namespaces.

**Comment by zyyw** [comment]
> Remove could resolve the 500, but we need to figure out the meaning of search_namespaces.

@lxShaDoWxl Could you please kindly provide some insights on this? Although we have read through this [doc](https://docs.gitlab.com/ee/api/projects.html) (search by `search_namespaces`), the `Description` of `search_namespaces` is still not very clear to us.

**Comment by wy65701436** [comment]
@lxShaDoWxl can you leave your comments?

**Review by stonezdj — APPROVED** [review]

**Review by wy65701436 — APPROVED** [review]
lgtm

**Pull request merged**
