### PR TITLE
Updated translation for 2.5

### PR DESCRIPTION
**Pull request by sluetze**
Signed-off-by: sluetze <13255307+sluetze@users.noreply.github.com>

@Vad1mo

### CODE REVIEW

**Review by Vad1mo — APPROVED** [review]
LGTM

Thank you @sluetze for the german translation 

🇩🇪 🇨🇭 🇦🇹

**Comment by sluetze** [comment]
#16321 related

**Review by OrlinVasilev — APPROVED** [review]
LGTM

**Review by Vad1mo — APPROVED** [review]

**Review by Vad1mo — APPROVED** [review]
👍

**Review by AllForNothing — APPROVED** [review]
LGTM

**Pull request merged**
