### PR TITLE
spelling * AuthProxyRedirectPath

### PR DESCRIPTION
**Pull request by azadious**

### CODE REVIEW

**Review by ninjadq — APPROVED** [review]
lgtm

**Review by heww — APPROVED** [review]

**Comment by heww** [comment]
Hi, @azadious could you update and signoff your PR?

**Review by Vad1mo — APPROVED** [review]
this is a trivial one, what are we waiting for?

**Comment by ninjadq** [comment]
@Vad1mo because DCO test failed, the author need to sign his name on commit

**Comment by Vad1mo** [comment]
Right didn't see that one

**Comment by wy65701436** [comment]
@azadious can you help to review the DCO？ Then I can merge it.

**Comment by wy65701436** [comment]
@azadious I'll close it as no activity, and feel free to reopen it once the DCO is fixed.

**Pull request closed without merging**
