### PR TITLE
Change the permissions of the *.go file from 0755 to 0644

### PR DESCRIPTION
**Pull request by Iceber**
Thank you for contributing to Harbor!

# Comprehensive Summary of your change

# Issue being fixed
Fixes #(issue)

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [ ] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Review by OrlinVasilev — APPROVED** [review]
lgtm but can you share what issue you have faced with the original premissions @Iceber ? :) Thanks!

**Review by wy65701436 — APPROVED** [review]
lgtm

**Comment by wy65701436** [comment]
@Iceber can you help to resolve this conflicts, then let me merge it, thanks.

**Comment by Iceber** [comment]
@wy65701436 rebased, sorry to make you wait so long

**Pull request merged**
