### PR TITLE
Correct "leveraging"

### PR DESCRIPTION
**Pull request by grinnellian**

### CODE REVIEW

**Comment by xaleeks** [comment]
Thanks!  please also cherry pick to release-2.0.0 if possible

**Comment by wy65701436** [comment]
@grinnellian could you please fix the DCO and help to cherry-pick it to release-2.0.0？

**Comment by xaleeks** [comment]
@grinnellian  please sign your commit

**Comment by grinnellian** [comment]
I can pull this down and sign the commit, but I'm curious if folks have given thought to the cost/benefit of all-but preventing web-client edits?
It's a lot of friction for someone just doing some proofreading as they go :-)

**Pull request merged**
