### PR TITLE
docs(readme): fix syntax errors in the document

### PR DESCRIPTION
**Pull request by Fish-pro**
Signed-off-by: Fish-pro <zechun.chen@daocloud.io>

Thank you for contributing to Harbor!

# Comprehensive Summary of your change

# Issue being fixed
Fixes #(issue)

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Review by Vad1mo — APPROVED** [review]
grat work, thank your for your contribution

**Review by OrlinVasilev — APPROVED** [review]
looks great! Thank you for your contribution @Fish-pro :) hope we can meet at KubeCon :)

**Comment by OrlinVasilev** [comment]
will close and open again the PR so we can unblock the checks!

**Review by chlins — APPROVED** [review]
lgtm

**Comment by OrlinVasilev** [comment]
will close and will reopen in few minutes, no idea what's going on with github actions...

**Comment by OrlinVasilev** [comment]
@Fish-pro can you please push again to the branch something github is giving us grief with the checks :(

**Comment by Fish-pro** [comment]
> @Fish-pro can you please push again to the branch something github is giving us grief with the checks :(

@OrlinVasilev Thanks for tips，I've already pushed it again

**Review by zyyw — APPROVED** [review]

**Comment by zyyw** [comment]
close and then reopen it to trigger the github actions

**Comment by Fish-pro** [comment]
> close and then reopen it to trigger the github actions

I'm sorry. I did it again

**Comment by OrlinVasilev** [comment]
@Fish-pro Thanks for contributing merging it now! Welcome to the team! :))

**Pull request merged**
