### PR TITLE
feat: support Alibaba ACR proxy cache type

### LINKED ISSUE #19693: Harbor don't supports proxy caching for the Alibaba ACR registry
How can we help you?

### PR DESCRIPTION
**Pull request by njucjc**
Thank you for contributing to Harbor!

# Comprehensive Summary of your change

# Issue being fixed
Fixes #19693

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

PR for docs [#519](https://github.com/goharbor/website/pull/519)

### CODE REVIEW

**Comment by stonezdj** [comment]
@njucjc  could you please share us an account to verify the PR in the Slack

**Comment by njucjc** [comment]
> @njucjc could you please share us an account to verify the PR in the Slack

@stonezdj I just email you an account 

> @njucjc could you please share us an account to verify the PR in the Slack

I haven't joined the Slack, I just email you in this address `stonezdj@gmail.com`

**Comment by njucjc** [comment]
ping @stonezdj  @wy65701436 . Any suggestion for this PR?

**Review by chlins — APPROVED** [review]
lgtm

**Comment by chlins** [comment]
Wait for https://github.com/goharbor/harbor/pull/19692.

**Comment by chlins** [comment]
@njucjc Please fix the DCO in CI.

**Comment by njucjc** [comment]
> @njucjc Please fix the DCO in CI.

done

**Review by stonezdj — APPROVED** [review]

**Pull request merged**
