### PR TITLE
Fix links in docs 1.10

### PR DESCRIPTION
**Pull request by sdiepend**

### CODE REVIEW

**Comment by bitsf** [comment]
use "git commit -s"

**Comment by stuclem** [comment]
The TOC linking issue was resolved in https://github.com/goharbor/harbor/pull/10661.

**Comment by sdiepend** [comment]
TOC linking is fixed, i have rebased my PR. But the links at the bottom are still not OK, see diff.

**Comment by bitsf** [comment]
this is already fixed by other pr.
Thanks for the effort too.

**Pull request closed without merging**
