### PR TITLE
Fix #20658 docker-compose `version` is obsolete warning

### LINKED ISSUE #20658: docker-compose: `version` is obsolete
**Expected behavior and actual behavior:**
Harbor using docker-compose generate following warning message with latest docker:
```
WARN[0000] /home/app/harbor/docker-compose.yml: `version` is obsolete
```

The top level version is now obsolete. see https://docs.docker.com/compose/compose-file/04-version-and-name/#version-top-level-element-optional

**Steps to reproduce the problem:**
executing any docker compose command: e.g. `docker compose up`

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.11.0-70255684 (but irrelevent actually)
- docker engine version: 26.1.3
- docker-compose version: 2.27.0

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

### PR DESCRIPTION
**Pull request by jhdxr**
# Comprehensive Summary of your change
This is PR removed the obsoleted global level `version` from the docker compose template.

# Issue being fixed
Fixes #20658 

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [ ] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [ ] Made sure tests are passing and test coverage is added if needed.
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Comment by jhdxr** [comment]
I don't think I have the permission to label this PR. or maybe there is robot can help me to do so? It's not mentioned in the `CONTRIBUTING.md`

**Comment by MinerYang** [comment]
Please confirm it work with legacy docker-compose version , 
Thx~

**Comment by jhdxr** [comment]
> Please confirm it work with legacy docker-compose version , Thx~

Can I check what's the minimun version we need to support?

**Comment by MinerYang** [comment]
> > Please confirm it work with legacy docker-compose version , Thx~
> 
> Can I check what's the minimun version we need to support?

We need at lease:
 - docker-compose (v1.18.0+) or docker compose v2 (docker-compose-plugin)
 - docker engine Version 20.10.10-ce+ or higher

**Comment by jhdxr** [comment]
> > > Please confirm it work with legacy docker-compose version , Thx~
> > 
> > 
> > Can I check what's the minimun version we need to support?
> 
> We need at least:
> 
>     * docker-compose (v1.18.0+) or docker compose v2 (docker-compose-plugin)
> 
>     * docker engine Version 20.10.10-ce+ or higher

I did a test for docker compose without version line on Rocky Linux 8 with docker engine v20.10.10 and docker compose v2, and everything looks good.

env:
```
NAME="Rocky Linux"
VERSION="8.9 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.9"

Server: Docker Engine - Community
 Engine:
  Version:          20.10.10
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       e2f740d
  Built:            Mon Oct 25 07:41:17 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.32
  GitCommit:        8b3b7ca2e5ce38e8f31a34f35b2b68ceb8470d89
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

Docker Compose version v2.27.0
```

BTW, docker CE 20.10 is EOL half year ago, I think we may increase the min supported to v23.0 (see https://endoflife.date/docker-engine)

**Review by MinerYang — APPROVED** [review]
lgtm

 @jhdxr, Thanks for your contribution to Harbor community!
 
 Best,
Miner

**Review by wy65701436 — APPROVED** [review]
lgtm

**Pull request merged**
