### PR TITLE
#4258-Refine Configure_https.md

### PR DESCRIPTION
**Pull request by jeffweilee**
Refine Configure_https.md so that HTTPS can work and comply with Subject Alternative Name (SAN) and x509 v3 extension requirement. The document outline is as follows:
* Getting Certificate Authority
* Getting Server Certificate
* Getting Client Certificate
* Configuration and Installation
* Troubleshooting

### CODE REVIEW

**Comment by jeffweilee** [comment]
Is the PR not accepted? any reason?

**Comment by steven-zou** [comment]
@jeffweilee 

Please pass DOC checking by appending `-s` flag after git commit or amend your commit with `-s`.

**Comment by steven-zou** [comment]
@jeffweilee 

PR is also outdated, please rebase it and submit it again. We'll merge it after review. Thanks!
Don't forget to [sign-off](https://probot.github.io/apps/dco/) your commit.

**Comment by clouderati** [comment]
Hi @jeffweilee – going to close this out due to inactivity. More than happy to re-open if you'd like to rebase and sign-off on your commit. Many thanks for the contribution!

**Pull request closed without merging**
