### PR TITLE
fix fatal error

### LINKED ISSUE #9300: 1.9.0 jobservice fatal error: concurrent map iteration and map write
Start tag retention task
```
019-09-29T06:01:23Z [INFO] [/common/config/store/driver/rest.go:24]: get configuration from url: http://harbor-core/api/internal/configurations
fatal error: concurrent map iteration and map write

goroutine 1032 [running]:
runtime.throw(0x168d1e8, 0x26)
	/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc002eeb458 sp=0xc002eeb428 pc=0x42f222
runtime.mapiternext(0xc002eeb5b0)
	/usr/local/go/src/runtime/map.go:860 +0x597 fp=0xc002eeb4e0 sp=0xc002eeb458 pc=0x410a57
runtime.mapiterinit(0x14a9240, 0xc000475260, 0xc002eeb5b0)
	/usr/local/go/src/runtime/map.go:850 +0x1c9 fp=0xc002eeb500 sp=0xc002eeb4e0 pc=0x4103c9
github.com/goharbor/harbor/src/jobservice/job/impl.createLoggers(0xc003a1dca0, 0x18, 0x1679c58, 0x19, 0xc001186c48, 0x42e43d)
	/harbor/src/jobservice/job/impl/context.go:190 +0x340 fp=0xc002eeb620 sp=0xc002eeb500 pc=0x8c3600
github.com/goharbor/harbor/src/jobservice/job/impl.(*Context).Build(0xc0000cd380, 0x1970100, 0xc00153a640, 0xc003686540, 0xc00153a640, 0xc002eeb798, 0x0)
	/harbor/src/jobservice/job/impl/context.go:126 +0x310 fp=0xc002eeb6f0 sp=0xc002eeb620 pc=0x8c2ec0
github.com/goharbor/harbor/src/jobservice/runner.(*RedisJob).Run(0xc001060f00, 0xc003686540, 0x0, 0x0)
	/harbor/src/jobservice/runner/redis.go:170 +0x3d3 fp=0xc002eeb840 sp=0xc002eeb6f0 pc=0x12b4993
github.com/goharbor/harbor/src/jobservice/worker/cworker.(*basicWorker).registerJob.func2(0xc003686540, 0x26570e0, 0xc002eeb8c0)
	/harbor/src/jobservice/worker/cworker/c_worker.go:413 +0x34 fp=0xc002eeb870 sp=0xc002eeb840 pc=0x12b9ae4
github.com/gocraft/work.runJob.func1(0x166af76, 0x10)
	/harbor/src/vendor/github.com/gocraft/work/run.go:31 +0x514 fp=0xc002eeb970 sp=0xc002eeb870 pc=0x86bc34
github.com/goharbor/harbor/src/jobservice/worker/cworker.(*workerContext).logJob(0x267a868, 0xc003686540, 0xc00153a5a0, 0x0, 0x0)
	/harbor/src/jobservice/worker/cworker/c_worker.go:75 +0x120 fp=0xc002eeb9c8 sp=0xc002eeb970 pc=0x12b6310
runtime.call64(0xc0020b82a0, 0x1717f28, 0xc001da5320, 0x1800000028)
	/usr/local/go/src/runtime/asm_amd64.s:520 +0x3b fp=0xc002eeba18 sp=0xc002eeb9c8 pc=0x45aafb
reflect.Value.call(0x1498160, 0x1717f28, 0x13, 0x165a984, 0x4, 0xc002eebd48, 0x3, 0x3, 0xc00369e190, 0x0, ...)
	/usr/local/go/src/reflect/value.go:447 +0x461 fp=0xc002eebc38 sp=0xc002eeba18 pc=0x485fd1
reflect.Value.Call(0x1498160, 0x1717f28, 0x13, 0xc002eebd48, 0x3, 0x3, 0xc00153a5a0, 0x50, 0x18eeb6c)
	/usr/local/go/src/reflect/value.go:308 +0xa4 fp=0xc002eebca0 sp=0xc002eebc38 pc=0x485a54
github.com/gocraft/work.runJob.func1(0x8, 0x1717568)
	/harbor/src/vendor/github.com/gocraft/work/run.go:23 +0x204 fp=0xc002eebda0 sp=0xc002eebca0 pc=0x86b924
github.com/gocraft/work.runJob(0xc003686540, 0x197c620, 0x14a9600, 0xc000014040, 0x1, 0x1, 0xc000e96780, 0x2f, 0xc001f59320, 0x53, ...)
	/harbor/src/vendor/github.com/gocraft/work/run.go:51 +0x18b fp=0xc002eebdf0 sp=0xc002eebda0 pc=0x864b8b
github.com/gocraft/work.(*worker).processJob(0xc0006bd140, 0xc003686540)
	/harbor/src/vendor/github.com/gocraft/work/worker.go:198 +0x208 fp=0xc002eebef8 sp=0xc002eebdf0 pc=0x866dd8
github.com/gocraft/work.(*worker).loop(0xc0006bd140)
	/harbor/src/vendor/github.com/gocraft/work/worker.go:119 +0x20d fp=0xc002eebfd8 sp=0xc002eebef8 pc=0x865f0d
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc002eebfe0 sp=0xc002eebfd8 pc=0x45c791
created by github.com/gocraft/work.(*worker).start
	/harbor/src/vendor/github.com/gocraft/work/worker.go:78 +0x3f
```

### PR DESCRIPTION
**Pull request by liuxu623**
Fixes #9300

### CODE REVIEW

**Comment by steven-zou** [comment]
@liuxu623 

Thanks for fixing the bug. Please make sure the CI/CD pipeline passed and then we can start the merging process.

**Comment by liuxu623** [comment]
> @liuxu623
> 
> Thanks for fixing the bug. Please make sure the CI/CD pipeline passed and then we can start the merging process.

CI/CD passed

**Comment by steven-zou** [comment]
@liuxu623 

Thanks for raising PR to fix the race issue of the job service. I  checked the code, is it possible to lock in a small scope? Like the place where race issue found?

src/jobservice/job/imple/context.go line 190

```
fSettings := map[string]interface{}{}
			for k, v := range lc.Settings {
				// Copy settings
				fSettings[k] = v
			}
```

**Comment by liuxu623** [comment]
> @liuxu623
> 
> Thanks for raising PR to fix the race issue of the job service. I checked the code, is it possible to lock in a small scope? Like the place where race issue found?
> 
> src/jobservice/job/imple/context.go line 190
> 
> ```
> fSettings := map[string]interface{}{}
> 			for k, v := range lc.Settings {
> 				// Copy settings
> 				fSettings[k] = v
> 			}
> ```

Not only  line 190
```
		if lc.Name == logger.NameFile || lc.Name == logger.NameStdOutput || lc.Name == logger.NameDB {
			if lc.Settings == nil {
				lc.Settings = map[string]interface{}{}
			}
			lc.Settings["depth"] = 5
		}
```

**Pull request merged**
