### PR TITLE
remove duplicate word

### PR DESCRIPTION
**Pull request by royeectu**

### CODE REVIEW

**Comment by clouderati** [comment]
lgtm; can you please sign-off on the commit so that I can merge? Thanks!

**Comment by royeectu** [comment]
A simple PR, why is it taking so long?

**Comment by royeectu** [comment]
you must be kidding me

**Comment by Hokwang** [comment]
@royeectu
simple thing.
please sign-off. You don't know very basic rule.

**Comment by royeectu** [comment]
@Hokwang , what do you mean?

**Pull request merged**
