### PR TITLE
[Cherrypick to v2.11] bump up beego to v2.2.1 (#20555)

### PR DESCRIPTION
**Pull request by hajnalmt**
Bump up beego v2.2.1

# Comprehensive Summary of your change
Cherry-picking MinerYang's commit:
[https://github.com/goharbor/harbor/pull/20555/files](https://github.com/goharbor/harbor/pull/20555/files)
There were High security vulnerabilities in the beego versions <2.2.1

[GHSA-wr3p-r5fj-wf9](https://github.com/advisories/GHSA-wr3p-r5fj-wf97)
[GHSA-r6qh-j42j-pw64](https://github.com/advisories/GHSA-r6qh-j42j-pw64)

I've checked and it seems none of them affects Harbor. Please confirm my take on this one.
Even though this does not affect Harbor it would be nice to have this in at least on the latest release.

Please indicate you've done the following:
- [X] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [X] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Comment by MinerYang** [comment]
This is not in out plan for 2.11. So will close this for now.

**Comment by Vad1mo** [comment]
Why?

**Review by Vad1mo — APPROVED** [review]

**Comment by wy65701436** [comment]
To avoid any uncertainty in the Harbor patch release, we prefer not to upgrade the minor version of Beego; instead, we would like to stick with the patch release. Upgrading to a minor release would introduce code changes that we would like to avoid.

To address the CVEs, I will discuss with the Beego maintainer to see if they can provide a patch for Harbor. If they are unable to assist, we can consider merging this PR.

@Vad1mo 
What are your thoughts on this approach?

**Review by reasonerjt — APPROVED** [review]

**Comment by reasonerjt** [comment]
Let's merge this PR to fix CVEs in v2.11.2

**Pull request merged**
