### PR TITLE
feat: Disable CSRF check for "/c/oidc/onboard" API for authenticating and Onboarding a User via API from Custom CLI

### LINKED ISSUE #16966: Disable CSRF check for "/c/oidc/onboard" API for authenticating and Onboarding a User via API from Custom CLI
We are facing an issue when we are trying to onboard the OIDC user in the harbor via API.

https://goharbor.io/docs/edge/administration/configure-authentication/oidc-auth/

Via UI it works perfectly fine. 

The same functionality is not working via the API. Getting CSRF error. 

As per online research CSRF is only checked when you do activity via browser i.e. where there is some sessions.

Issue is only with this particular API. Other APIs are working fine.

Without onboarding an OIDC user we won’t be able to set secret and therefore docker login will not work.

 
`curl -X 'POST' 'https://xxxx-registry-xxxx-xxx.xxxxxx.com/c/oidc/onboard' \
-H 'Content-Type: application/json' \
-H 'Authorization: Basic YWRtaW46cXNlYSvhcnRpZmFjdG9yeS1hZG1pbg==' \
-d '{"username": gbell@xxxx.com }'
`

`{"errors":[{"code":"FORBIDDEN","message":"CSRF token invalid"}]}`

### PR DESCRIPTION
**Pull request by Rajpratik71**
Thank you for contributing to Harbor!

# Comprehensive Summary of your change

# Issue being fixed
Fixes #16966 

Please indicate you've done the following:
- [*] Well Written Title and Summary of the PR
- [*] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [*] Accepted the DCO. Commits without the DCO will delay acceptance.
- [*] Made sure tests are passing and test coverage is added if needed.
- [*] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

Signed-off-by: Pratik Raj <rajpratik71@gmail.com>

### CODE REVIEW

**Comment by AllForNothing** [comment]
@Rajpratik71 Please run `git commit --amend -s` to signoff  to pass the DOC check

**Comment by Rajpratik71** [comment]
@AllForNothing  @Vad1mo  #16969  can be taken as final clean commit.

**Comment by Rajpratik71** [comment]
Also @AllForNothing @Vad1mo 

Can we cherry-pick this fix to older release of Harbor

**Comment by Rajpratik71** [comment]
@reasonerjt  requesting review

**Comment by Vad1mo** [comment]
duplicate

**Pull request closed without merging**
