### PR TITLE
Add chartmuseum migrator tool

### PR DESCRIPTION
**Pull request by thcdrt**
Hello,

As discussed yesterday in the Harbor Community Meeting, I developed a script in golang to migrate Helm charts from Chartmuseum to OCI.

I developed it for our customers, I think it may be useful to others Harbor users.

The main difference with the existing tool is that you don't need to setup a local Harbor with replication.
The script does everything, it pulls Helm charts from Chartmuseum and push it to OCI. 

A progress bar is displayed during the migration to see the progression and having an estimated ETA:
```bash
$ docker run -ti --rm goharbor/chartmuseum-migrator --url $HARBOR_URL --username $HARBOR_USER --password $HARBOR_PASSWORD
2023/06/28 16:17:32 416 Helm charts to migrate from Chartmuseum to OCI
   4% |█████                                                                                                                                        | (19/416, 20 it/min) [56s:19m36s]
```

PS: We should probably find a better name for this script to see the difference with the existing one.

Thomas

### CODE REVIEW

**Review by Vad1mo — CHANGES_REQUESTED** [review]
Excellent tool. 

I think the tool deserves a different location than been hidden under a tools dir in the harbor project. 

1. it is to important for the community.
2. Hardly anyone will find it.

**Comment by stonezdj** [comment]
Could you please provide the url of your repo? we could try and add the link to the chartmuseum migration wiki page?

**Comment by thcdrt** [comment]
> 

For now it's not in a repository, but I can create one under my name or my company if needed.

**Comment by thcdrt** [comment]
> Excellent tool.
> 
> I think the tool deserves a different location than been hidden under a tools dir in the harbor project.
> 
>     1. it is to important for the community.
> 
>     2. Hardly anyone will find it.

Where do you think it would be the more visible ? In a dedicated repository under Harbor organization ?

**Comment by thcdrt** [comment]
@wy65701436 @OrlinVasilev wdyt ?

**Comment by Vad1mo** [comment]
@OrlinVasilev, can you create I new repo in Harbor and allow @thcdrt to push the code in there?

**Comment by thcdrt** [comment]
Closing this in favor of https://github.com/goharbor/chartmuseum-migration-tools/pull/1

**Pull request closed without merging**
