### PR TITLE
i18n: fix password+secret limit tooltips

### PR DESCRIPTION
**Pull request by 0xC0ncord**
# Comprehensive Summary of your change

Some translations specify the (older) limit of 20 characters for passwords and secrets. Update these to specify a limit of 128 characters.

# Issue being fixed
N/A

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Comment by AllForNothing** [comment]
@0xC0ncord Please update other language files as well

**Comment by 0xC0ncord** [comment]
Sorry - didn't realize I missed those. This should be all of them.

**Comment by AllForNothing** [comment]
@0xC0ncord Please rebase your code to pass the `CI / UTTEST` check

**Review by AllForNothing — APPROVED** [review]
lgtm

**Review by wy65701436 — APPROVED** [review]
lgtm

**Pull request merged**
