### PR TITLE
Upgrade to distribution (registry) v3 alpha

### LINKED ISSUE #19150: Harbor has trouble with buildx --cache-to
This is what happens when trying to use --cache-to
```
docker buildx build -f postgresql.Dockerfile . --platform linux/arm64/v8,linux/amd64 --tag demo.goharbor.io/testproject/postgresql-s3:latest --push --cache-to type=registry,ref=demo.goharbor.io/testproject/postgresql-s3:cache
```
```
ERROR: failed to solve: error writing manifest blob: failed commit on ref "sha256:030951621ab6c414e7a35b30124ad0809a5236f0a3b75917ada3ecc6cf86b44e": unexpected status from PUT request to https://harbor.silvenia.dev/v2/library/postgresql-s3/manifests/cache: 404 Not Found
```

### PR DESCRIPTION
**Pull request by AaronDewes**
# Comprehensive Summary of your change

This includes all the benefits of the v3 distribution, but also all breaking changes.

Most notably, Image Manifest v2 Schema v1 support has been dropped, as well as the `oss` and `swift` storage drivers.

Currently, this still relies on v2's github.com/docker/distribution through indirect dependencies.

This PR is a draft because distribution v3 isn't stable yet. However, I am sucessfully running Harbor of this branch.

# Issue being fixed

None

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Comment by wy65701436** [comment]
thanks @AaronDewes , I'm considering using a separate branch for your changes. This approach allows us to conduct thorough testing to prevent any potential regressions.

**Comment by MinerYang** [comment]
Hi @AaronDewes ,

Thanks for your contribution! Would you mind changing the merge branch from main to [distribution_v3_test](https://github.com/goharbor/harbor/tree/distribution_v3_test). We would like to do regression test based on this branch

**Comment by AaronDewes** [comment]
> Hi @AaronDewes ,
> 
> Thanks for your contribution! Would you mind changing the merge branch from main to [distribution_v3_test](https://github.com/goharbor/harbor/tree/distribution_v3_test). We would like to do regression test based on this branch

Sure, I'll also rebase this later.

**Comment by AaronDewes** [comment]
The files that depend on `"github.com/docker/distribution/registry/client/auth/challenge"` still need refactoring to drop that dependency; but I can do that in a separate PR if you already want to start testing this.

**Comment by wy65701436** [comment]
As for the separate branch, we can proceed by merging the PR and then focus on regression testing. If any issues are identified during testing, we can address them promptly. Additionally, there may be a need to contribute the changes upstream.

@MinerYang Im OK to merge it if the CI passes, and start the regression testing.

**Comment by AaronDewes** [comment]
@wy65701436 I fixed the build failures, but DCO fails now after I rebased on master. Can you merge master into distribution_v3_test first, so the DCO bot passes? And the CI requires another approval because I pushed a commit and I'm a first time contributor.

**Comment by MinerYang** [comment]
Hi @AaronDewes ,
Please help to fix the DCO via git config and amend your commit with `-s`

**Comment by AaronDewes** [comment]
@MinerYang My commit is signed off. The problem is that this PR contains commits from master not yet in the `distribution_v3_test` branch. The commits in `master` are not from me and not all signed off. You or another project member need to  merge master into ``distribution_v3_test`.

**Pull request merged**
