### PR TITLE
aws auth use default creds when none are supplied

### LINKED ISSUE #15007: Unable to create replication for ECR on harbor running under kubernetes
What can we help you?

I have harbor v2.2.2 running on a kubernetes cluster. I see the following error when I try to add an ECR endpoint without specifying access key/secret -

```
2021-05-28T06:08:54Z [ERROR] [/replication/adapter/awsecr/adapter.go:208]: failed to ping registry https://<id>.dkr.<region>.amazonaws.com: EC2RoleRequestError: EC2RoleRequestError: no EC2 instance role found
caused by: RequestError: send request failed
caused by: Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

I have added following environment variables to 'core' and 'jobservice' deployments -

- AWS_ROLE_ARN - Policies/Roles set in AWS to allow read access to my ECR instance
- AWS_WEB_IDENTITY_TOKEN_FILE - I am using kubernetes OIDC discovery and projected service account token
- AWS_REGION - Though it should not be required and is extracted from the registry URL.

I do not have any AWS metadata service running (e.g. KIAM) in the cluster. All IAM policies are in place in AWS for the role I am trying to use. 

I tried an 'awscli' pod with similar environment variables and the aws CLI is able to talk to my ECR using the same role ARN.

I checked https://github.com/goharbor/harbor/issues/13687 but no mention of what changes were done to the core/jobservice pods. Also, the setup explained in the issue uses KIAM to associate roles to pods, which is not my case.

Not sure why is the awecr adaptor trying to fetch roles from metadata despite having those environment variables set ?

### PR DESCRIPTION
**Pull request by caleblloyd**
# Comprehensive Summary of your change

Harbor should not assume that if AWS Credentials are not defined that the user wants to use `ec2rolecreds`.  Rather, it should allow the AWS SDK to resolve credentials by passing `nil` Credentials:

https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html#specifying-credentials

This _should_ be backwards compatible because the defualt provider chain does look for: `4. If your application is running on an Amazon EC2 instance, IAM role for Amazon EC2.`

# Issue being fixed
Fixes #15007

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [ ] Made sure tests are passing and test coverage is added if needed.
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Review by Vad1mo — COMMENTED** [review]
This looks good to me, any idea or guide how to easily test this on AWS?

**Comment by caleblloyd** [comment]
A little tough to unit test because you need actual creds to run through the SDK.  But I purpose-built a couple test binaries in branches on my fork.  This run demonstrates that Before, the `Shared credentials file` is not loaded per AWS' default credential chain, but After it is.

I also tested Good/Bad static creds after the change and there are no regressions there.

## Before Change:

Test source: https://github.com/caleblloyd/harbor/tree/aws-test-after-change/src/awssecrettest

### Auto Detect

```
$ export AWS_PROFILE=my-profile-name
$ export AWS_SDK_LOAD_CONFIG=true
$ ./run.sh https://123456.dkr.ecr.us-east-2.amazonaws.com
2022-12-08T13:21:24-05:00 [INFO] [/pkg/reg/adapter/native/adapter.go:36]: the factory for adapter docker-registry registered
2022-12-08T13:21:24-05:00 [INFO] [/pkg/reg/adapter/awsecr/adapter.go:44]: the factory for adapter aws-ecr registered
2022-12-08T13:21:30-05:00 [FATAL] [/awssecrettest/awssecrettest.go:38]: EC2RoleRequestError: no EC2 instance role found
caused by: RequestError: send request failed
caused by: Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": dial tcp 169.254.169.254:80: connect: no route to host
```


## After Change:

Test source: https://github.com/caleblloyd/harbor/tree/aws-test-after-change/src/awssecrettest

### Auto Detect

```
$ export AWS_PROFILE=my-profile-name
$ export AWS_SDK_LOAD_CONFIG=true
$ ./run.sh https://123456.dkr.ecr.us-east-2.amazonaws.com
2022-12-08T13:18:08-05:00 [INFO] [/pkg/reg/adapter/native/adapter.go:36]: the factory for adapter docker-registry registered
2022-12-08T13:18:08-05:00 [INFO] [/pkg/reg/adapter/awsecr/adapter.go:44]: the factory for adapter aws-ecr registered
<valid token>
```


### With Bad Static Token:

```
$ ./run.sh https://123456.dkr.ecr.us-east-2.amazonaws.com "bad" "bad"
2022-12-08T13:32:40-05:00 [INFO] [/pkg/reg/adapter/native/adapter.go:36]: the factory for adapter docker-registry registered
2022-12-08T13:32:40-05:00 [INFO] [/pkg/reg/adapter/awsecr/adapter.go:44]: the factory for adapter aws-ecr registered
2022-12-08T13:32:41-05:00 [FATAL] [/awssecrettest/awssecrettest.go:38]: UnrecognizedClientException: The security token included in the request is invalid.
        status code: 400, request id: 7c3a3f19-95c8-4cdd-9b39-a1cb07edab2b
exit status 1
```

### With Good Static Token:

$ ./run.sh https://123456.dkr.ecr.us-east-2.amazonaws.com "xxxxxx" "xxxxxx"

```
2022-12-08T13:35:15-05:00 [INFO] [/pkg/reg/adapter/native/adapter.go:36]: the factory for adapter docker-registry registered
2022-12-08T13:35:15-05:00 [INFO] [/pkg/reg/adapter/awsecr/adapter.go:44]: the factory for adapter aws-ecr registered
<valid token>
```

**Comment by caleblloyd** [comment]
## After Change - EC2 Instance Metadata Allows getting token:

image

## After Change - EC2 Instance Metadata Does Not Allow getting token:

image

**Review by stonezdj — COMMENTED** [review]
LGTM

**Review by stonezdj — APPROVED** [review]
LGTM

**Comment by slacki123** [comment]
Hey @Vad1mo, are you the other reviewer on this PR? We're really excited to get this released

**Comment by slacki123** [comment]
Hi @caleblloyd @Vad1mo, what is the status on this PR?

**Review by Vad1mo — APPROVED** [review]

**Review by OrlinVasilev — APPROVED** [review]

**Comment by OrlinVasilev** [comment]
Will close and re-open the PR so we can try to unblock GH actions!

**Comment by Vad1mo** [comment]
@caleblloyd, seems the test fail, can you rebase and we try again. We merge if it becomes green.

**Comment by slacki123** [comment]
@caleblloyd looks like test coverage decreased by 0.01% and failed the checks. Can we do anything about it?

**Comment by caleblloyd** [comment]
All the checks were green, but it was complaining that the commit was not signed, so I have re-pushed the same code except with a signed commit now.  I think the workflows may need to be manually approved again because I am a first-time contributor?

**Pull request merged**
