### PR TITLE
Add autoescape parameter to jinja environments

### PR DESCRIPTION
**Pull request by 100mik**
This resolves the bugs observed [here](https://lift.sonatype.com/result/bhamail/harbor/01FHG1B5AJ8MXCH0A05BMBNWWT?t=CustomTool%20%22Bandit%22%7Cjinja2_autoescape_false) by Sonatype Lift.

### CODE REVIEW

**Comment by MinerYang** [comment]
Hi @100mik ,

Thanks for your contribution! Sorry for the late response and we would like to merge this PR into main branch. Do you have any chance recently to adding the `select_autoescape` option into the jinja migration file for v2.5.0 and v2.6.0 as well ?

**Review by MinerYang — APPROVED** [review]
lgtm

**Comment by MinerYang** [comment]
@100mik 
Hi could you pls add a [DCO](https://probot.github.io/apps/dco/) for this pr, then we will merge it. 
Appreciate!

**Comment by 100mik** [comment]
Sorry for the late response on this one! Fell off my radar
Signed the commit ✅

**Comment by MinerYang** [comment]
HI @100mik ,
NP and thanks for your keep working on this PR. But I didn't see any sign-off on this commit and the DCO CI still not passed.
Would you mind try one more time and you could refer  to this https://docs.pi-hole.net/guides/github/how-to-signoff/

**Comment by wy65701436** [comment]
hi @100mik per the error message of DCO, you probably need to revise the mail address. 

`Expected "Soumik Majumder [soumikm@vmware.com](mailto:soumikm@vmware.com)", but got "Soumik Majumder [soumik712@gmail.com](mailto:soumik712@gmail.com)".`

**Comment by 100mik** [comment]
Did a rebase and fixed up the DCO ✅

**Review by wy65701436 — APPROVED** [review]
lgtm

**Pull request merged**
