### PR TITLE
Aliyun ACR Enterprise Edition replication support

### PR DESCRIPTION
**Pull request by barryz**
Support for Aliyun ACR(aliyun container registry) Enterprise Edition, https://help.aliyun.com/document_detail/111958.html?spm=a2c4g.11186623.6.543.4ff04ecaOm8Xrr
Replication (pull、push、delete) testing was passed.

### CODE REVIEW

**Comment by xh4n3** [comment]
Hi @barryz , are you still working this PR?
Do you need some help?

**Comment by barryz** [comment]
> Hi @barryz , are you still working this PR?
> Do you need some help?

yep, I‘m working on it.

**Comment by barryz** [comment]
> Hi @barryz , are you still working this PR?
> Do you need some help? 

Help to review the code, and I'll resolve the conflicts later.

**Comment by barryz** [comment]
@xh4n3 request to review

**Comment by steven-zou** [comment]
@barryz 

Thanks a lot for submitting this PR to support Aliyun ACR.  Just want to let you know, we're trying to build a replication adapter verification testing framework. After it's ready, we can have capabilities to track the incompatibilities of kinds of application adapters.

So, before the testing framework is ready, we need to hold for a while to merge this PR. Please stay tuned.

**Comment by bitsf** [comment]
@barryz please rebase the code, and make sure the function is working.
And it's better to refer the https://github.com/goharbor/replication-verification, do a local testing for this ACR, and upload the result gif, to prove the function

**Comment by barryz** [comment]
@bitsf I'll be updating the latest code and doing some testing on it in a few days.

**Comment by bitsf** [comment]
@barryz remember to merge the commits as 1 commit, that would help make commit history looks better

**Comment by bitsf** [comment]
@barryz how is this going ?

**Comment by barryz** [comment]
> @barryz how is this going ?


Sorry for the delay in this pr, I will submit an update on the changes this weekend

**Comment by bitsf** [comment]
@barryz your PR seems always has conflicts that can not merge. I'm not sure if you have rebased with the master code?
image
And is it possible that you can provide a test account like tencent-tcr adapter #11470 ?

**Comment by bitsf** [comment]
@barryz update?

**Comment by hyy0322** [comment]
@barryz Hello，will you follow this PR again?

**Comment by fddOs** [comment]
@bitsf  @barryz  Hello，will you follow this PR again?

**Pull request closed without merging**
