### PR TITLE
Provide more useful error info

### LINKED ISSUE #16377: 404 error occurs on Replication Rule create/edit screen
After creating registry endpoint, i created a Replication rule by selecting Pull based mode and the endpoint, then received a http 404 error in the middle of the dialog. I found that the endpoint provider caused this error. 

It is possible to create an (incorrect) Endpoint that fails the Replication Rule create/edit page:
First, create an Endpoint by keeping the Provider as Harbor(The Provider default value is Harbor), but configuring an Artifactory remote server.
Uncheck the certificate validation and save it.
Then create a Replication rule by selecting Pull based mode and the endpoint. You will receive an http 404 error in the middle of the dialog.
If you save, OR the replication rule is created by REST API (which is possible without problem), then the rule will not be editable any more (the edit screen will show the error without loading the parameters of the rule).

Either the endpoint should not be allowed to save, or the error message should be more informative (or, the rule should be editable/configurable even though the endpoint is incorrect).

### PR DESCRIPTION
**Pull request by AllForNothing**
Fixes #16377

1. Provide more useful error info when editing a problematic replication rule
image

Signed-off-by: AllForNothing <sshijun@vmware.com>

Thank you for contributing to Harbor!

# Comprehensive Summary of your change

# Issue being fixed
Fixes #(issue)

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Review by YangJiao0817 — APPROVED** [review]

**Review by wy65701436 — APPROVED** [review]
lgtm

**Comment by AllForNothing** [comment]
@Vad1mo 
I think it is enough for the community to update the related language files before each release date.
It may take too much afford  to track every PR

**Comment by Vad1mo** [comment]
Agree, I just want to find a way how it would be possible to later track each line in the translation to a PR, It is difficult to provide an excellent translation if the context is not present.

**Comment by AllForNothing** [comment]
@AllForNothing Yes, this is for 2.6.   For PRs that have no linked issue,  should be tagged for releases

**Pull request merged**
