### PR TITLE
fix(webhook): fix the verify cert logic of webhook endpoint

### PR DESCRIPTION
**Pull request by chlins**
Close: https://github.com/goharbor/harbor/issues/13016

Signed-off-by: chlins <chlins.zhang@gmail.com>

### CODE REVIEW

**Review by steven-zou — APPROVED** [review]
LGTM

**Comment by reasonerjt** [comment]
Thanks @chlins , but I see another issue in the code:  By default the client should be `secure`

Could you kindly also fix it in this PR?
cc @mmpei

**Comment by reasonerjt** [comment]
Oh and there's same issuei n slack_job.go....

Actually this `GetHTTPInstance` is redundant.  

I suggest removing it and use `httpHelper.clients[insecure]` or `httpHelper.clients[insecure]` directly and the code will be a little easier to understand...

**Review by reasonerjt — CHANGES_REQUESTED** [review]
please see my comments, let's fix the bugs in other parts altogether.

**Comment by chlins** [comment]
@reasonerjt Good advice, i have updated the code, can you take a look again?

**Review by reasonerjt — APPROVED** [review]

**Comment by reasonerjt** [comment]
@chlins  This is awesome!  Thanks!

**Pull request merged**
