### PR TITLE
feat(aliacr-adapter): update url regex foraliacr Enterprise edition

### PR DESCRIPTION
**Pull request by xkos**
aliacr Enterprise edition's url like (Prefix)registry.(Region).cr.aliyuncs.com

Signed-off-by: xkos <ain-sophaur@qq.com>

### CODE REVIEW

**Comment by bitsf** [comment]
can you paste some document or snapshot from aliyun about this url

**Comment by xkos** [comment]
> can you paste some document or snapshot from aliyun about this url

I didn't find a document that explained the url differences, so I copied a picture and a document from aliyun's official documents.   they contained the url for aliacr ee

 (please ignore the red line ):
  quotes from ali's official documents

(this picture from this [https://help.aliyun.com/document_detail/142246.html?spm=a2c4g.11186623.6.564.5435641d2biBas](https://help.aliyun.com/document_detail/142246.html?spm=a2c4g.11186623.6.564.5435641d2biBas))


and 

at end of this document:  [https://help.aliyun.com/document_detail/142247.html?spm=a2c4g.11186623.6.566.31ef37a5XXX9LD](https://help.aliyun.com/document_detail/142247.html?spm=a2c4g.11186623.6.566.31ef37a5XXX9LD)

**Comment by xkos** [comment]
I make a mistake，the sdk seems different between aliacr and aliacr ee,  i need writer a new adapter

**Comment by fddOs** [comment]
@xkos， May I ask what version will support aliacr ee?

**Pull request closed without merging**
