### PR TITLE
fix manifest unknown error code as specs

### PR DESCRIPTION
**Pull request by alexmanno**
**Issue link:** #16515 

Fix error code for manifest unknown following docker api specs, `NOT_FOUND` error code is not supported.
Ref: https://docs.docker.com/registry/spec/api/#errors-2

This error code brokes `docker-compose pull --ignore-pull-failures` when images are not available on the registry (docker agent expects `MANIFEST_UNKNOWN` error instead).

### CODE REVIEW

**Review by Vad1mo — COMMENTED** [review]
any idea where it might impact existing users, who are no expecting `NOT_FOUND`

**Comment by alexmanno** [comment]
@Vad1mo thank you for comment.
As described in #16515 this unexpected error code breaks tools like `docker-compose` or in generally every tool that parse this error code when it pull images from the registry.

**Review by Vad1mo — APPROVED** [review]

**Comment by alexmanno** [comment]
@Vad1mo  There were some failed tests, I fixed them

**Review by Vad1mo — APPROVED** [review]

**Comment by alexmanno** [comment]
@Vad1mo do you have any news on this topic?

**Comment by Morlackx** [comment]
Any ETA about this pr? I'm waiting for this one too 😭

**Comment by it-devops-facile-it** [comment]
Any news?

**Comment by Morlackx** [comment]
Any news? :pray:

**Comment by Vad1mo** [comment]
@goharbor/maintainers can we get some 👀 on that issue?

**Comment by esantoro** [comment]
Hello, any news on this PR ?

We're suffering from this problem too and we'd love to see it merged.

**Comment by peelandsee** [comment]
Hi @wy65701436 @chlins, is there any chance to see this merged soon?
this issue has been open for more than 6 months now!

thanks for your support,

**Comment by Vad1mo** [comment]
We, will address this issue internally next PR review. Mon 28th Nov. 2022

**Comment by Vad1mo** [comment]
We had internal discussion and verified that with the OCI spec, and cam to the conclusion that the current implementation in Harbor aligns with the OCI spec.

**Comment by peelandsee** [comment]
@Vad1mo my understanding was the opposite: the OCI Distribution specs literally say in their [Error Codes](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#error-codes) section
> The code field MUST be one of the following: BLOB_UNKNOWN, BLOB_UPLOAD_INVALID, BLOB_UPLOAD_UNKNOWN, DIGEST_INVALID, MANIFEST_BLOB_UNKNOWN, MANIFEST_INVALID, MANIFEST_UNKNOWN, NAME_INVALID, NAME_UNKNOWN, SIZE_INVALID, UNAUTHORIZED, DENIED, UNSUPPORTED, TOOMANYREQUESTS

Would you please link here the specs you were referring to?

thank you!

**Comment by peelandsee** [comment]
commenting on this to avoid auto-close while @Vad1mo complete the check

**Comment by peelandsee** [comment]
a brand-new dummy comment avoiding auto-close to let @Vad1mo complete his check

**Comment by wy65701436** [comment]
This change does not make sense, as the NOT_FOUND_CODE is a general 404 failure for the API handlers. This code simply means that the object was not found, and is definitely not meant for manifest unknown errors.

**Review by wy65701436 — CHANGES_REQUESTED** [review]
see the comment.

**Pull request closed without merging**
