### PR TITLE
Support for Google Cloud Artifact Registry

### LINKED ISSUE #16973: Please provide ETA for supporting replication to Google Artifact Registry as Registry Endpoint Provider
Google Cloud Platform still supports Google Container Registry but only as a legacy service and it offers Artifact Registry as a better alternative which has many features including artifact support and granular access control. We have a harbor registry as an internal development environment and have been able to replicate it to GCR without issues.  We are unable to replicate to Artifact Registry since Google Artifact Registry is not listed as a Registry End Point Provider.
Could you provide an ETA on when Support for Artifact Registry will be included in Harbor?
Kind Regards
Patrick
image

### PR DESCRIPTION
**Pull request by mrbuk**
Implement an adapter for the Google Artifact Registry (`src/pkg/reg/adapter/googlegar/adapter.go`) based on the logic of the adapter for Google Container Registry (`src/pkg/reg/adapter/googlegcr/adapter.go`).

In contrast to Google Container Registry the native `Authorizer` can't be used for Google Artifact Registry. The native `Authorizer` only adds the Authentication Header to URLs that contain `/v2/`. In case of Google Artifact Registry the actual upload endpoint does not contain a `/v2/` but instead `/artifacts-uploads` like showing below

```
18:30:35 HTTPS GET     europe-west1-docker.pkg.dev /v2/                                                                                                                  401   application/json
18:30:35 HTTPS HEAD    europe-west1-docker.pkg.dev /v2/artifact-registry-sync-121/sync-01/mrbuk/nginx/manifests/1.21                                                     404       [no content]
18:30:35 HTTPS HEAD    europe-west1-docker.pkg.dev /v2/artifact-registry-sync-121/sync-01/mrbuk/nginx/blobs/sha256:036ae8e42548a69ca1cd3f8862cc243dd90230258abecee936cd… 404       [no content]
18:30:35 HTTPS POST    europe-west1-docker.pkg.dev /v2/artifact-registry-sync-121/sync-01/mrbuk/nginx/blobs/uploads/                                                     202       [no content]
18:30:35 HTTPS PUT     europe-west1-docker.pkg.dev /artifacts-uploads/namespaces/artifact-registry-sync-121/repositories/sync-01/uploads/AB38jmJfA4_GYLVqot73sX7TCFk9AK… 401   application/json
```

The logic in the new `Authorizer` is adjusted so the Authorization Header is additionally added for a URL Path starting with `/artifacts-uploads`. The rest of the logic of the native Authorizer is preserved. 

Tests for the change of the behaviour have been added (`src/pkg/reg/adapter/googlegar/authorizer_test.go`)

Instead of adding logic to existing code (e.g. `googlegcr` or `native`) the decision was made to introduce a new package `googlegar` instead. That way regressions/side-effects to existing code should be minimized. 

# Issue being fixed
Fixes #16973

Please indicate you've done the following:
- [X] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [X] Accepted the DCO. Commits without the DCO will delay acceptance.
- [X] Made sure tests are passing and test coverage is added if needed.
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Comment by chlins** [comment]
@mrbuk Thanks for your contribution! I'm not sure do you have any test account or environment to share with me that I can verify this adapter work.

**Comment by mrbuk** [comment]
@chlins I have added another commit to address the [edge-case discussed in the issue](https://github.com/goharbor/harbor/issues/16973#issuecomment-1195975275).

I will be traveling tomorrow but am happy to support with testing from Thursdays (28.07.) if there is a need.

**Comment by chlins** [comment]
@mrbuk Hi, mrbuk, the code looks good to me, but pending on the account for testing, thanks.

**Comment by mrbuk** [comment]
From my perspective this PR can be closed as support was added in Artifact Registry. Artifact Registry now behaves like GCR and the GCR Adapter works out of the box (tested myself with Harbor 2.6.0).

See [comment](https://github.com/goharbor/harbor/issues/16973#issuecomment-1245938649) in #16973

**Pull request closed without merging**
