### PR TITLE
Minor grammar fix.

### PR DESCRIPTION
**Pull request by mboldt**

### CODE REVIEW

**Comment by reasonerjt** [comment]
@mboldt could you fix the DCO issue by signing you comment?

**Comment by mboldt** [comment]
Commit signed; thank you for the nudge.

**Comment by xaleeks** [comment]
@stuclem Hey Stuart, can you resubmit this commit.  This CI failed.

**Comment by stuclem** [comment]
I made the fix in https://github.com/goharbor/harbor/pull/9395. Closing this one.

**Pull request closed without merging**
