### PR TITLE
return err when replication schema v1 image

### LINKED ISSUE #9170: Pull based replication not support schema 1 image
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

I want config harbor replication a old registry, and the old registry have some schema 1 images, all schema 1 images replication failed.

**Steps to reproduce the problem:**

try pull based replication a schema 1 image

**Versions:**
Please specify the versions of following systems.

- harbor version: 1.8.3
- docker engine version: 19.03.2

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .
```
2019-09-19T15:27:31Z [INFO] [/replication/transfer/image/transfer.go:331]: pushing the manifest of image base/dns_checker:v1 ...
2019-09-19T15:27:31Z [ERROR] [/replication/transfer/image/transfer.go:339]: failed to push manifest of image base/dns_checker:v1: http error: code 500, message {"errors":[{"code":"UNKNOWN","message":"unknown error","detail":{}}]}
2019-09-19T15:27:31Z [ERROR] [/replication/transfer/image/transfer.go:143]: http error: code 500, message {"errors":[{"code":"UNKNOWN","message":"unknown error","detail":{}}]}
```

### PR DESCRIPTION
**Pull request by liuxu623**
Fixes #9170

### CODE REVIEW

**Comment by chlins** [comment]
@liuxu623 Thanks, How about squash your commits and check the ci error ?

**Comment by bitsf** [comment]
schema v1 is seldom used now, especially we're going to implement the OCI spec now, and this change may also break quota function, as it will decode manifest to get blob size info.
suggest not support such case now, it will increase code maintain cost

**Comment by liuxu623** [comment]
> schema v1 is seldom used now, especially we're going to implement the OCI spec now, and this change may also break quota function, as it will decode manifest to get blob size info.
> suggest not support such case now, it will increase code maintain cost

or should we skip replication schema v1 image ?

**Comment by xaleeks** [comment]
like @bitsf said, this is not happening since schema 1 is almost completely deprecated

**Comment by bitsf** [comment]
@liuxu623  If skipped, you will not know that some images fail replicate from UI event log, I think current behavior is not quite a problem.

**Comment by liuxu623** [comment]
> @liuxu623 If skipped, you will not know that some images fail replicate from UI event log, I think current behavior is not quite a problem.

```
/ / copy contents between the source and destination registries
	switch manifest.(type) {
	case *schema1.SignedManifest:
		return errors.New("skip copy schema1 image")
	default:
		for _, content := range manifest.References() {
			if err = t.copyContent(content, srcRepo, dstRepo); err != nil {
				return err
			}
		}
	}
```

**Comment by bitsf** [comment]
I think the error message maybe something like "schema v1 image is not supported"

@xaleeks @ywk253100 what do you think, if we need change this now ?

**Comment by xaleeks** [comment]
@bitsf @ywk253100  please check and merge if ok

**Comment by bitsf** [comment]
this fix is conflict with the OCI implement, hold on to see how to deal with this.

**Pull request closed without merging**
