### PR TITLE
Updates goharbor to var IMAGENAMESPACE  in Makefiles to make injectable

### PR DESCRIPTION
**Pull request by morlay**

### CODE REVIEW

**Comment by wy65701436** [comment]
Generall, the varaable BASEIMAGENAMESPACE is used for base images? If we want to apply it to the Makefile, we need a more general name.

**Comment by morlay** [comment]
`IMAGENAMESPACE` ?

**Comment by wy65701436** [comment]
@morlay IMAGENAMESPACE is fine for me, you can just update the code.

**Comment by morlay** [comment]
@wy65701436 updated.

**Comment by chlins** [comment]
ci failed, could you try to rebase main? @morlay

**Review by chlins — APPROVED** [review]
lgtm

**Pull request merged**
