### PR TITLE
Change commit-msg hook.sh address to right place

### PR DESCRIPTION
**Pull request by yuzp1996**
Thank you for contributing to Harbor!

# Comprehensive Summary of your change
When I follow the document to set commit hook.sh with command `curl https://cdn.jsdelivr.net/gh/tommarshall/git-good-commit@v0.6.1/hook.sh >.git/hooks/commit-msg && chmod +x.git/hooks/commit-msg`, I found that the content in .git/hooks/commit-msg is `Moved Permanently. Redirecting to https://cdn.jsdelivr.net/gh/tommarshall/git-good-commit@v0.6.1/hook.sh`.

So I change the address to the moved address.

# Issue being fixed
Fixes #(issue)

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Comment by yuzp1996** [comment]
release-note/ignore-for-release

**Comment by yuzp1996** [comment]
Looks like I have no right to label this PR as `release-note/ignore-for-release`

**Review by wy65701436 — APPROVED** [review]
lgtm

**Comment by reasonerjt** [comment]
Thanks but my coporate firewall is blocking the new URL.
If other maintainers have a chance to verify the content of the script it can be approved and merged.

**Review by chlins — APPROVED** [review]
lgtm

**Pull request merged**
