### PR TITLE
Retention: Implement Evaluator: Keep N Most Recently Pulled

### LINKED ISSUE #6659: Tag Retention: Filter Implementation: Retain the most recently pulled # images
> This issue is a sub-task of the Tag Retention Policies epic (#6654)

Implement the `Retain the most recently pulled # images` filter

### PR DESCRIPTION
**Pull request by nlowe**
Implement the `Keep N Most Recently Pulled/Accessed Artifacts` evaluator.

Fixes #6659 

Signed-off-by: Nathan Lowe public@nlowe.me

### CODE REVIEW

**Comment by steven-zou** [comment]
@nlowe 

feature/tag_retention branch now is broken, @bitsf is fixing it.

**Comment by steven-zou** [comment]
@nlowe 

Please fix the golint error first to fix the CI failure

>/home/travis/gopath/src/github.com/goharbor/harbor/src/pkg/retention/policy/rule/lastPulled/evaluator.go:15:1: don't use MixedCaps in package name; lastPulled should be lastpulled
/home/travis/gopath/src/github.com/goharbor/harbor/src/pkg/retention/policy/rule/lastPulled/evaluator.go:58:1: exported function New should have comment or be unexported
/home/travis/gopath/src/github.com/goharbor/harbor/src/pkg/retention/policy/rule/lastPulled/evaluator_test.go:15:1: don't use MixedCaps in package name; lastPulled should be lastpulled
make: *** [golint] Error 123

**Comment by steven-zou** [comment]
Code for the evaluator is ok for me. Once the failure of CI is fixed, I'll merge it to the feature branch.

cc @nlowe

**Comment by steven-zou** [comment]
@nlowe 

Seems there are some issues in your code branch. Could you please have a check? Or the CI build can pass.

**Comment by nlowe** [comment]
@steven-zou Hmm, I'll try to take a look later today. I had my remotes mixed up in that copy of the repo and accidentially pushed to `goharbor/harbor` instead of my fork. I deleted the branch but must have done it before travis went along and built it, linking the failure to the commit. I think I can fix this by squashing.

**Comment by nlowe** [comment]
New error! @steven-zou did the tracking branch break again? Looks to be a missing config key or something similar:

```python
Traceback (most recent call last):
  File "main.py", line 62, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 59, in main
    prepare_docker_compose(config_dict, with_clair, with_notary, with_chartmuseum)
  File "/usr/src/app/utils/docker_compose.py", line 27, in prepare_docker_compose
    'log_location': configs['log_location'],
KeyError: 'log_location'
The command "if [ "$UTTEST" == true ]; then bash ./tests/travis/ut_install.sh ; fi" failed and exited with 1 during .
```

**Comment by steven-zou** [comment]
> New error! @steven-zou did the tracking branch break again? Looks to be a missing config key or something similar:
> 
> ```python
> Traceback (most recent call last):
>   File "main.py", line 62, in <module>
>     main()
>   File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "main.py", line 59, in main
>     prepare_docker_compose(config_dict, with_clair, with_notary, with_chartmuseum)
>   File "/usr/src/app/utils/docker_compose.py", line 27, in prepare_docker_compose
>     'log_location': configs['log_location'],
> KeyError: 'log_location'
> The command "if [ "$UTTEST" == true ]; then bash ./tests/travis/ut_install.sh ; fi" failed and exited with 1 during .
> ```

@nlowe 

Ignore it, we're fixing it. Once the CI passed, I'll merge your PR into the feature branch.

**Comment by steven-zou** [comment]
merge back to the feature branch to avoid code rebase

**Comment by MrMEEE** [comment]
> > New error! @steven-zou did the tracking branch break again? Looks to be a missing config key or something similar:
> > ```python
> > Traceback (most recent call last):
> >   File "main.py", line 62, in <module>
> >     main()
> >   File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
> >     return self.main(*args, **kwargs)
> >   File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
> >     rv = self.invoke(ctx)
> >   File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
> >     return ctx.invoke(self.callback, **ctx.params)
> >   File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
> >     return callback(*args, **kwargs)
> >   File "main.py", line 59, in main
> >     prepare_docker_compose(config_dict, with_clair, with_notary, with_chartmuseum)
> >   File "/usr/src/app/utils/docker_compose.py", line 27, in prepare_docker_compose
> >     'log_location': configs['log_location'],
> > KeyError: 'log_location'
> > The command "if [ "$UTTEST" == true ]; then bash ./tests/travis/ut_install.sh ; fi" failed and exited with 1 during .
> > ```
> 
> @nlowe
> 
> Ignore it, we're fixing it. Once the CI passed, I'll merge your PR into the feature branch.

How did you fix this?

I'm still getting the missing log_location, when trying to run the prepare script??

**Comment by MrMEEE** [comment]
@nlowe @steven-zou I'm still getting this when running the prepare script...

do you now why???

**Pull request merged**
