### PR TITLE
add unittest for jobservice/common/utils package and fix a issue for IsValidURL

### PR DESCRIPTION
**Pull request by yxxhero**
Signed-off-by: yxxhero <aiopsclub@163.com>
Fixed: https://github.com/goharbor/harbor/issues/15541
## Note
I've seen many programmers use the net/url.Parse() function returning error message as the way to validate URL. However, it is NOT the right way and why you should use a better URL validator, such as govalidator package to validate a URL.
This method has many weaknesses and if you change the str value to d or wwwsocketloopcom, net/url.Parse() function will still pass the broken URL as valid. This is NOT the right way to validate URL.

### CODE REVIEW

**Review by cndoit18 — APPROVED** [review]
LGTM

Is this the same as the one used in kubernetes?

**Comment by yxxhero** [comment]
@steven-zou @ywk253100 2 workflows awaiting approval

**Comment by yxxhero** [comment]
any update?

**Comment by Vad1mo** [comment]
I am bit puzzled here @yxxhero do you have use cases where the current URL parser failed?

**Comment by yxxhero** [comment]
@Vad1mo  so many, example:
1. aaaaa
2. wwww
3. bbbbbb

**Comment by yxxhero** [comment]
I found that there was no URL format verification in the UI!

@steven-zou @ywk253100

**Review by bitsf — APPROVED** [review]
LGTM

**Review by heww — APPROVED** [review]

**Pull request merged**
