### PR TITLE
[cherry-pick]Add release.yml to automate release notes

### PR DESCRIPTION
**Pull request by YangJiao0817**
Use github autogeneration release notes and add action to check if the PR has labels

Complete and more readable relase notes
https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
Signed-off-by: OrlinVasilev <ovasilev@vmware.com>

Thank you for contributing to Harbor!

# Comprehensive Summary of your change

# Issue being fixed
Fixes #(issue)

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Review by wy65701436 — APPROVED** [review]
lgtm

**Review by OrlinVasilev — APPROVED** [review]
lgtm

**Comment by OrlinVasilev** [comment]
@YangJiao0817 For my information :)  why we are cherry picking this into 2.5 branch

**Comment by YangJiao0817** [comment]
@OrlinVasilev Because we will use this in release-2.5.1 to generate release notes.

**Pull request merged**
