### PR TITLE
Updating copyright notices

### PR DESCRIPTION
**Pull request by clouderati**
Replacing copyright notices with "Copyright 2018 The Harbor Authors".

### CODE REVIEW

**Comment by clouderati** [comment]
@caniszczyk @reasonerjt can you ptal?

**Comment by reasonerjt** [comment]
1) Please add sign-off the fix DCO failure.
2) Do we have to remove osl?  It's required for integration with VIC and other products.

**Comment by clouderati** [comment]
Thanks @reasonerjt – not sure why the DCO bot failed; the last commit was signed-off. 😊 

re: osl – my preference is to remove it. I think we should remove the VIC code, too, eventually as it's irrelevant to the rest of the community.

**Comment by clouderati** [comment]
Closing in lieu of https://github.com/goharbor/harbor/pull/5690.

**Pull request closed without merging**
