### PR TITLE
Better mail server compatibility

### LINKED ISSUE #14480: Unable to send emails using Office 356 smtp server
**Expected behavior and actual behavior:**
Unable to send emails using Office 356 smtp server with STARTTLS encryption.

**Steps to reproduce the problem:**

* Email Server: `smtp.office365.com`
* Email Server Port: `587`
* Email Username: `username`
* Email Password: `password`
* Email From: `admin <noreply@domain.com>`
* Email SSL: `True`
* Verify Certificate: `True`

Reference: https://support.microsoft.com/en-us/office/pop-imap-and-stmp-settings-8361e398-8af4-4e97-b147-6c6c4ac95353

**Versions:**

- harbor version: v2.2.0-ec0ba116
- docker engine version: -
- docker-compose version: -

**Additional context:**

- **Log Files**

```
2021-03-19T21:19:19Z [ERROR] [/core/api/email.go:113]: failed to ping email server: tls: first record does not look like a TLS handshake
2021-03-19T21:19:21Z [ERROR] [/core/api/email.go:113]: failed to ping email server: tls: first record does not look like a TLS handshake
2021-03-19T21:22:34Z [ERROR] [/core/api/email.go:113]: failed to ping email server: tls: first record does not look like a TLS handshake
```

#5757

### PR DESCRIPTION
**Pull request by SoMuchForSubtlety**
# Comprehensive Summary of your change
This PR enables sending mail via exchange SMTP servers that force STARTTLS. Most of the code is borrowed from alertmanager[^1]. I tested the code with my company (exchange/STARTTLS) and private (SSL/TLS) email servers, and it works as expected.

# Issue being fixed
Fixes #14480

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

[^1]: https://github.com/prometheus/alertmanager/blob/23f961ec6a9c8a15bf99c83815d35e13d66a4d5d/notify/email/email.go#L118-L196

### CODE REVIEW

**Comment by SimonAlling** [comment]
I suggest changing _compat**a**bility_ to _compat**i**bility_ in the title for improved searchability.

**Comment by SoMuchForSubtlety** [comment]
Hi, when you have a chance could you review my PR?

**Comment by SoMuchForSubtlety** [comment]
This is not stale 🙂

**Comment by wy65701436** [comment]
Hi, we are planning to deprecate the mail configuration as there is no functionality using it.

I'm sorry that this is not acceptable, but thank you for your contribution.

**Pull request closed without merging**
