### PR TITLE
Custom Transports respects system proxy

### PR DESCRIPTION
**Pull request by everydaynerd**
The built in transport in Go respects the system proxy settings (/etc/profile.env for example).  The  custom transports used in Harbor do not respect the system proxy settings, so added `Proxy: http.ProxyFromEnvironment,` to the custom transports.  

This enables the ability to add proxy environment to YAML files.  For example:

`environment:
      - http_proxy=http://192.168.1.8:8080
      - https_proxy=http://192.168.1.8:8080
      - no_proxy=log,registry,mysql,adminserver,ui,jobservice,proxy,postgres,clair,notary-server,notary-signer,notary-db,127.0.0.1,localhost,corp.network
  `

### CODE REVIEW

**Comment by everydaynerd** [comment]
Not sure how adding 6 lines of code can make the code coverage go from 56.161% to -0.05%

**Comment by everydaynerd** [comment]
How does one get a review on a PR? Asking for a friend.

**Comment by jomeier** [comment]
Harbor is not working behind our corporate proxy. Could you fix that please? Injecting the http_proxy environment variable seems not to make any effect.

Is this pull request the solution ?

**Comment by clouderati** [comment]
Hi @everydaynerd – super sorry for dropping the ball on this. We're cleaning up old PRs and issues. If you're still interested in contributing this feature please ping me and I'll help get this reviewed and merged.

Apologies again!

**Comment by jomeier** [comment]
@clouderati 
Is this issue solved? I don't think so.

**Comment by clouderati** [comment]
Hi @jomeier – this is actually a PR, not an issue. I haven't tested whether it will fix potential issues of Harbor running behind a proxy.

Very happy to reopen, but the PR will have to be rebased before it can be merged.

In an effort to track your particular problem, can you open a separate issue and describe the problem you're hitting in detail? This will ensure that it doesn't fall through the cracks.

Thoughts?

**Comment by everydaynerd** [comment]
@clouderati I'd love to have this merged in.  This change I opened the PR for is what we did to make it work with our corporate proxy.

**Comment by clouderati** [comment]
Wahoo! Thanks @everydaynerd – this contribution is super welcomed. :smile:

Looks a few conflicts need to be ironed out. I'll review as soon as you rebase. 👍  Thanks again for spending time on this; it's greatly appreciated!

**Comment by everydaynerd** [comment]
> Wahoo! Thanks @everydaynerd – this contribution is super welcomed. 😄
> 
> Looks a few conflicts need to be ironed out. I'll review as soon as you rebase. 👍 Thanks again for spending time on this; it's greatly appreciated!

No problem - glad to give back, we really love this product.  It may take me some time to rebase due to current workload, but get it done as soon as possible.

**Comment by clouderati** [comment]
Absolutely no rush. :+1:

**Comment by steven-zou** [comment]
@everydaynerd 

PR is also outdated, please rebase it and submit it again. We'll merge it after review. Thanks!
Don't forget to [sign-off](https://probot.github.io/apps/dco/) your commit.

**Comment by clouderati** [comment]
Gentle ping. Happy to close and re-open when you have spare cycles to contribute @everydaynerd. No rush at all. :+1:

**Comment by everydaynerd** [comment]
Thanks James,  It will be Q1 of 19 before I get on this. My son was killed
by a drunk driver last week, so taking some time...

{
    "name"  : "Dan Burgess",
    "email" : "dan@everydaynerd.com",
    "phone" : "864.990.2101"
}

**Comment by salkin** [comment]
@everydaynerd if ok for you I can also submit the change as we ended up doing the same fix on the newer codebase

**Comment by everydaynerd** [comment]
That would be awesome - thank you!

**Comment by ywk253100** [comment]
As @salkin has submitted another PR #6541 to fix this, closing this one. Thanks a lot @everydaynerd .

**Pull request closed without merging**
