### PR TITLE
19559 cannot see full label easily

### LINKED ISSUE #19559: Cannot see full label easily
**Expected behavior and actual behavior:**
Actually, when labels are too long, the only way I found to show it fully is to open the developer's console.
It should be great to see it fully via a hover.

**Steps to reproduce the problem:**
Go on a Project --> On a Repository --> Select an Artifact --> Open Actions menu --> Click on Add labels : if there is too long labels, you will not see them fully.
And when a long label is assigned to an Artifact, same, you cannot see them fully.

**Versions:**

- harbor version: [v2.7.3-252a0b7c & v2.9.0-6d1ad65c]

### PR DESCRIPTION
**Pull request by jmichot-exotec**
# Comprehensive Summary of your change
Added css to see full label on hover

# Issue being fixed
Fixes #19559 
Closes #19559 

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [ ] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [ ] Made sure tests are passing and test coverage is added if needed.
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Comment by AllForNothing** [comment]
@jmichot-exotec Thanks for the PR to improve the label view.
Usually, we use the `title` property to show the full content for a hover action. Could you update your PR with the 'title way'?

**Comment by jmichot-exotec** [comment]
@AllForNothing modification done on label hover !

**Review by AllForNothing — APPROVED** [review]
lgtm

**Review by YangJiao0817 — APPROVED** [review]

**Comment by OrlinVasilev** [comment]
@jmichot-exotec congrats on merging your first PR here :))) welcome to the club

**Pull request merged**
