### PR TITLE
Feat(Logging): create new JSON logger

### LINKED ISSUE #15820: Json logs
Actually, logs are formatted as rsyslog format.
We use fluentbit as log collector in our kubernetes cluster. 

Formatting the logs in Json would allow the parsing of the logs and the possibility of advanced search in our ELK stack.

Thanks in advance

### PR DESCRIPTION
**Pull request by sebglon**
Thank you for contributing to Harbor!

# Comprehensive Summary of your change
Add new formatter  for JSON format log.
New Env variable to select format type: `LOG_FORMAT`; value is `json` for Jsonf format else we use the default text format
# Issue being fixed
Fixes #15820

Please indicate you've done the following:
- [ ] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [ ] Made sure tests are passing and test coverage is added if needed.
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Review by Vad1mo — COMMENTED** [review]
This PR needs to be mentioned in the docs

**Comment by sebglon** [comment]
@Vad1mo doc issue is created for tracking

**Comment by Vad1mo** [comment]
I was expecting a PR 😂 or an issue with a bit more context that me, you or anybody else knows what to do in a week

**Comment by OrlinVasilev** [comment]
@sebglon can you please point me to the docs PR ? thanks

**Comment by wy65701436** [comment]
@sebglon would you mind to fix the UI failure?

**Comment by OrlinVasilev** [comment]
@sebglon are you still up for working on this :) it will be great!

**Pull request closed without merging**
