### PR TITLE
fix: oidc token is not respected in /service/token endpoint

### PR DESCRIPTION
**Pull request by tmaroschik**
I can query the harbor API with my OIDC token, but unfortunately I cannot get a distribution token.

This PR fixes that. 

This PR enables us to build facades/proxies to harbor that act as custom PHP composer or JS npm registries over OCI Artifacts with OIDC Token support instead of CLI secrets.

### CODE REVIEW

**Comment by Vad1mo** [comment]
here is the link to the discussion me and @tmaroschik had on slack 
https://cloud-native.slack.com/archives/CC1E09J6S/p1646050852588059

**Comment by tmaroschik** [comment]
Any chance you can take a look at this PR @reasonerjt?

**Comment by tmaroschik** [comment]
This PR is not stale.

**Review by wy65701436 — APPROVED** [review]
lgtm

**Review by Vad1mo — APPROVED** [review]

**Pull request merged**
