### PR TITLE
fix: fix quay adapter catalog api return error

### PR DESCRIPTION
**Pull request by chlins**
Close: https://github.com/goharbor/harbor/issues/13200

Signed-off-by: chlins <chlins.zhang@gmail.com>

### CODE REVIEW

**Comment by bitsf** [comment]
hi @chlins can you also upload a test result for case
https://github.com/goharbor/replication-verification/blob/master/master/cases/Quay.robot
you can change the `bitsf/{photon,alpine}` to `bitsf/{photon,alpine*}` in order to test the catalog api

**Comment by chlins** [comment]
@bitsf Maybe we can also update the replication verification quay case to cover the scene. How do you think?

Before fix, if use fuzzy pattern which will call catlog cause below error:
图片
图片

After fix:
图片
图片

**Comment by steven-zou** [comment]
> @bitsf Maybe we can also update the replication verification quay case to cover the scene. How do you think?
> 
> Before fix, if use fuzzy pattern which will call catlog cause below error:
> 图片
> 图片
> 
> After fix:
> 图片
> 图片

@bitsf I think it's a good idea

cc @chlins

**Review by steven-zou — APPROVED** [review]
LGTM

CC @bitsf

**Comment by bitsf** [comment]
@chlins yes, I will fix the case

**Review by bitsf — APPROVED** [review]

**Comment by steven-zou** [comment]
@chlins 

This fix should be cherry-picked to the 2.1 branch

**Pull request merged**
