### PR TITLE
add default namespace library if not specified

### PR DESCRIPTION
**Pull request by aladjadj**
PR refer to issue #5143

### CODE REVIEW

**Comment by reasonerjt** [comment]
This change seems only add a namespace `library` in permission checking?
So if a user pushes to an image like `$registry_host/$repo:$tag`  will require the permission of library, but it won't actually be pushed to the `/library/$repo` in the storage.

This seems a workaround to me.

**Comment by aladjadj** [comment]
yes you right,
the solution maybe to fix the error 500 into harbor when pull image without "project"
and redirect root path to "library" in router ( nginx ) to match with Harbor concept 

what do you think ?

**Comment by jessehu** [comment]
This feature is great!

**Comment by reasonerjt** [comment]
Sorry I don't think it's the right thing to do, because in the registry it will still be stored in the storage of 
/$repo not /library/$repo.  

The code change in permission checking will introduce confusing inconsistency.  You'll at least also have to deal with the case when calling `GET v2/_catalog` and add the `library` to the images that does not have  namespace.  And it may become tricky when triggering Clair to scan the image(it may not, we need to check the code).

The benefit of this change is just a shortcut but the inconsistency it introduced may cause problems in the future.

**Pull request closed without merging**
