### PR TITLE
Fix auth config oidc scope regex

### PR DESCRIPTION
**Pull request by rlacko58**
# Comprehensive Summary of your change

This PR fixes the OIDC Auth scopes validation on the auth config page to comply with RFC standards.

Example scopes that are not compatible currently with Harbor's validation:
- [Google OAuth](https://developers.google.com/identity/protocols/oauth2/scopes)
- [Microsoft Oauth](https://learn.microsoft.com/en-us/entra/identity-platform/scopes-oidc)

RFC:
https://datatracker.ietf.org/doc/html/rfc6749#appendix-A.4
     scope       = scope-token *( SP scope-token )
     scope-token = 1*( %x21 / %x23-5B / %x5D-7E )

A scope is composed of one or more scope-tokens separated by spaces, and each scope-token must consist of one or more characters defined by NQCHAR.

https://datatracker.ietf.org/doc/html/rfc6749#appendix-A
NQCHAR     = %x21 / %x23-5B / %x5D-7E
NQCHAR includes all printable ASCII characters except
double quote ("), backslash (\), and space ( ).

Breakdown of changes:
- Previously: `[\w.]`
- New regex: `((?!["\\ ])[ -~])`
  `[ -~]` - Match all ASCII characters between space ( ) and tilde (~)
  `(?!["\\ ])` - Negative lookahead ignore double quote ("), backslash (\), and space ( )

Tests of this regex: https://regex101.com/r/IrNM6D/1

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Review by stonezdj — APPROVED** [review]
LGTM

**Review by Vad1mo — APPROVED** [review]

**Comment by Vad1mo** [comment]
@rlacko58 @stonezdj, before merging and accepting, can you think of any potential backward incompatibilities?

**Comment by rlacko58** [comment]
It's compatible with the previous regex. This just further extends the list of allowed characters. @Vad1mo 

Previously we had \w. Which represents a-zA-Z0-9_

In the new one we extend this list with all ascii characters between space ( ) and tilde (~). Only exception is double quote ("), backslash (), and space ( ).

**Comment by Vad1mo** [comment]
love the test comparison here https://regex101.com/r/IrNM6D/1, attaching it here for history purposes. 

image

**Comment by rlacko58** [comment]
I see the Prettier test failed. I'll update the PR later today/tomorrow. @Vad1mo

**Comment by Vad1mo** [comment]
@rlacko58 can you take a look into the issues? there are some linter errors.

**Comment by reasonerjt** [comment]
@rlacko58 
Thanks for the contribution!
Do you plan to continue working on this PR?  If the answer's yes, could you please rebase and fix the CI errors?

**Comment by rlacko58** [comment]
@reasonerjt  Thanks for the reminder. It should be good to go now. I've put the change to a separate commit to make the review easier

**Comment by reasonerjt** [comment]
@rlacko58 Thanks for the update.  There're still some lint errors.  Could you check?

**Comment by rlacko58** [comment]
@reasonerjt Now it should be finally good to go

**Comment by OrlinVasilev** [comment]
Did someone tested that @goharbor/all-maintainers ? I think we can merge that

**Pull request merged**
