### PR TITLE
Adapt Multiple Type of Database

### PR DESCRIPTION
**Pull request by JinXingYoung**
Support MySQL and MariaDB
Related issue: https://github.com/goharbor/harbor/issues/6534
Signed-off-by: yvonnexyang <yvonnexyang@tencent.com>

### CODE REVIEW

**Comment by chlins** [comment]
@JinXingYoung Thanks! I think we need to add MySQL and MariaDB integration tests in the CI to ensure the feature works well, you can refer `.github/workflows/CI.yaml`.

**Comment by JinXingYoung** [comment]
> @JinXingYoung Thanks! I think we need to add MySQL and MariaDB integration tests in the CI to ensure the feature works well, you can refer `.github/workflows/CI.yaml`.

@chlins OK, I'll  refer to CI.yaml and add some new tests.

**Comment by JinXingYoung** [comment]
@chlins I've added MySQL and MariaDB integration tests in the CI. Could you please help  to approve the running workflows, thanks.

**Comment by Vad1mo** [comment]
I am marking this PR as draft for now

**Pull request closed without merging**
