### PR TITLE
feat: replace redis MULTI command with lua script

### PR DESCRIPTION
**Pull request by j4ckstraw**
when redis proxy is not support MULTI command, replace it with lua script

Thank you for contributing to Harbor!

# Comprehensive Summary of your change

# Issue being fixed
Fixes #(issue)

Please indicate you've done the following:
- [ ] Well Written Title and Summary of the PR
- [ ] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [ ] Accepted the DCO. Commits without the DCO will delay acceptance.
- [ ] Made sure tests are passing and test coverage is added if needed.
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Comment by Vad1mo** [comment]
can you elaborate or reference to ticket this problem si solving?

**Comment by j4ckstraw** [comment]
> Can you elaborate in more detail or reference to an issue this PR is solving?

We use redis proxy which not support MULTI command, so I use lua script replace it. I heard that MULTI is not recommended, maybe anyone need this.

**Comment by stonezdj** [comment]
The jobservice is based on gocraft/worker, it used the MULTI command too.
https://github.com/goharbor/harbor/blob/2a40068d7520346721afa959399bd10e916c83a1/src/vendor/github.com/gocraft/work/worker.go#L228

**Comment by j4ckstraw** [comment]
> The jobservice is based on gocraft/worker, it used the MULTI command too.
> 
> https://github.com/goharbor/harbor/blob/2a40068d7520346721afa959399bd10e916c83a1/src/vendor/github.com/gocraft/work/worker.go#L228

Yes, I also change this vendor file in my internal version, while I don't think change this vendor file in harbor project is a good idea.  what do you think？

**Pull request closed without merging**
