### PR TITLE
Add Turkish Language

### PR DESCRIPTION
**Pull request by dorukhanguloz**
Turkish language support was added.
Signed-off-by: dorukhanguloz <dorukhanguloz@hotmail.com>

### CODE REVIEW

**Comment by steven-zou** [comment]
@dorukhanguloz 
  Thank you very much for such a great contribution. Hope more contributions coming in in the feature.

@goharbor/all-maintainers 

  If no rejection, we'll merge this PR into code base later!

**Comment by zhoumeina** [comment]
Please take a look at app.module.ts, need to register locale data as other languages. registerLocaleData();

**Comment by michmike** [comment]
@dorukhanguloz please see the comment above about one small change. thanks!

**Comment by dorukhanguloz** [comment]
> Please take a look at app.module.ts, need to register locale data as other languages. registerLocaleData();Otherwise, it will report error when switch Turkish language.

I added. Sorry for late.

**Comment by jwangyangls** [comment]
@dorukhanguloz 
 You should merge four commits into one commit before committing, and then the pull request can be merged.

**Comment by dorukhanguloz** [comment]
> You should merge four commits into one commit before committing, and then the pull request can be merged.

I merged them.

**Comment by kofj** [comment]
@dorukhanguloz Pls rebase and resolve, I'll approve later.

**Pull request merged**
