### PR TITLE
Provides full translation for Brazilian Portuguese.

### PR DESCRIPTION
**Pull request by juliohm1978**
Fixes https://github.com/goharbor/harbor/issues/15454.

Signed-off-by: Julio Morimoto <julio@morimoto.net.br>

### CODE REVIEW

**Comment by AllForNothing** [comment]
@juliohm1978  Thanks for your PR
Can you invite someone to review your PR, as there is no pr-br speaker in the Harbor team?
Then rebase your code to resolve conflict

**Review by yanji09 — APPROVED** [review]

**Review by AllForNothing — APPROVED** [review]

**Comment by juliohm1978** [comment]
Thank you, guys. My apologies if I couldn't get anyone in time to review this. I am not a translator by profession, but as a Brazilian I have been proficient in English throughout my career as a developer and sysadmin. There are certainly a few mistakes in there. I'll provide more PRs in the future to correct them.

On the same note, I would also be glad to join as a part-time member to keep the pt-BR translation up to date. I can certainly manage this in my free time.

**Comment by AllForNothing** [comment]
@juliohm1978 It would be great for keeping the pt-BR translation up to date. Thanks for the contribution!

**Comment by grstein** [comment]
I went late to review, sorry. I read all the diff and can confirm that Julio's translation really bumped the pt-br quality of Harbor. Today, it is very confusing and mixed with English terms. It will be very cool to see Harbor 100% in brasilian portuguese! 

Congratulations for your job, @juliohm1978

**Comment by AllForNothing** [comment]
@grstein As the development progresses，new terms in English will be continuously added to language JSON files. So new PRs to update your language file are welcome. And the best time node is before each new version is released

**Pull request merged**
