### PR TITLE
I think the 'or' should be 'and'

### PR DESCRIPTION
**Pull request by silenceshell**
I think the 'or' should be 'and'. The migrator backups both.

Signed-off-by: silenceshell me@ieevee.com

### CODE REVIEW

**Comment by clouderati** [comment]
lgtm – thanks for the contribution @silenceshell!

**Comment by silenceshell** [comment]
Signed-off-by: silenceshell <me@ieevee.com>

**Comment by clouderati** [comment]
@ywk253100 can you please comment on this PR since we're also moving the Helm bits to [another repo](https://github.com/goharbor/harbor/pull/5693)?

**Comment by silenceshell** [comment]
@ywk253100 I have delete the commit for Harbor chart.

**Comment by silenceshell** [comment]
hi @clouderati , I have delete the commit for Harbor chart, would you please review this PR again? Thanks.

**Comment by clouderati** [comment]
@silenceshell many thanks for the contribution!

**Comment by silenceshell** [comment]
@clouderati You are welcome :)

**Pull request merged**
