### PR TITLE
Add optional DBAuth

### PR DESCRIPTION
**Pull request by dioguerra**
fixes: https://github.com/goharbor/harbor/issues/9006

[portal]
* Only show username:password login fields for DBAuth if enabled (default: true)

[core]
* Add BASIC_AUTH_ENABLED to api/configurations to enable/disable user authentication using DBAuth (includes admin)

**HALP NEEDED**
I didn't manage to compile the core container after applying changes, and i don't know why it's not triggering

Also, my idea here is to enable/disable the registration of the DBAuth AuthN method so that authentication.login() would only work with other set-up methods. Do you think this is the correct way.
This actually depends on how the harbor-core reloads the configurations after the user submits these.

This is my first commit here, so i am a bit lost, still trying to understand the Arch. Some points would be nice

### CODE REVIEW

**Comment by MrD2** [comment]
I'm still having this error: '{"errors":[{"code":"BAD_REQUEST","message":"configure item is not defined in metadata, item name: basic_auth_enabled"}]}'

Which means that the parameter is not being correctly registered into swagger's API.

Any thoughts?

**Comment by reasonerjt** [comment]
I don't disagree this may be useful in your scenario, but we want to balance the configurations that are exposed and options that are provide to user in order to control the complexity.

After review, we believe this is not a very widely required use case, hence, I'm closing this PR.

Please feel free to ping me on slack if you want to discuss.

**Comment by rochaporto** [comment]
Is this really adding a lot of complexity? We still have users passing their user/pass in this form thinking they're logging in with their SSO credentials. We have an open issue with our security team regarding this, and might need a downstream patch if this doesn't make it upstream - meaning cloning the repo, rebuilding packages, releasing downstream, etc.

**Comment by reasonerjt** [comment]
@rochaporto This PR alone does not adding A LOT complexity.

I'm discussing with Diogo on slack for a way to mitigate the security issue without having to add another configuration.  Hopefully, he will open another issue and provide a fix that everyone is OK with.

**Comment by DaniD3v** [comment]
> @rochaporto This PR alone does not adding A LOT complexity.
> 
> I'm discussing with Diogo on slack for a way to mitigate the security issue without having to add another configuration. Hopefully, he will open another issue and provide a fix that everyone is OK with.

@reasonerjt 

What was the outcome of that discussion? #9006 has 17 upvotes.
This is pretty widely requested and poses an issue to every company with strict compliance needs.

**Pull request closed without merging**
