### PR TITLE
fix: panic recover when stream

### PR DESCRIPTION
**Pull request by hunshcn**
Thank you for contributing to Harbor!

# Comprehensive Summary of your change

when download a layer and the http request between core and registry is aborted, the ReverseProxy handler will panic. [net/http/httputil: ReverseProxy should use ErrAbortHandler on read error while copying body · Issue ](https://github.com/golang/go/issues/23643)

but beego will recover this panic and show a error page. so the layer will like this 

tar content

If this is a client which has auto-retry with broken-point continuingly-transferring, the content will be dirty.(include error html page), such as wget and containerd [link to code](https://github.com/containerd/containerd/blob/8167751f569c9374a6c3ef5b39a42629577a543a/remotes/docker/fetcher.go#L160)

wget

after retry with breakpoint transmission, the content will be wrong.
sha256sum

maybe related to https://github.com/containerd/containerd/issues/3974#issuecomment-989510035 , https://github.com/goharbor/harbor/issues/17643 , https://github.com/goharbor/harbor/issues/16556

# Issue being fixed
Fixes #(issue)

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository]([GitHub - goharbor/website: Source for the main Harbor website](https://github.com/goharbor/website)).

### CODE REVIEW

**Comment by Vad1mo** [comment]
@hunshcn thank you for your contribution, we will review the issue.
is there any possibility we might be able to reproduce the error?

**Comment by hunshcn** [comment]
> @hunshcn thank you for your contribution, we will review the issue. is there any possibility we might be able to reproduce the error?

This error can be reproduced by using unstable s3 storage.

But the most convenient way is to panic http.ErrAbortHandler in the code.

**Comment by hunshcn** [comment]
Actually, there should be no error message after the file download starts.

**Comment by hunshcn** [comment]
> @hunshcn So this issue only happened when the `runmode=dev`?

yes

**Comment by chlins** [comment]
@hunshcn Hi, personally I think since current dev mode is prod which will not pose to this issue, and also the behavior is designed by upstream beego side, we can add your modification for this case, but there are many other similar cases, from my side the behavior from beego may also make sense for dev && debug, so I suggest keep current behavior and resolve the issue from update the mode to prod, do you think so? But great thanks for pointing this.

**Comment by hunshcn** [comment]
> @hunshcn Hi, personally I think since current dev mode is prod which will not pose to this issue, and also the behavior is designed by upstream beego side, we can add your modification for this case, but there are many other similar cases, from my side the behavior from beego may also make sense for dev && debug, so I suggest keep current behavior and resolve the issue from update the mode to prod, do you think so? But great thanks for pointing this.

you are right, but I still think it's a very bad thing to download files with abnormal content. kubelet cannot handle this  situation.

**Comment by chlins** [comment]
@hunshcn I think the behavior is designed by beego dev mode, although we can handle this case from harbor side as your pr described, but such a change is not universal, I suggest open issue on the upstream beego project or keep the current behavior.

**Pull request closed without merging**
