### PR TITLE
GitLab replication adapter: improve projects search

### PR DESCRIPTION
**Pull request by hlubek**
Adds a query parameter to search in ancestor namespaces which should
find projects in subgroups matching a name filter component.

### CODE REVIEW

**Comment by hlubek** [comment]
Pull request created as mentioned in https://github.com/goharbor/harbor/issues/13364#issuecomment-746119483

**Review by bitsf — APPROVED** [review]
As I can't contact with the original developer for this gitlab adapter, so I suppose your PR is already tested for many cases and worked well

**Comment by hlubek** [comment]
@bitsf I couldn't test all different scenarios with GitLab of course, since I only verified it against our instance (recent version) with lots of projects in different hierarchies. Reading the GitLab source code the `search_namespaces` parameter should only return more matches for projects (which are later filtered out by the adapter according to the name filter) - so it should not be worse than the current solution.

As written in #13364 the solution of using a (fuzzy) search for projects is not very robust and should be replaced by iterating over groups/projects via the GitLab API. I can have a look at that soon - but for now this fix would at least improve things.

**Comment by bitsf** [comment]
that would be quite helpful if someone can figure out how gitlab API should work well.

**Comment by bitsf** [comment]
hi @hlubek , I test this, we should not use `search_namespaces`, as it will also filter projects with namespace matched, not name matched
such as repo 'test/abc/repo1' and 'user/test/repo2', if filter with 'user/test/*', the two projects will be filtered both.

I think the issue that you faced is because param `membership=1` which 'Limit projects that the current user is a member of'
So you should add the user to all projects needed.

**Comment by bitsf** [comment]
oh, I just understand your problem, I didn't notice gitlab can create multi level sub groups, I thought it can only has user as first level

**Pull request closed without merging**
