### PR TITLE
Fix project setup step.

### PR DESCRIPTION
**Pull request by akshatdalton**
Fixes `CONTRIBUTING.md` guide on how to get the code.

Thank you for contributing to Harbor!

# Comprehensive Summary of your change

# Issue being fixed
Fixes https://cloud-native.slack.com/archives/CC1E0J0MC/p1677094103138229

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Review by Vad1mo — APPROVED** [review]
thanks for the update

**Review by chlins — APPROVED** [review]
lgtm

**Review by OrlinVasilev — APPROVED** [review]
lgtm

**Comment by OrlinVasilev** [comment]
@akshatdalton congrats on your first merged PR :) Welcome to the club!

**Pull request merged**
