### PR TITLE
fix: reduce the execution sweep job frequency from hourly to daily

### PR DESCRIPTION
**Pull request by chlins**
Reduce the execution sweep job frequency from hourly to daily.

Thank you for contributing to Harbor!

# Comprehensive Summary of your change

# Issue being fixed
Fixes https://github.com/goharbor/harbor/issues/20255

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Review by wy65701436 — APPROVED** [review]
lgtm

**Review by stonezdj — APPROVED** [review]

**Comment by another-novelty** [comment]
When is this fix going to be in a release? Or did I miss it in the release notes?

**Comment by chlins** [comment]
> When is this fix going to be in a release? Or did I miss it in the release notes?

This issue was fixed in the version 2.11.

**Comment by another-novelty** [comment]
image
We currently have 2.11.1 installed, but the cron setting does not seem to be updated

**Pull request merged**
