### PR TITLE
fix broken demo link in the readme file

### PR DESCRIPTION
**Pull request by theJaxon**

### CODE REVIEW

**Comment by xaleeks** [comment]
@theJaxon  Thanks for catching this, please sign your commit.  And please cherry pick to release-2.0.0 if possible.  Thx!

**Comment by bitsf** [comment]
@theJaxon remove the  .swp files

**Comment by theJaxon** [comment]
> rebase the code, you should just have one commit

I think instead of fixing it i ended up creating even more commits 
what i did was 
git rebase -i HEAD~9

replaced 8 of the pick with squash so that only 1 is left 
added the commit message 
git pull 
git push 

Can someone help me fix this ?

**Comment by bitsf** [comment]
you can

git checkout master
git cherry-pick [commit-id]
git commit -s --amend
git push --force


or
git checkout master
manually fix again
git add .
git commit -s
git push

**Comment by bitsf** [comment]
just push 1 commit for 1 PR, you can use --amend for each change, don't push many commits.

**Pull request closed without merging**
