### PR TITLE
Add SearchDN error, mark field as required in UI

### PR DESCRIPTION
**Pull request by sixeIa**
…ection

Fix #15196

Signed-off-by: Alexis <60alexis@gmail.com>

### CODE REVIEW

**Review by stonezdj — COMMENTED** [review]
The original logic is to verify the SearchDn and the error message is incorrect, could you please add a new error for it.

```
 // ErrEmptySearchDN ...
var ErrEmptySearchDN = errors.New("empty search dn")
```

**Comment by sixeIa** [comment]
SearchDN isn't a mandatory field (according to the UI) so why should we check if it is empty or not ?

**Comment by stonezdj** [comment]
> SearchDN isn't a mandatory field (according to the UI) so why should we check if it is empty or not ?
 searchDN is mandatory in backend

**Comment by sixeIa** [comment]
@stonezdj I've done the required changes and edited UI to mark is as required for user. Tell me if there are additional code to review/change.

**Review by stonezdj — APPROVED** [review]

**Comment by reasonerjt** [comment]
Please correct the commit message.

**Comment by sixeIa** [comment]
@reasonerjt modified commit history.

**Review by reasonerjt — APPROVED** [review]

**Pull request merged**
