### PR TITLE
add swagger user guide

### PR DESCRIPTION
**Pull request by zhoumeina**
add swagger user guide.

### CODE REVIEW

**Comment by reasonerjt** [comment]
It should be part of the user guide?  And we only have to let user know how to navigate to that piece of UI via Harbor's Portal.

**Comment by reasonerjt** [comment]
1.  It's REST API not Swagger API.  So it should reword to "Invoke REST API from Portal" or "Try REST API via API Explorer"
2. The image looks extremely big in user guide markdown file.

**Comment by zhoumeina** [comment]
> 1. It's REST API not Swagger API.  So it should reword to "Invoke REST API from Portal" or "Try REST API via API Explorer"
> 2. The image looks extremely big in user guide markdown file.

done.

**Comment by zhoumeina** [comment]
> It should be part of the user guide? And we only have to let user know how to navigate to that piece of UI via Harbor's Portal.

done.

**Pull request merged**
