### PR TITLE
fix copy artifact accessory quota issue

### PR DESCRIPTION
**Pull request by wy65701436**
It needs to request quota for accessory on copying artifact.

Signed-off-by: wang yan <wangyan@vmware.com>

Thank you for contributing to Harbor!

# Comprehensive Summary of your change

# Issue being fixed
Fixes #(17207)

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Review by chlins — APPROVED** [review]
lgtm

**Comment by MinerYang** [comment]
when I **sign an artifact inside a manifest list**, then copy the index artifact, **quota usage is incorrect**.

Other cases below are working fine.
```
copy simple standalone image
copy standalone image with a cosign accessory 
copy standalone image with multi cosign accessory 
copy simple manifest index artifact
copy manifest index artifact with a cosign accessory on the index. 
```

**Review by MinerYang — APPROVED** [review]
lgtm

**Comment by MinerYang** [comment]
> when I **sign an artifact inside a manifest list**, then copy the index artifact, **quota usage is incorrect**.
> 
> Other cases below are working fine.
> 
> ```
> copy simple standalone image
> copy standalone image with a cosign accessory 
> copy standalone image with multi cosign accessory 
> copy simple manifest index artifact
> copy manifest index artifact with a cosign accessory on the index. 
> ```

resolved

**Pull request merged**
