### PR TITLE
Re-implemented LDAP nested group searching

### PR DESCRIPTION
**Pull request by Typositoire**
This is a take 2.

Re-implemented the feature, but behind an `experimental` toggle that is off by default.

I've tested this for basic functionality and also simplified the code.

Last thing to do is add test cases but I'm getting `POSTGRES` errors .. What's the setup for that? It's not in the `contributing` documentation. I'll go back to previous ticket and try to account for already known issues.

This is kind of a deal breaker for us, so I'd really appreciate your help to make this works this time!

harbor-toggle

### CODE REVIEW

**Comment by Typositoire** [comment]
What would be the best time to talk and get me up with the testing setup? My new test fails which I expected cuz it's wrong lol But I'd like to be able to test them locally before going through Travis.

**Comment by reasonerjt** [comment]
I don't think we can merge it in 1.10 as we are so close to cutting an RC.

**Comment by xaleeks** [comment]
yep this is out of scope for 1.10 but we can potentially merge for the next release. @Typositoire

**Comment by Typositoire** [comment]
Still have no idea how to run Unit Tests... This really doesn't help for contributions.

**Comment by Typositoire** [comment]
We dropped Harbor here. So let's forget about this.

**Pull request closed without merging**
