### PR TITLE
fix invalid access action

### PR DESCRIPTION
**Pull request by orblazer**
Hello,
This PR fix invalid access action for get repository. This is originally from #16381.

Route impacted :
- when we get repository via [GET]`/projects/{project_name}/repositories/{repository_name}` its ask `list` instead of `read`

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [ ] Made sure tests are passing and test coverage is added if needed.
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

Thanks.

### CODE REVIEW

**Review by wy65701436 — APPROVED** [review]
lgtm

**Review by MinerYang — APPROVED** [review]
lgtm

**Comment by wy65701436** [comment]
@YangJiao0817 can you help to test if it impacts the robot account?

**Comment by YangJiao0817** [comment]
Verification passed.

**Comment by OrlinVasilev** [comment]
@orblazer - congrats on merging your first PR :) welcome to the club! :)

**Pull request merged**
