### PR TITLE
chore: bump registry release to 2.8.2

### PR DESCRIPTION
**Pull request by DavidSpek**
# Comprehensive Summary of your change

This PR updates the version of the registry to 2.8.2 that was recently released. It also removes the patch from https://github.com/distribution/distribution/pull/2815 since that was backported into release 2.8.2 through PR https://github.com/distribution/distribution/pull/3893. For a full overview of the release notes please take a look at https://github.com/distribution/distribution/releases/tag/v2.8.2.

# Issue being fixed
Fixes #(issue)

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1204651419195132

### CODE REVIEW

**Review by wy65701436 — APPROVED** [review]
lgtm

**Review by MinerYang — APPROVED** [review]
lgtm

**Comment by wy65701436** [comment]
@DavidSpek thanks for the contribution, please sync with latest change.

**Comment by DavidSpek** [comment]
@wy65701436 I’ve updated the branch.

**Review by Vad1mo — APPROVED** [review]

**Comment by DavidSpek** [comment]
@Vad1mo I’ve resolved the conflict.

**Comment by DavidSpek** [comment]
@wy65701436 @Vad1mo @MinerYang Friendly ping to get this tested and merged so it doesn't get forgotten about and need constant rebasing.

**Comment by OrlinVasilev** [comment]
@DavidSpek happy to see your first PR merged :)) congrats!

**Pull request merged**
