### PR TITLE
Unify the method/style to handle error in handler/middleware

### PR DESCRIPTION
**Pull request by ywk253100**
This commit provides a "SendError" method to unify the way to handle error in handlers/middlewares

Signed-off-by: Wenkai Yin <yinw@vmware.com>

### CODE REVIEW

**Comment by ywk253100** [comment]
Fixes https://github.com/goharbor/harbor/issues/10553

**Comment by heww** [comment]
This make the management APIs return the same error format with OCI spec.  @steven-zou 

And if this PR merged, swagger.yaml and ServeError in handler for v2.0 also need to update to match the error format.

**Comment by ywk253100** [comment]
Fixes https://github.com/goharbor/harbor/issues/10573

**Comment by ywk253100** [comment]
@heww Let's use the issue https://github.com/goharbor/harbor/issues/10546 to discuss the error format. It's easy to change between these two formats as there is only one place to update.

**Pull request merged**
