### PR TITLE
Fixes bizarre translation for CLI in pt-br.

### PR DESCRIPTION
**Pull request by grstein**
Signed-off-by: Gustavo Raphael Stein <grstein.ramone@gmail.com>

### CODE REVIEW

**Comment by AllForNothing** [comment]
@grstein Thanks for your PR
Can you invite one or more Portuguese speakers to review this,  as there is no Portuguese speaker on the Harbor team，
and then I can help to merge this PR

**Comment by grstein** [comment]
Sure, I'll ask some friends to do this review, thanks!

**Comment by juliohm1978** [comment]
Hi, I'm from Brazil as well.

The word _clitóris_ has nothing to do with context here. It literally refers to female genitalia and it seems like a Google Translator misfortune. The translation provided by @grstein is perfect.

**Review by AllForNothing — APPROVED** [review]
LGTM

**Review by danfengliu — APPROVED** [review]

**Pull request merged**
