### PR TITLE
fix dragonfly response when p2p preheat

### PR DESCRIPTION
**Pull request by mr-002**
**reason**
when I use p2p preheat by dragonfly (1.0.6) while checking process from dragonfly it resp that :
``````
{
    "ID":"b0227c0ba41938d25abad4df1e9b57a1e7d113086cc77d047f7acb6e73916fa9",
    "finishTime":"2021-10-25T07:53:44.162Z",
    "startTime":"2021-10-25T07:53:44.143Z",
    "status":"FAILED",
    "errorMsg":"{\"Code\":208,\"Msg\":\"preheat task already exists, id:02b0d5c6e1cd99b5fa9f730b0a8d96696ca965898233ad68b4f26267b8016ce1\"}"
}
``````
but here is status defined on git:
``````
const (
	// PreheatingImageTypeImage defines the 'image' type of preheating images
	PreheatingImageTypeImage = "image"
	// PreheatingStatusPending means the preheating is waiting for starting
	PreheatingStatusPending = "PENDING"
	// PreheatingStatusRunning means the preheating is ongoing
	PreheatingStatusRunning = "RUNNING"
	// PreheatingStatusSuccess means the preheating is success
	PreheatingStatusSuccess = "SUCCESS"
	// PreheatingStatusFail means the preheating is failed
	PreheatingStatusFail = "FAIL"
)
``````
so I fix that and add retry when dragonfly job already exists.

**what I changed**

- fix check dragionfly response status;
- add handle when dragonfly preheat job existed;

Signed-off-by: anyiwei <anyiwei@didichuxing.com>

### CODE REVIEW

**Review by bitsf — APPROVED** [review]
LGTM

**Comment by bitsf** [comment]
please try rebase code to make the CI run

**Review by steven-zou — APPROVED** [review]
approved

**Comment by wy65701436** [comment]
@mr-002 please help to fix the go check issue, then let me merge it.

**Comment by Vad1mo** [comment]
@mr-002 ping, we don't want your effort to get lost. Please help us address the requested change by @wy65701436

**Comment by mr-002** [comment]
I'm so sorry for these days delay.

**Comment by wy65701436** [comment]
@mr-002 could you please resove the golint error? I'd like to merge this PR.

**Comment by mr-002** [comment]
@wy65701436 Hi, I have resoved golint errors，All CI jobs are passed。😁

**Comment by mr-002** [comment]
Thanks for all patience about my first commit 🤗

**Review by mr-002 — COMMENTED** [review]
add test case

**Comment by wy65701436** [comment]
@mr-002 thanks, and could you please help to squash the commits?

**Pull request merged**
