### PR TITLE
Fix ecr authorization token issue

### PR DESCRIPTION
**Pull request by vincentni**
Signed-off-by: Vincent Ni <kangqini@amazon.com>

Thank you for contributing to Harbor!

# Comprehensive Summary of your change

# Issue being fixed
Fixes https://github.com/goharbor/harbor/issues/17642
GetAuthorizationTokenInput returns error in case of empty registry ids.

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Comment by vincentni** [comment]
@chlins please take a look. Thanks!

**Comment by vincentni** [comment]
@stonezdj @chlins shall we merge it if it looks good to you? thanks!

**Review by stonezdj — APPROVED** [review]

**Review by chlins — APPROVED** [review]
lgtm

**Comment by YangJiao0817** [comment]
图片

I can add AWS ECR Endpoint using this fix.

**Pull request merged**
