### PR TITLE
fixed typo in legacy_swagger.yaml file

### PR DESCRIPTION
**Pull request by tibeer**
Signed-off-by: Tim Beermann <beermann@osism.tech>

Thank you for contributing to Harbor!

# Comprehensive Summary of your change

# Issue being fixed
Fixes #(issue)

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [ ] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Comment by tibeer** [comment]
Label can only be set by maintainers - ignoring.

**Review by Vad1mo — APPROVED** [review]
Thank you for you contribution @tibeer

**Comment by lindhe** [comment]
Fix typo in title: legaxy_swagger --> legacy_swagger ;)

**Comment by tibeer** [comment]
> Fix typo in title: legaxy_swagger --> legacy_swagger ;)

Done.

**Review by chlins — APPROVED** [review]
lgtm

**Comment by OrlinVasilev** [comment]
@tibeer that was your first PR right ?

**Pull request merged**
