### PR TITLE
Feature: GDPR compliant audit logs

### PR DESCRIPTION
**Pull request by tpoxa**
# Summary

In order to keep the audit logs compliant with GDPR requirements, this PR makes it possible to "mask" the username of  users that were deleted from the system.

The username in the audit_log table is changed to its CRC32 value and so becomes GDPR compliant.

GDPR compliant audit logs are enabled with the environmental variable `AUDIT_LOGS_GDPR_COMPLIANT=true`.

Once enabled, only the audit logs of deleted users will be masked and made GDPR compliant and not current active users.

This is PR is like the existing one for GDPR compliant user deletion. See:
- https://github.com/goharbor/harbor/pull/16859

# Issue being fixed
Fixes https://github.com/goharbor/harbor/issues/13523

Please indicate you've done the following:

- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Comment by stonezdj** [comment]
Username is personal data but it is not sensitive personal data in GDPR

**Comment by Vad1mo** [comment]
> Username is personal data but it is not sensitive personal data in GDPR

If the username contains the first or last name of a user: (such as email address), then this information is considered being GFPR relevant. Emails as usernames us the default option if "Automatic onboarding" is enabled. 

Harbor actually favors using emails as usernames

**Review by Vad1mo — APPROVED** [review]

**Comment by MinerYang** [comment]
We are aware of that we have to mask the username in logs if they are no longer needed compliant with GDPR requirements.
Once concern for this is once this feature enabled, it will slow down the audit log process relatively.
We would evaluate this feature to be added whether to the harbor.yml or the ENV, we prefer the latter one though, because it will satisfy the users that need GDPR compliant and  won't make the harbor.yml too complicated or heavy to others.

**Review by stonezdj — APPROVED** [review]

**Comment by wy65701436** [comment]
@tpoxa per this [comment](https://github.com/goharbor/harbor/pull/17396#issuecomment-1305315777), we kindly request the addition of a new ENV in the core to enable the desired feature. Could you please incorporate this modification and ensure that the UT pass?

**Review by Vad1mo — APPROVED** [review]

**Pull request merged**
