### PR TITLE
Fix panic if ExtEndpoint is empty

### PR DESCRIPTION
**Pull request by tossmilestone**
Fix panic if `ExternalEndpoint` is empty, see the panic snapshot:

image

Signed-off-by: Xiaoxi He <xxhe@alauda.io>

### CODE REVIEW

**Comment by tossmilestone** [comment]
cc @wy65701436

**Comment by wy65701436** [comment]
thanks @tossmilestone, but we are working on the code adminserver, it will be merged into core.

You can refer to the PR https://github.com/goharbor/harbor/pull/6231.

**Comment by tossmilestone** [comment]
@wy65701436 OK, I will wait the PR to be merged.

**Comment by wy65701436** [comment]
@tossmilestone thanks for your PR, but we are working on adminserver refectory, and plan to merge it into core service. So, this PR won't be effective after that.

**Comment by tossmilestone** [comment]
@wy65701436 Let me know if you have done with the adminserver refactory. Thanks!

**Pull request closed without merging**
