### PR TITLE
To allow goharbor UI to show the images pushed by other docker clients such as Skopeo

### PR DESCRIPTION
**Pull request by saikirandusari**
To resolve https://github.com/goharbor/harbor/issues/5729

To allow go harbor to show the images pushed by other docker clients such as Skopeo

### CODE REVIEW

**Comment by clouderati** [comment]
I'm not opposed to the `UserAgent` change, though I do have a few thoughts:

* Spokeo should probably use a slightly more descriptive `UserAgent` string so that future Go-based clients can differentiate. Obviously that's out of our control. 😄 
* We've not tested this _at all_, so we need to update our documentation to make that clear.
* @saikirandusari, just want to confirm: have you actually tested Spokeo + Harbor functionality after making this change?

@reasonerjt any other concerns, technical or otherwise, that we should discuss?

**Comment by clouderati** [comment]
@goharbor/harbor – ptal and provide feedback. Thanks!

**Comment by reasonerjt** [comment]
IMO this change should not be merged to `master` as it will make notification handler unable to differentiate a `pull` from a rest call by regular Go HTTP Client.
As I suggested in another issue or thread, a better approach should be update the notification handler it can identify a `pull` or `push` command by checking a custom HTTP header of the request, rather than adding more and more user agents to the white list.

**Comment by clouderati** [comment]
Thanks @reasonerjt. @saikirandusari any questions about @reasonerjt's approach?

**Comment by clouderati** [comment]
Closing this for now. I still think it's a valuable feature to have and contributions to make this happen as per @reasonerjt's welcomed.

**Pull request closed without merging**
