### PR TITLE
Fix tencentcr adapter.

### PR DESCRIPTION
**Pull request by kofj**
1. Limit API qps for the adapter.
2. Allow set qps via env.
3. Fix Tencnet SDK pagenation.
4. Fix resource filter.

Signed-off-by: fanjiankong <fanjiankong@tencent.com>

### CODE REVIEW

**Comment by ywk253100** [comment]
@kofj  Is this PR a dup of #14828?

**Comment by kofj** [comment]
> @kofj Is this PR a dup of #14828?

Not. #14828 for release v2.2, this for master.

**Comment by bitsf** [comment]
@kofj need rebase code

**Comment by ywk253100** [comment]
@kofj Please resolve the conflict

**Comment by kofj** [comment]
> @kofj Please resolve the conflict

Done.

**Review by ywk253100 — APPROVED** [review]

**Review by bitsf — APPROVED** [review]

**Pull request merged**
