### PR TITLE
Fixed search images in registry gitlab

### PR DESCRIPTION
**Pull request by lxShaDoWxl**
Correct work regular expression search.
Fixed match tag name
#9295

### CODE REVIEW

**Comment by d2dyno** [comment]
@ywk253100 Can you check this, to resolve the outstanding issue many are having?

**Comment by d2dyno** [comment]
Bump @bitsf

**Comment by d2dyno** [comment]
I'm not sure who we need to get this approved, but this has been a but for several months and made our harbor instance useless. Because bugging people is probably the only way to get this seen:
@ywk253100 @bitsf @wy65701436 @xaleeks @stuclem @heww

**Comment by bitsf** [comment]
hi, I remember this gitlab replication adapter is added in release 1.10.0, but the issue is talking about 1.8 and 1.9, just want to confirm if this is the fix for that first

**Comment by bitsf** [comment]
And I don't have any gitlab repo now, can you share some test cases and results that make sure this is worked now.

**Comment by lxShaDoWxl** [comment]
@bitsf I'm sorry, I didn't add tests right away

**Comment by d2dyno** [comment]
@ywk253100 @bitsf @wy65701436 @xaleeks @stuclem @heww please re-check this

**Comment by bitsf** [comment]
@d2dyno rebase the master should fix error in CI.
at least paste some manually test result result that can prove this fix work

**Comment by bitsf** [comment]
hi @d2dyno , try rebase this pr

**Comment by bitsf** [comment]
@lxShaDoWxl try rebase this to fix ci

**Comment by lxShaDoWxl** [comment]
I'll make a correction in a few days

**Pull request merged**
