### PR TITLE
Update to latest version of angular

### PR DESCRIPTION
**Pull request by mrbusche**
Thank you for contributing to Harbor!

# Comprehensive Summary of your change
Updated to Angular 14 using the Angular Update Guide

# Issue being fixed
- Fixes: Angular is a major version behind
- Labels: I'm not able to add labels but `release-note/enhancement` is appropriate
- Unit tests pass locally
- One docs page (that I found) affected has been updated

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Comment by mrbusche** [comment]
@goharbor/maintainers can I get someone to approve this PR for status checks, please?

**Comment by mrbusche** [comment]
Looks like we need to wait for `@clr/angular` to release version 14 before we can use angular:14

```shell
13:49:48 + npm install -q --no-progress
13:49:50 npm ERR! code ERESOLVE
13:49:50 npm ERR! ERESOLVE could not resolve
13:49:50 npm ERR!
13:49:50 npm ERR! While resolving: @clr/angular@13.3.0
13:49:50 npm ERR! Found: @angular/common@14.1.0
13:49:50 npm ERR! node_modules/@angular/common
13:49:50 npm ERR! @angular/common@"^14.1.0" from the root project
13:49:50 npm ERR! peer @angular/common@"14.1.0" from @angular/forms@14.1.0
13:49:50 npm ERR! node_modules/@angular/forms
13:49:50 npm ERR! @angular/forms@"^14.1.0" from the root project
13:49:50 npm ERR! 7 more (@angular/platform-browser, ...)
13:49:50 npm ERR!
13:49:50 npm ERR! Could not resolve dependency:
13:49:50 npm ERR! peer @angular/common@"^13.0.0" from @clr/angular@13.3.0
13:49:50 npm ERR! node_modules/@clr/angular
13:49:50 npm ERR! @clr/angular@"13.3.0" from the root project
13:49:50 npm ERR! peer @clr/angular@"13.3.0" from @clr/ui@13.3.0
13:49:50 npm ERR! node_modules/@clr/ui
13:49:50 npm ERR! @clr/ui@"13.3.0" from the root project
13:49:50 npm ERR!
13:49:50 npm ERR! Conflicting peer dependency: @angular/common@13.3.11
13:49:50 npm ERR! node_modules/@angular/common
13:49:50 npm ERR! peer @angular/common@"^13.0.0" from @clr/angular@13.3.0
13:49:50 npm ERR! node_modules/@clr/angular
13:49:50 npm ERR! @clr/angular@"13.3.0" from the root project
13:49:50 npm ERR! peer @clr/angular@"13.3.0" from @clr/ui@13.3.0
13:49:50 npm ERR! node_modules/@clr/ui
13:49:50 npm ERR! @clr/ui@"13.3.0" from the root project

**Comment by AllForNothing** [comment]
@mrbusche That's true.
I have consulted the Clarity team about the release plan for 14, let's wait for the updates

**Comment by AllForNothing** [comment]
@mrbusche Refer to this,https://github.com/vmware-clarity/ng-clarity/discussions/274
Would you like to try  Clarity version 13.6.x

**Comment by mrbusche** [comment]
> @mrbusche Refer to this,[vmware-clarity/ng-clarity#274](https://github.com/vmware-clarity/ng-clarity/discussions/274) Would you like to try Clarity version 13.6.x

I updated the Clarity version and also had to update ngx-markdown, but everything should be good. 

I'd be happy to do another run through of updates once this one is merged.

**Comment by AllForNothing** [comment]
@mrbusche I will run the e2e cases first, then merge this PR if no breaking change

**Review by AllForNothing — APPROVED** [review]
LGTM

**Comment by AllForNothing** [comment]
@mrbusche Did you notice this error? any ideas?
image

**Review by YangJiao0817 — APPROVED** [review]

**Pull request merged**
