### PR TITLE
fix: align some configuration api fields validation with frontend

### PR DESCRIPTION
**Pull request by chlins**
This is the backend change to align with fronend commit: https://github.com/goharbor/harbor/commit/5f1dff32c27555c620e6e5ec25ef49e2ae0bd9d7

Signed-off-by: chlins <chenyuzh@vmware.com>

Thank you for contributing to Harbor!

# Comprehensive Summary of your change

# Issue being fixed
Fixes #(issue)

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Review by AllForNothing — APPROVED** [review]
LGTM

**Review by Vad1mo — APPROVED** [review]
Does it have an impact on the REST API?

**Review by wy65701436 — APPROVED** [review]
lgtm

**Comment by chlins** [comment]
> Does it have an impact on the REST API?

@Vad1mo Yes, the API will return BAD_REQUEST if the value over the limit(9999999999).

**Pull request merged**
