### PR TITLE
Update clair version to fix NVD deprecated links

### PR DESCRIPTION
**Pull request by angelbarrera92**
Hi team!

First of all thanks for the amazing work you are doing with this project!

We found some error logs in our Harbor installation (Clair module):

```
clair-8667559468-hbhfl clair {"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:161","Time":"2020-10-02 13:40:10.806339","data feed name":"2018","error":"https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2018.meta failed status code: 404"}
```

You can check that the URL `https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2018.meta` returns 404 while
`https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2018.meta` returns 200.

```bash
$ curl -I https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2018.meta
HTTP/1.1 404 Not Found
content-length: 0
server: Microsoft-IIS/8.5
x-frame-options: SAMEORIGIN
content-security-policy: frame-ancestors 'self'
date: Fri, 02 Oct 2020 14:03:12 GMT
strict-transport-security: max-age=31536000
```

```bash
$ curl -I https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2018.meta
HTTP/1.1 200 OK
content-length: 165
content-type: text/plain
last-modified: Fri, 02 Oct 2020 08:15:16 GMT
accept-ranges: bytes
etag: "02bc289498d61:0"
server: Microsoft-IIS/8.5
x-frame-options: SAMEORIGIN
content-security-policy: frame-ancestors 'self'
date: Fri, 02 Oct 2020 14:02:39 GMT
strict-transport-security: max-age=31536000
```

Digging a little bit into the error, we found that NVD deprecated version 1.0, they move to 1.1.
The upstream Clair project already fixed the issue in version v2.1.5: https://github.com/quay/clair/pull/1056

So this PR aims to fix the issue in this project.

Thanks!

### CODE REVIEW

**Comment by angelbarrera92** [comment]
FIX: #13212

**Comment by angelbarrera92** [comment]
@danielpacak @steven-zou

**Comment by steven-zou** [comment]
@wy65701436 

Please check if the change is ok for our building.

**Comment by wy65701436** [comment]
hi @angelbarrera92 could you please help to rebase with master to resolve the UT failure? Then, I'll merge it.

**Comment by angelbarrera92** [comment]
> hi @angelbarrera92 could you please help to rebase with master to resolve the UT failure? Then, I'll merge it.

Rebase done @wy65701436! 
Thanks for taking care of this!

**Review by wy65701436 — APPROVED** [review]
lgtm

**Review by danielpacak — APPROVED** [review]

**Comment by wy65701436** [comment]
@angelbarrera92 can you also cherry pick this PR to release-2.0 & release-2.0? thanks.

**Comment by angelbarrera92** [comment]
> @angelbarrera92 can you also cherry pick this PR to release-2.0 & release-2.0? thanks.

Done!
I did it for 2.0 and 2.1 (i think you had a typo in your message, dup 2.0 version)

https://github.com/goharbor/harbor/pull/13273
https://github.com/goharbor/harbor/pull/13274

Thanks!

**Comment by biggnou** [comment]
> > @angelbarrera92 can you also cherry pick this PR to release-2.0 & release-2.0? thanks.
> 
> Done!
> I did it for 2.0 and 2.1 (i think you had a typo in your message, dup 2.0 version)
> 
> #13273
> #13274
> 
> Thanks!

Hi folks,

Is it possible to get this backported to the 1.10.x versions as well? 

We have a constraint on our side, we can't use Harbor 2.x.

Thanks!

Alex.

**Pull request merged**
