### PR TITLE
Added Gitlab Registry Support

### PR DESCRIPTION
**Pull request by lxShaDoWxl**
This request added gitlab registry support
Checked at https://gitlab.com
Need use login and personal access tokens, no use password, in added registry
#694

### CODE REVIEW

**Comment by reasonerjt** [comment]
Could you squash the commit and properly update the title and description of the PR, refine the commit message to clarify?

**Comment by reasonerjt** [comment]
even ` Added Gitlab Registry Support`

It seems you are only adding an adapter for replication and it doesn't cover UI.

Please kindly add more commit message so other user/developer knows exactly what you code change is about.

A good example:
https://github.com/goharbor/harbor/commit/bf9ac08c89514d97559be9dc46c887f9b5e5d074

**Comment by xaleeks** [comment]
@bitsf please review gitlab as a replication endpoint

**Comment by ywk253100** [comment]
@lxShaDoWxl Sorry for the late reply. Could you fix the conflicting files?

**Pull request merged**
