### PR TITLE
Added nginx rewrite component

### PR DESCRIPTION
**Pull request by jkroepke**
As discussed here https://github.com/vmware/harbor/issues/5189

I tested:

* docker login
* docker pull
* docker push
* docker logout

I looked at the generated configurations from 

* helm template .
* helm template --set nginx.enabled=true .

both looks okay. I also do some integration test on our test environment. I found some issues about proxy buffering but I found a resolution for the case.

### CODE REVIEW

**Comment by ywk253100** [comment]
@jkroepke As we are moving the Harbor chart to the new repository https://github.com/goharbor/harbor-helm, could you please re-submit your PR to the new one? Thanks a lot.

**Comment by jkroepke** [comment]
It is still required?

https://github.com/goharbor/harbor/commit/9f34bd5b17609bdc6a3ba791b4b232def4f87b89#diff-0eb8e573ab3d200ab22baf405ac0929e

**Comment by ywk253100** [comment]
Yes, we want to support `NodePort`, so the proxy is necessary.

**Comment by jkroepke** [comment]
Sorry. can you please explain the relation between NodePort and this nginx proxy?

This nginx proxy was used to redirect from /v2/ to /registryproxy/v2/.

NodePort NAT to the container port is managed by kubernetes

**Comment by ywk253100** [comment]
OK, it's not needed, thanks. Closing this one.

**Pull request closed without merging**
