### PR TITLE
disable external redis using acl username auth

### PR DESCRIPTION
**Pull request by MinerYang**
Thank you for contributing to Harbor!

# Comprehensive Summary of your change
- introduced by: https://github.com/goharbor/harbor/pull/18364
- affect version: v2.8.0, v2.8.1, v2.8.2
- impact: distribution performance

Note: distribution configuration (until v2.8.2) only support auth by password
- https://pkg.go.dev/github.com/distribution/distribution/v3/configuration
- https://github.com/distribution/distribution/blob/7c354a4b40feeea21d7eeae4de91c8ff7951e672/registry/handlers/app.go#L530

# Issue being fixed
Fixes 

Please indicate you've done the following:
- [ ] Well Written Title and Summary of the PR
- [ ] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [ ] Accepted the DCO. Commits without the DCO will delay acceptance.
- [ ] Made sure tests are passing and test coverage is added if needed.
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Review by wy65701436 — APPROVED** [review]
LGTM

**Review by chlins — APPROVED** [review]
lgtm

**Review by wy65701436 — CHANGES_REQUESTED** [review]
don't merge

**Comment by MinerYang** [comment]
we don't need this, since could bypass this issue by follow this [FAQ](https://github.com/goharbor/harbor/wiki/Harbor-FAQs#external-redis-username-password-usage)

**Pull request closed without merging**
