### PR TITLE
Fix Permission Denied

### PR DESCRIPTION
**Pull request by paroque28**
When executing the command:
```bash
docker run vmware/harbor-db:dev
```
With `chmod +x` I get this error:
(Using set -x to debug the script)
```bash
+ exec sudo -u mysql -E /usr/local/bin/docker-entrypoint.sh mysqld
/bin/bash: /usr/local/bin/docker-entrypoint.sh: Permission denied
```
This was fixed giving also permission to read `chmod 555`

### CODE REVIEW

**Comment by paroque28** [comment]
Also I want to contribute harbor adding groups support to LDAP and link it with the namespaces.
Do you have a current effort on this topic?

**Comment by paroque28** [comment]
I also noticed the harbor-ui container didn't have access to templates such as index.html
I suspect this is because I am running as root and the contents are copied on docker build with owner root
Proof:
```bash
~# docker run -it --entrypoint "/bin/stat" vmware/harbor-ui:dev /harbor/views/index.html
  File: '/harbor/views/index.html'
  Size: 810             Blocks: 8          IO Block: 4096   regular file
Device: fc03h/64515d    Inode: 140010      Links: 1
Access: (0600/-rw-------)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2018-01-08 15:51:37.000000000 +0000
Modify: 2018-01-08 15:51:37.000000000 +0000
Change: 2018-01-09 17:09:01.652858228 +0000
 Birth: -

```

**Comment by clouderati** [comment]
Hi @paroque28 – can you try with latest Dockerfiles? Cleaning out old issues and PRs and want to determine if this is still needed.

Thanks!

**Comment by paroque28** [comment]
@clouderati  Thank you  , no need now

**Pull request closed without merging**
