### PR TITLE
enable gzip in the nginx config

### PR DESCRIPTION
**Pull request by yankay**
Enable gzip in the nginx config for slow networks.

Thank you for contributing to Harbor!

# Comprehensive Summary of your change

# Issue being fixed
Fixes #(issue)

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [ ] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x]  Accepted the DCO. Commits without the DCO will delay acceptance.
- [x]  Made sure tests are passing and test coverage is added if needed.
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Comment by OrlinVasilev** [comment]
@yankay thank you for your contribution!
Does that fix any specific issue or you have faced it can you please elaborate a bit more!
I like the idea but we need to be a bit more specific when we introduce new stuff !

Thank you!

**Comment by yankay** [comment]
> @yankay thank you for your contribution! Does that fix any specific issue or you have faced it can you please elaborate a bit more! I like the idea but we need to be a bit more specific when we introduce new stuff !
> 
> Thank you!

Thanks @OrlinVasilev 

When we use the harbor to serve the helm charts, the `helm repo update` needs to download the index.yaml. 

In the scenario, the index.yaml is 2MB(compressed size 180KB), so when the Nginx use gzip compress, the network IO would be reduced 10x,  it's very effective in the Slow Network.

image

**Comment by panpan0000** [comment]
it saves a lot of public cloud bandwidth cost :-)

**Review by stonezdj — CHANGES_REQUESTED** [review]
Could please add an option in the harbor.yaml.tmpl so that we could enable or disable it?

**Comment by wy65701436** [comment]
Regarding Docker images, this option may only be beneficial for the manifest rather than the blobs, which typically make up the majority of an image's size. I would prefer to add an option that allows the user to decide whether to enable it.

Harbor provides a default configuration for Nginx, but users can enable or disable any configurations based on their specific requirements. However, this default configuration is only applicable for online/offline installations. What if a user installs Harbor on Kubernetes and prefers to use Contour as the proxy?

**Comment by stonezdj** [comment]
Because most of the content type in the Harbor server might be application/octet-stream(blob) or application/vnd.docker.distribution.manifest.v2+json (manifest), it is not in the list of the gzip_types and won't be compressed.

As for the helm chart's index.yaml, it is the output of chartmuseum server, it is already removed from Harbor 2.8.0

So the performance improvement is limited to the REST API and javascript level.

**Comment by wy65701436** [comment]
hi @yankay would you mind to reply the above two comments? Or we can go ahead to stale this pull request.

**Comment by yankay** [comment]
> hi @yankay would you mind to reply the above two comments? Or we can go ahead to stale this pull request.

Thanks @wy65701436 

The PR uses the `gzip_types ` to filter the mime-type of the content. So the blob would not be compressed. :-)

But if the chartmuseum be removed , the compress is not very useful.

So the PR may should be closed :-)

**Comment by wy65701436** [comment]
@yankay thanks for your input.

**Pull request closed without merging**
