### PR TITLE
upgrade aws-sdk-go to support OIDC feature

### PR DESCRIPTION
**Pull request by shivpathak**
**About this PR**

I wanted to use S3 backend for harbor registry storage.

In order to support k8s ServiceAccount feature with AWS IAM roles upgrading the aws-sdk-module.

### CODE REVIEW

**Comment by redradrat** [comment]
This PR will add support for using IAM roles linked to k8s serviceAccounts via OIDC integration. 
https://docs.aws.amazon.com/eks/latest/userguide/enable-iam-roles-for-service-accounts.html

**Comment by reasonerjt** [comment]
@shivpathak you need to vendor the code.  Harbor builds with `mod=vendor`

**Comment by reasonerjt** [comment]
I believe this is a dup of https://github.com/goharbor/harbor/pull/12281 @shivpathak

**Comment by shivpathak** [comment]
duplicates of this https://github.com/goharbor/harbor/pull/12281 so closing.

**Pull request closed without merging**
