### PR TITLE
Correct typo

### PR DESCRIPTION
**Pull request by ltupin**

### CODE REVIEW

**Comment by ltupin** [comment]
As now there is the helm repo, why dont moving https://github.com/goharbor/harbor/tree/master/make/kubernetes folder ?

**Comment by clouderati** [comment]
@ltupin can you please [sign-off](https://github.com/goharbor/harbor/pull/6282/checks?check_run_id=31719136) on your commit so that I can merge? Thanks!

**Comment by ltupin** [comment]
I tried @clouderati but unable to do it. I push a new one here https://github.com/goharbor/harbor/pull/6315 hope that resolve it ?

**Comment by clouderati** [comment]
Closing in lieu of https://github.com/goharbor/harbor/pull/6315.

**Pull request closed without merging**
