### PR TITLE
fix registryctl being blocked on exit

### PR DESCRIPTION
**Pull request by Iceber**
Thank you for contributing to Harbor!

# Comprehensive Summary of your change
`context.Background()` will never be Done, we need to use WithCancel to create a cancelable context

# Issue being fixed
Fixes #(issue)

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Comment by Iceber** [comment]
@wy65701436 @MinerYang PTAL

**Review by Vad1mo — APPROVED** [review]

**Comment by chlins** [comment]
@Iceber Hi, please rebase the main and resolve the conflicts.

**Comment by Iceber** [comment]
This looks to have been fixed

**Comment by Vad1mo** [comment]
@Iceber I don't' see it beeing fixed. In main at least, it isn't there. the problem persists IMO, so reopening.

**Pull request closed without merging**
