### PR TITLE
python sdk bug

### PR DESCRIPTION
**Pull request by sunlianqiang**

### CODE REVIEW

**Comment by sunlianqiang** [comment]
@AllForNothing @jwangyangls @bitsf  anyone want see this pr? it's been almost one month.

**Comment by steven-zou** [comment]
@sunlianqiang 

We can help to merge this PR. But one thing you may need to know is the registryAPI under contrib has been deprecated alreay.

**Comment by sunlianqiang** [comment]
> @sunlianqiang
> 
> We can help to merge this PR. But one thing you may need to know is the registryAPI under contrib has been deprecated alreay.

could you explain why deprecated the registryAPI? it will work if using the right http request.

**Comment by steven-zou** [comment]
> > @sunlianqiang
> > We can help to merge this PR. But one thing you may need to know is the registryAPI under contrib has been deprecated alreay.
> 
> could you explain why deprecated the registryAPI? it will work if using the right http request.

No maintainer resource.

**Comment by sunlianqiang** [comment]
> > > @sunlianqiang
> > > We can help to merge this PR. But one thing you may need to know is the registryAPI under contrib has been deprecated alreay.
> > 
> > 
> > could you explain why deprecated the registryAPI? it will work if using the right http request.
> 
> No maintainer resource.

all right, I just use this sdk for once, you can handle it as you like.

**Comment by bitsf** [comment]
I think it's welcome if anyone wish to continue contribute for this code.
And this tool maybe helpful when we test OCI feature in future.

**Comment by steven-zou** [comment]
@sunlianqiang 

As I mentioned before, we can merge your PR but anyway be aware that the py client has been deprecated as no maintainer is maintaining it anymore.

**Pull request closed without merging**
