### PR TITLE
various spelling & grammar issues and other misc cleanup

### PR DESCRIPTION
**Pull request by burdzwastaken**

### CODE REVIEW

**Comment by reasonerjt** [comment]
@burdzwastaken thanks a lot for fixing typos in the comments and messages.

However, some changes, such as `Parms -> Params` seems not very necessary to me, and some of the changes in attribute/variable names break the `go vet`

**Comment by burdzwastaken** [comment]
@reasonerjt sorry that is due to me messing a reference of `Parm`. I added that in but am happy to change it back if you would like as I was just trying to be consistent.

**Comment by reasonerjt** [comment]
@burdzwastaken Sorry for the late response, there has been quite a few changes and conflicts, will you resolve the conflicts?

**Comment by burdzwastaken** [comment]
@reasonerjt no problem. everything should be resolved now.

**Comment by reasonerjt** [comment]
@burdzwastaken could you rebase to resolve the conflicts?

**Comment by burdzwastaken** [comment]
@reasonerjt rebased again

**Pull request closed without merging**
