### PR TITLE
delete membership=0 in getProjectsByName

### LINKED ISSUE #20056: Pull Replication from GitLab does not work if not member of source group
Hello,

I'm trying to pull replicate images from a public gitlab instance to a local harbor instance, but it does not find the images (hence the job ends with 0 Tasks).

I believe I tracked this down to:
The filter `membership=true` or `membership=1` causes to return only projects of which one is a member. But in case of public repos/groups this is usually not the case.

My proposal is to remove the `membership=true` flag.

https://github.com/goharbor/harbor/blob/29cdc398e048b739c19a23fa0ffb5073df256009/src/pkg/reg/adapter/gitlab/client.go#L77
https://github.com/goharbor/harbor/blob/29cdc398e048b739c19a23fa0ffb5073df256009/src/pkg/reg/adapter/gitlab/client.go#L86

### PR DESCRIPTION
**Pull request by prima101112**
delete membership=0 in getProjectsByName but lets getProjects still using membership=1 for reserve if getProjectsByName not found any

# Comprehensive Summary of your change

# Issue being fixed
Fixes #20056

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [ ] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Review by stonezdj — APPROVED** [review]
LGTM

**Comment by stonezdj** [comment]
@prima101112 could you please give us the document link for it?

**Comment by chlins** [comment]
@lxShaDoWxl Kindly review this, thank you!

**Comment by prima101112** [comment]
> @prima101112 could you please give us the document link for it?

whats document, is this whay you mean https://docs.gitlab.com/ee/api/projects.html
from the issue just state that when using public gitlab **it should not require the member of the project**

please assist me if its missing something or need to be fixed

**Comment by lxShaDoWxl** [comment]
you can also remove the "membership" here, only the search becomes more extensive. The disadvantage is only in performance

**Comment by prima101112** [comment]
> you can also remove the "membership" here, only the search becomes more extensive. The disadvantage is only in performance

I think yes we can remove the "membership" but adjusting the fallback mechanism is risky. Currently, if the repository is not found, the search extends to the entire GitLab instance. However, it would be more efficient to limit the search to projects where the user is a member. This way, the search would only include projects that the user has access to. so i will leave it like that. please advice

**Comment by prima101112** [comment]
@lxShaDoWxl could we get approval for this

**Review by lxShaDoWxl — APPROVED** [review]

**Review by Vad1mo — APPROVED** [review]

**Pull request merged**
