### PR TITLE
introduce configurable concurrency in gc run

### PR DESCRIPTION
**Pull request by hemanth132**
Thank you for contributing to Harbor!

# Comprehensive Summary of your change
Introduced configurable concurrency within a gc run to speed up the GC

# Issue being fixed
[Fixes #(issue)](https://github.com/goharbor/harbor/issues/17836)

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/update"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [ ] Made sure tests are passing and test coverage is added if needed.
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Comment by hemanth132** [comment]
@wy65701436 @zyyw hey folks, waiting for your review. let me know if something is missing.

**Comment by Vad1mo** [comment]
@hemanth132 can you add some tests to your code?

**Comment by Vad1mo** [comment]
@hemanth132, can you join the [Harbor Slack channel](https://cloud-native.slack.com/archives/CC1E0J0MC/p1687528062607739?thread_ts=1686563290.705529&cid=CC1E0J0MC) to continue our discussion?

**Comment by wy65701436** [comment]
Hi @hemanth132, thank you for your contribution. Regarding the multiple deletion issue, it has already been addressed in https://github.com/goharbor/harbor/pull/18855.

For the multiple deletion feature, I suggest narrowing it down to the sweep phase since it won't take up too much time in the mark phase. However, it needs to handle the API and front-end IO as well.

And would you mind to close this pull request?

**Pull request closed without merging**
