### PR TITLE
Update installation_guide.md

### PR DESCRIPTION
**Pull request by aidanSoles**
Added a "P" that someone forgot in the protocol name! Oops! 🤫

Signed off by: @clouderati 🤘

### CODE REVIEW

**Comment by clouderati** [comment]
Hi @aidanSoles – thanks so much for the contribution. Can you please sign-off on your commit message so that I can merge?

Thanks!

**Comment by aidanSoles** [comment]
@clouderati : Thanks for approving this! 🙂

**Comment by aidanSoles** [comment]
@clouderati : Did I sign off right?!

**Comment by clouderati** [comment]
Hi @aidanSoles – sorry for the delay. Actually, your git commit message should reflect your email address.

**Comment by clouderati** [comment]
Hi @aidanSoles – let me know if you still need help signing off on the commit. Happy to discuss over Slack, too, if that's easier. :+1:

**Comment by clouderati** [comment]
Closing due to inactivity.

**Pull request closed without merging**
