### PR TITLE
Adding CREATE/DELETE Label for Robot Account

### LINKED ISSUE #15788: Robot Account "403 FORBIDDEN" on "Add" or "Removal" or artifact (image) label
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
I have a CD that on rollout labels the artifact in Harbor using an account / Robot account. When trying to add and remove the labels, both actions are being responded with a 403 "FORBIDDEN". 

My Robot Account has "Create Artifact Label" permissions. Should this scope not include the option to add/remove labels from an artifact? 

**Steps to reproduce the problem:**
Using a robot account, try to add/remove a label from an artifact using;

POST: /projects/{project_name}/repositories/{repository_name}/artifacts/{reference}/labels

OR 

DELETE: /projects/{project_name}/repositories/{repository_name}/artifacts/{reference}/labels/{label_id}

Both will fail with a 403: FORBIDDEN

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.3.3]

**Additional context:**
I don't think there's a need for this, but here's the Robot account; 

image

### PR DESCRIPTION
**Pull request by DandyDeveloper**
This is a basic implementation of adding CREATE/DELETE options for labels on both Artifacts AND Chartrepo charts. 

Tests will follow, when I understand how your Python tests work :)

- fixes #15788

### CODE REVIEW

**Comment by YangJiao0817** [comment]
@DandyDeveloper Please execute `make swagger_client` in the harbor/ directory, this can solve your problem.

**Comment by DandyDeveloper** [comment]
@YangJiao0817 @AllForNothing @wy65701436 This has been skipped for several releases now. 

Can I please get this included in a release?

**Comment by AllForNothing** [comment]
@DandyDeveloper This is already included in the upcoming 2.5

**Comment by DandyDeveloper** [comment]
@AllForNothing Oh, sorry I don't see a tag anywhere so I assume it wasn't. Thank you.

**Pull request merged**
