### PR TITLE
Fix: fix function name in comments

### PR DESCRIPTION
**Pull request by cuishuang**

### CODE REVIEW

**Review by zyyw — APPROVED** [review]

**Review by chlins — APPROVED** [review]
lgtm

**Comment by chlins** [comment]
@cuishuang Hi, please rebase your branch with main.

**Comment by cuishuang** [comment]
> @cuishuang Hi, please rebase your branch with main.

Completed. Also do I need to squash multiple commits into one？

**Comment by MinerYang** [comment]
> 
Yes,  please squash commit into one. Appreciate!
And we are wondering is there any specific linter you are using to test this?

**Comment by cuishuang** [comment]
> > 
> 
> Yes, please squash commit into one. Appreciate! And we are wondering is there any specific linter you are using to test this?

Completed. I am very interested in static analysis, and I tried to write some analyzers for go vet, but the proposal was not approved. 

Specifically, I did some analysis with the abstract syntax tree, but it is difficult to use it as a tool, because the first word in front of a large number of func is not necessarily the method name, so a lot of manual screening is required Work

**Comment by cuishuang** [comment]
> Hi @cuishuang please rebase your branch with main.

Done. Thanks

**Comment by OrlinVasilev** [comment]
@cuishuang congrats on merging your first PR here :)) Welcome to the club!

**Pull request merged**
