### PR TITLE
Add comment format check to makefile and travis

### PR DESCRIPTION
**Pull request by cd1989**
Signed-off-by: 陈德 <chende@caicloud.io>

Related to: https://github.com/goharbor/harbor/pull/5827

Add comment format check to makefile and travis CI

### CODE REVIEW

**Comment by reasonerjt** [comment]
@cd1989  thanks for the PR but is there a strong reason we need this check?  Why is it required since it's not part of `golint`?

**Comment by cd1989** [comment]
@reasonerjt It should be a good practice to follow consistent comment spec, and `// Comment` is commonly accepted one rule, so I make a pr to correct this previously. @steven-zou thinks we'd better integrate one check into travis CI to ensure incoming PRs also follow this. I totally agree this, so I make this check.

**Comment by wy65701436** [comment]
@cd1989 is there a way to fix it if my commit fails at check comments phase? Like gofmt error could be fixed by "-w".

**Comment by cd1989** [comment]
@wy65701436 You can use following command to fix it.

```
find src -name "*.go" | grep -v vendor | xargs sed -i -r 's/(^|\s)\/\/(\S)/\1\/\/ \2/g'
```

**Comment by wy65701436** [comment]
@cd1989 the regular expression fails to check the string like "// here is my comments //something bala bala"

**Comment by cd1989** [comment]
@wy65701436 

```
$ echo "// here is my comments //something bala bala" | egrep '(^|\s)\/\/(\S)'
// here is my comments //something bala bala
```
It matches.

As for cases with more than one spaces, I ignore it since it's not easy to deal with cases like:

image

**Pull request merged**
