### PR TITLE
Update Clair to v2.1.3

### PR DESCRIPTION
**Pull request by leolb-aphp**
This release adds ubuntu support for newer releases and fixes an issue where RHEL updaters bailed to quickly.

https://github.com/quay/clair/releases/tag/v2.1.3

### CODE REVIEW

**Comment by leolb-aphp** [comment]
Chicken and egg for availability of URL: https://storage.googleapis.com/harbor-builds/bin/clair/release2.0-v2.1.3/clair

**Comment by burdzwastaken** [comment]
It would be great if this could make it into `v1.10.3` as it is blocking our organization migrating to focal.

**Comment by leolb-aphp** [comment]
@burdzwastaken Yep..

**Comment by reasonerjt** [comment]
@wy65701436 @bitsf could you update the binary accordingly?  I think we can make it to 1.10.3 if we have this merged in this week.

**Comment by reasonerjt** [comment]
@wy65701436 please also make sure this is cherry-picked to 1.10.3

**Pull request merged**
