### PR TITLE
Add support for OIDC based SSO

### PR DESCRIPTION
**Pull request by ktbartholomew**
This addresses #6616.

* Adds configuration fields for OIDC provider URL, client ID, and client secret
* Adds core API endpoints to facilitate an access token OAuth flow with an OIDC-compliant provider (like Dex, see #5358)
* Creates user (in database) from OIDC claims if not present, or authenticates as that user if present.

Feedback welcome, as I'm sure there will be lots of opinions from more experienced contributors about things that I haven't done correctly 😄

### CODE REVIEW

**Comment by steven-zou** [comment]
@ktbartholomew 

Thanks a lot for submitting PR to cover the fantastic OIDC supporting which the whole community is looking forward to. However, based on the Harbor [governance model](https://github.com/goharbor/community/blob/master/GOVERNANCE.md), the changes should be summarized as a proposal and submitted to the community for a widely discussed. Only the proposal is accepted after review and voting by maintainers, the related code changes (PRs) can be accepted.

Is it ok to draft a [proposal](https://github.com/goharbor/community/blob/master/proposals/TEMPLATE.md)to describe your main ideas and let the community have a review? @ktbartholomew 

Moreover, a suggestion, many other community users have interested in this feature, maybe you can have a try to contact them to set up an `OIDC` workgroup to discuss and deliver the feature together? @ktbartholomew

**Comment by reasonerjt** [comment]
@ktbartholomew 
Thanks for the valuable work!
Actually we do plan to provide oidc support in 1.8.0 timeframe (Before end of April).
The proposal was delayed and planned to be submitted by the end of Feb, if you are interested we can work together to define the scenarios in the proposal and implement the feature.

**Comment by ktbartholomew** [comment]
@steven-zou It looks like a proposal had been made, but a revised draft is being worked on privately (see https://github.com/goharbor/community/pull/17#issuecomment-464275884). I'm happy to review and contribute to the proposal, but want to make sure I'm helping in the right place.

**Comment by reasonerjt** [comment]
@ktbartholomew 
Do you have a preferred way to more interactive communication in addition to this PR?  Email?  Slack(cloud-native.slack.com)?

**Comment by ktbartholomew** [comment]
> @ktbartholomew
> Do you have a preferred way to more interactive communication in addition to this PR? Email? Slack(cloud-native.slack.com)?

Slack is good, didn't know you had a workspace. Joining now!

**Pull request closed without merging**
