### PR TITLE
20548 MISSING CONDITION FOR RETURNING LOG DATA

### LINKED ISSUE #20548: Jobservice: GC logs blank page when using DB logging
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

Go to 'Clean up', you will see a table of GC runs (or if not you can run one manually)
When the GC task has completed, click on 'show logs' in the table.
What I would expect to see is a page showing the steps of the GC task - as you get if you set to FILE
What I actually see is a blank page

**Steps to reproduce the problem:**
Set logging on jobservice config to log to DB and set the max_retrieve_size_mb to 10MB
As above, select the GC logs from the 'clean up' page

**Versions:**
Please specify the versions of following systems.

- harbor version:  2.8.0 onwards
- docker engine version: 26.1.3
- docker-compose version: 1.29.2

**Additional context:**

- **Harbor config files:** 
jobservice.yml config
```
#Protocol used to serve
protocol: "http"

#Server listening port
port: 8080

#Worker pool
worker_pool:
  #Worker concurrency
  workers: 10
  backend: "redis"
  #Additional config if use 'redis' backend
  redis_pool:
    #redis://[arbitrary_username:password@]ipaddress:port/database_index
    redis_url: redis://redis:6379/2?idle_timeout_seconds=30
    namespace: "harbor_job_service_namespace"
    idle_timeout_second: 3600
#Loggers for the running job
job_loggers:
  # The jobLoggers backend name, only support "STD_OUTPUT", "FILE" and/or "DB"
  - name: "STD_OUTPUT"
    level: "INFO" # INFO/DEBUG/WARNING/ERROR/FATAL
  - name: "DB"
    level: "INFO"
    sweeper:
      duration: 1 #days

#Loggers for the job service
loggers:
  - name: "STD_OUTPUT" # Same with above
    level: "INFO"


reaper:
  # the max time to wait for a task to finish, if unfinished after max_update_hours, the task will be mark as error, but the task will continue to run, default value is 24,
  max_update_hours: 24
  # the max time for execution in running state without new task created
  max_dangling_hours: 168

# the max size of job log returned by API, default is 10M
max_retrieve_size_mb: 10
```

### PR DESCRIPTION
**Pull request by nickhyoti**
As per bug #20548, if DB logging is enabled for jobservice and the parameter is also set for maximum log size the log data is not being returned and 'Clean Up->Show GC Logs' shows a blank page

Thank you for contributing to Harbor!

# Comprehensive Summary of your change

# Issue being fixed
Fixes #20548

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Comment by nickhyoti** [comment]
I'm getting emails about this not being labeled but theres no ability to label

**Review by Vad1mo — APPROVED** [review]

**Review by zyyw — APPROVED** [review]

**Comment by zyyw** [comment]
@nickhyoti could you please help to resolve this `DCO` issue? Thanks

**Review by zyyw — CHANGES_REQUESTED** [review]
Thank you for contributing to goharbor/harbor. Could you please help to add unit test?

**Comment by shishir-11** [comment]
I'm a bit new and confused on some of the things , what are we supposed to add unit tests on? that it now produces the logs properly ?

**Comment by zyyw** [comment]
> I'm a bit new and confused on some of the things , what are we supposed to add unit tests on? that it now produces the logs properly ?

Thanks for the contribution. We do reproduce the issue mentioned here https://github.com/goharbor/harbor/issues/20548.

Maybe update the `TestDBGetter` of this [file](https://github.com/goharbor/harbor/blob/main/src/jobservice/logger/getter/db_getter_test.go#L38-L58), to something like below:
```
// TestDBGetter
func TestDBGetter(t *testing.T) {
	uuid := "uuid_for_unit_test_getter"
	l, err := backend.NewDBLogger(uuid, "DEBUG", 4)
	require.Nil(t, err)

	l.Debug("JobLog Debug: TestDBLoggerGetter")
	err = l.Close()
	require.NoError(t, err)

	_ = config.DefaultConfig.Load("../../config_test.yml", true)  <====== add this line
	dbGetter := NewDBGetter()
	ll, err := dbGetter.Retrieve(uuid)
	require.Nil(t, err)
	require.NotEqual(t, 0, len(ll))  <====== add this line
	log.Infof("get logger %s", ll)

	err = sweeper.PrepareDBSweep()
	require.NoError(t, err)
	dbSweeper := sweeper.NewDBSweeper(-1)
	count, err := dbSweeper.Sweep()
	require.Nil(t, err)
	require.Equal(t, 1, count)
}
```

@nickhyoti @shishir-11 could you please help to resolve the `DCO` issue displayed in the CI as well? Thanks! 

cc: @wy65701436

**Comment by shishir-11** [comment]
Hey, how do you guys check out how the changes you make in the code reflect in the working except the tests , do I need to rebuild the harbor project everytime I want to see a change ?

**Comment by zyyw** [comment]
> Hey, how do you guys check out how the changes you make in the code reflect in the working except the tests , do I need to rebuild the harbor project everytime I want to see a change ? I'm also having some trouble building the project as i keep getting
> 
> ```
> Error happened in config validation...
> ERROR:root:Please specify hostname
> make: *** [Makefile:372: prepare] Error 255
> ```
> 
> this error even though the harbor.yml file has reg.mydomain.com as hostname

maybe you wanna try the following command to build an offline-installer against your source code:
```
Harbor_Build_Base_Tag=dev
Harbor_Assets_Version=dev
Harbor_Package_Version=dev-build.2024050702
build_base_params=" BUILD_BASE=true"
sudo make package_offline GOBUILDTAGS="include_oss include_gcs" BASEIMAGETAG=${Harbor_Build_Base_Tag} VERSIONTAG=${Harbor_Assets_Version} PKGVERSIONTAG=${Harbor_Package_Version} TRIVYFLAG=true HTTPPROXY= ${build_base_params}
```
If everything goes well, it will generate an offline-installer of the source codebase. Then you can install it in a docker-compose way.

**Comment by mohamedawnallah** [comment]
Hey @zyyw,

I've just submitted a PR for this issue, including the test and `DCO` (saving credits to @nickhyoti for the main fix). I was able to test the fix before and after, as you can see in the attached images:

**Before (Blank Page)**  
Screenshot 2024-07-02 at 5 57 34 AM

**After (Logs appear)**  
Screenshot 2024-07-02 at 5 57 07 AM

I would love to receive any feedback, Thanks! 🙏

#20684

**Comment by chlins** [comment]
Closed as merged in https://github.com/goharbor/harbor/pull/20684

**Pull request closed without merging**
