### PR TITLE
Add support for TLSv1.3 in nginx configurations

### LINKED ISSUE #18358: Add support for TLSv1.3 in nginx proxy
**Is your feature request related to a problem? Please describe.**
We want to use TLSv1.3 for all our applications, but at the moment Harbor only supports TLSv1.2.

**Describe the solution you'd like**
The Harbor nginx proxy configuration should be extended to include `TLSv1.3`.

**Describe the development plan you've considered**
The only change required should be to change [this line](https://github.com/goharbor/harbor/blob/v2.7.1/make/photon/prepare/templates/portal/nginx.conf.jinja#L25) in the nginx.conf to include TLSv1.3:
```
ssl_protocols TLSv1.2 TLSv1.3;
```

**Additional context**
https://github.com/goharbor/harbor/issues/11119 was created three years ago to solve this problem - but went stale.

I can submit an PR with the required change if this feature is welcome.

### PR DESCRIPTION
**Pull request by malmor**
Thank you for contributing to Harbor!

# Comprehensive Summary of your change
This PR enables `TLSv1.3` by default in the nginx configuration. This way the configuration follows the [linked recommendations](https://raymii.org/s/tutorials/Strong_SSL_Security_On_nginx.html#toc_0) and the [nginx default configuration](https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_protocols).

# Issue being fixed
Fixes #18358

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [ ] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [ ] Made sure tests are passing and test coverage is added if needed.
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Comment by MinerYang** [comment]
Hi @malmor ,
Could you please help to rebase and resolve the conflict since the notary has been removed from main
Thanks!

**Comment by malmor** [comment]
Hey @MinerYang,
sure - I just rebased my branch and resolved the conflicts in the notary files.

**Review by MinerYang — APPROVED** [review]
lgtm

**Review by wy65701436 — APPROVED** [review]
LGTM

**Comment by OrlinVasilev** [comment]
@malmor thank you for contributing :) congrats on your first PR here :)

**Comment by niko-la-petrovic** [comment]
For those who are looking to get TLSv1.3 before the release 2.9.0 comes out, you can add to line `61` of the  `prepare` script
```bash
echo "Adding support for TLSv1.3"
sed -i $config_dir/nginx/nginx.conf -e 's/ssl_protocols TLSv1.2/ssl_protocols TLSv1.2 TLSv1.3/g'
```

Because the `prepare` script regenerates the `nginx.conf`, I think this is a sensible way to adjust the `nginx.conf` file in a reproducible way.

**Pull request merged**
