### PR TITLE
fix: import optimization

### PR DESCRIPTION
**Pull request by testwill**

### CODE REVIEW

**Review by wy65701436 — APPROVED** [review]
lgtm

**Comment by wy65701436** [comment]
hi @testwill thank you for your contribution! Could you please let me know if the findings were caught by any specific tools or lint rules? This will help us enable them in our CI process.

**Comment by testwill** [comment]
staticcheck

**Comment by MinerYang** [comment]
Hi @testwill ,
Interesting, actually we enable static check in our ci lint.
 https://github.com/goharbor/harbor/blob/4f3393e615c44cb64336c94963897a78b3080a3d/src/.golangci.yaml#L46 
Could you please share your golangci-lint version that is used?

**Comment by testwill** [comment]
staticcheck 2023.1.3 (v0.4.3)

**Review by zyyw — APPROVED** [review]

**Comment by MinerYang** [comment]
We may use different staticcheck binary per to this doc, thus make the difference
https://golangci-lint.run/usage/linters/#enabled-by-default

**Comment by OrlinVasilev** [comment]
@testwill congrats on your first PR here :)

**Comment by OrlinVasilev** [comment]
@wy65701436 @zyyw - we should not approve PRs without description or link to existing issue. As PR will appear into the release notes we need some more explanation in the description part thank you!
@testwill can you description , thank you so much!

**Pull request merged**
