### PR TITLE
Update RELEASE and CONTRIBUTING with main instead of master

### PR DESCRIPTION
**Pull request by OrlinVasilev**
Signed-off-by: OrlinVasilev <ovasilev@vmware.com>

Please indicate you've done the following:
- [X] Well Written Title and Summary of the PR
- [X] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [X] Accepted the DCO. Commits without the DCO will delay acceptance.
- [X] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Review by wy65701436 — APPROVED** [review]
lgtm

**Comment by AllForNothing** [comment]
@OrlinVasilev You need to rebase your code to pass  the `CI / UTTEST` check

**Comment by AllForNothing** [comment]
@OrlinVasilev Seems that something is wrong with your rebase action,  it shows some  merged commits in your PR now:
image

**Comment by OrlinVasilev** [comment]
> 

yeah that's strange will close and PR again :)

**Pull request closed without merging**
