### PR TITLE
Registryctl auth unit tests

### PR DESCRIPTION
**Pull request by SDBrett**
Added tests for registryctl authentication to improve coverage levels.

### CODE REVIEW

**Comment by wy65701436** [comment]
Thanks, please fix the golint failure.

**Comment by SDBrett** [comment]
Corrected linting.

**Comment by clouderati** [comment]
Just wanted to chime in real quick and thank you for the contribution. :smile:

**Comment by SDBrett** [comment]
Detail added to commit message.

**Pull request merged**
