### PR TITLE
Support vpc and internal network (goharbor#17488)

### LINKED ISSUE #17488: reg/adapter/aliacr: support endpoint of aliacr for vpc and internal network.
Support registry of aliacr for vpc network and internal network.

Endpoints like: 

+ `https://registry-vpc.%s.aliyuncs.com`
+ `https://registry-internal.%s.aliyuncs.com`

The vpc endpoint is  for vpc network node in ali cloud.

The internal endpoint is for classtic network node in ali cloud.

### PR DESCRIPTION
**Pull request by szyhf**
Signed-off-by: Back Yu <yhfszb@gmail.com>

Thank you for contributing to Harbor!

# Comprehensive Summary of your change

# Issue being fixed
Fixes #17488 

Add support for vpc and internal endpoint for aliacr.

Please indicate you've done the following:
- [X] Well Written Title and Summary of the PR
- [ ] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [X] Accepted the DCO. Commits without the DCO will delay acceptance.
- [X] Made sure tests are passing and test coverage is added if needed.
- [X] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Comment by chlins** [comment]
@kofj Please take a look at this pr, thanks!

**Comment by AllForNothing** [comment]
@szyhf Please run `cd src/portal; npm run lint_fix` to fix the lint failure

**Comment by szyhf** [comment]
Hi, what can I do for the release-note label check ?

And I'm not sure what's worng with the `codecov/project ` error 😅

**Review by AllForNothing — APPROVED** [review]
UI part LGTM

**Comment by kofj** [comment]
backend part reviewing.

**Comment by kofj** [comment]
@szyhf  Well done, please add some tests to override the `withc true` branches, the codecov has tips this.

**Comment by szyhf** [comment]
@kofj hi, new commit is pushed, but the robot seems suspend (or passed?)

**Review by kofj — APPROVED** [review]

**Pull request merged**
