### PR TITLE
Fix OIDC connect button string - [French]

### PR DESCRIPTION
**Pull request by malacoss**

### CODE REVIEW

**Review by ninjadq — APPROVED** [review]
lgtm

**Review by reasonerjt — APPROVED** [review]

**Comment by reasonerjt** [comment]
Please sign the DCO
merci

**Review by reasonerjt — CHANGES_REQUESTED** [review]
block the PR until DCO is signed.

**Comment by malacoss** [comment]
@reasonerjt DCO signed.

**Review by reasonerjt — APPROVED** [review]

**Pull request merged**
