### PR TITLE
feat: Disable CSRF check for "/c/oidc/onboard" API for authenticating and Onboarding a User via API from Custom CLI

### LINKED ISSUE #16966: Disable CSRF check for "/c/oidc/onboard" API for authenticating and Onboarding a User via API from Custom CLI
We are facing an issue when we are trying to onboard the OIDC user in the harbor via API.

https://goharbor.io/docs/edge/administration/configure-authentication/oidc-auth/

Via UI it works perfectly fine. 

The same functionality is not working via the API. Getting CSRF error. 

As per online research CSRF is only checked when you do activity via browser i.e. where there is some sessions.

Issue is only with this particular API. Other APIs are working fine.

Without onboarding an OIDC user we won’t be able to set secret and therefore docker login will not work.

 
`curl -X 'POST' 'https://xxxx-registry-xxxx-xxx.xxxxxx.com/c/oidc/onboard' \
-H 'Content-Type: application/json' \
-H 'Authorization: Basic YWRtaW46cXNlYSvhcnRpZmFjdG9yeS1hZG1pbg==' \
-d '{"username": gbell@xxxx.com }'
`

`{"errors":[{"code":"FORBIDDEN","message":"CSRF token invalid"}]}`

### PR DESCRIPTION
**Pull request by Rajpratik71**
# Issue being fixed

Fixes #16966 

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Review by Vad1mo — APPROVED** [review]

**Comment by Rajpratik71** [comment]
@reasonerjt  requesting review

**Comment by Rajpratik71** [comment]
@zyyw  @reasonerjt  requesting review

**Review by reasonerjt — APPROVED** [review]

**Review by reasonerjt — CHANGES_REQUESTED** [review]
Sorry for the late response but I don't understand why this is needed to onboard a user you need to follow the SSO flow to authenticate via the OIDC provider and do token exchange.  After that you will be redirected to onboard endpoint.

Therefore this is DESIGNED for browser, but in the issue you mentioned you wanna call this via curl which is not supposed to work.

**Comment by Vad1mo** [comment]
Maybe I am wrong but, as I understand it from @Rajpratik71 and other similar issues, is that they want to manage the user before he actually logs in to Harbor the first time. Examples are add the user to the different projects and grant them the right permissions. 

Am I right @Rajpratik71 ?

**Comment by Rajpratik71** [comment]
Hi @reasonerjt  @Vad1mo 

This is required to do:

1. authentication with OIDC provider and 
2. user onboarding 

via custom-made cli or curl request using API.

As mentioned in issue, In browser flow CSRF token got added in request, i.e. why it is happening fine but when calling direct API , csrf check is blocking.

i.e. exception was added in "csrfSkipper" function to skip csrf check for "/c/oidc/onboard" API.

**Comment by Rajpratik71** [comment]
@ywk253100  @wy65701436  @stonezdj  @zyyw  @daixiang0 @heww requesting review

**Comment by ashishkumar-07** [comment]
I also need the same behavior. For my use case @Vad1mo is correct. If not this then a similar API should exist for backend flow

**Comment by fredchen-bj** [comment]
why blocked? we need this pr.

**Comment by reasonerjt** [comment]
> Maybe I am wrong but, as I understand it from @Rajpratik71 and other similar issues, is that they want to manage the user before he actually logs in to Harbor the first time. Examples are add the user to the different projects and grant them the right permissions.

I think this may be a valid requirement but I'm not convinced this PR is the right way to solve the problem.  To use this endpoint you need the ID token of a specific user, but admin can't do that b/c he doesn't know the credentials of this user.
We need to find a way to allow admin to onboard user without ID token, and for that purpose I don't think we should use the current `/c/onboard` endpoint.

**Comment by Rajpratik71** [comment]
> 

@reasonerjt  I think there is some confusion in understanding the scenario.

Here, we don't want this for admin user and don't needs to be done by admin user.

This step is required for self-service i.e signup to harbor using configured Oauth.

This is required for first time signing in of a User in Harbor with configured Oauth.

While from UI, First time signing in of a User in Harbor with configured Oauth got success because in request UI passes the CSRF Token after getting the token from configured Auth/Oauth server then using the token fires the "/c/oidc/onboard" API to get it onboarded in Harbor as a User.

From next time it is not required as user is already there in Harbor.

On the other hand
 
While from CLI/API , First time signing in of a User in Harbor with configured Oauth got failed because of missing CSRF Token after getting the token from configured Auth/Oauth server then using the token fires the "/c/oidc/onboard" API to get it onboarded in Harbor as a User.

But as CLI/API request doesn't add CSRF Header in requests i.e. the check is failing

**Comment by Rajpratik71** [comment]
Further , missed the today community meeting due to time zone confusion, was thinking to discuss this.

@reasonerjt  and Harbor Team can we schedule a meeting to discuss this over call ?

**Comment by reasonerjt** [comment]
@Rajpratik71 
I would love to, I'll reach out to you on slack.

**Comment by WeiXie96** [comment]
Any updates? We also need this pr.

**Comment by WeiXie96** [comment]
Is it still possible that it can be merged sooner or later? We want to onboard OIDC users through CLI but not GUI, and this fix can solve our problem.

**Review by Vad1mo — APPROVED** [review]

**Comment by WeiXie96** [comment]
Sorry for asking: can it still be merged into harbor's main branch? And will there be a release that includes this change then? Otherwise we need to build harbor again from the source code.

**Comment by Vovanys** [comment]
I build images from this commit with CSRF disabled
I try to create a user and get an error

`curl -X 'POST' 'https://harbor-registry.xxxx/c/oidc/onboard'  -H 'Content-Type: application/json' -H 'Authorization: Basic YWRtaW46SGFyYm9yMTIzU='  -d '{"username": "testuser" }' `

{"errors":[{"code":"BAD_REQUEST","message":"Failed to get OIDC user info from session"}]}

At the same time, everything onboard works through the GUI.
I use keycloack

what else is needed?

in harbor logs

[DEBUG] [/server/middleware/security/basic_auth.go:79][requestID="266741f532898a29f1e2ecf1083a980f"]: a basic auth security context generated for request POST /c/oidc/onboard
[DEBUG] [/lib/http/error.go:61]: {"errors":[{"code":"BAD_REQUEST","message":"Failed to get OIDC user info from session"}]}

**Comment by OrlinVasilev** [comment]
@goharbor/all-maintainers can you check please

**Comment by WeiXie96** [comment]
My error message is still `{"errors":[{"code":"FORBIDDEN","message":"CSRF token invalid"}]}`, any updates on this issue??

**Pull request closed without merging**
