### PR TITLE
Added group_type information for type 3 OIDC group

### PR DESCRIPTION
**Pull request by Dannyx323**
Thank you for contributing to Harbor!

# Comprehensive Summary of your change
Added group_type information for type 3 OIDC group to the API description

# Issue being fixed
Fixes #()

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Comment by wy65701436** [comment]
@Dannyx323 can you help to squash the commits?

**Review by wy65701436 — APPROVED** [review]
lgtm

**Comment by Dannyx323** [comment]
> @Dannyx323 can you help to squash the commits?

squashed the two commits

**Review by stonezdj — APPROVED** [review]
LGTM

**Pull request merged**
