### PR TITLE
Changed logic search projects in gitlab adapter

### LINKED ISSUE #18284: Replication Issue with GitLab
**Expected behavior and actual behavior:**
When I try to replicate projects from one of my gitlab instance some replication works as expected but others fail doing nothing (no task is created, nothing in logs)

**Steps to reproduce the problem:**
Create two replication rules for different gitlab project hosted in same gitlab instance (same group path, same credentials, gitlab user have same permissions on the two projects)
First one replicate as expected (Execution and Task)
Second one do nothing (Execution is created but no Task)

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.7.1]
- docker engine version: [23.0.1]
- docker-compose version: [1.26.0]

**Additional context:**
We tried upgrading from 2.5.3 to 2.7.1 but problem still exist.
We tried to remove project, replication rule and re-create them without any change.

There is nothing in the logs regarding the replications.

### PR DESCRIPTION
**Pull request by lxShaDoWxl**
# Comprehensive Summary of your change
Changed logic search projects in gitlab adapter for correction search projects
# Issue being fixed
Fixes #18284

### CODE REVIEW

**Comment by chlins** [comment]
@lxShaDoWxl Thanks for your help, the changes look good to me, but let's hold for the verification from user.

**Comment by chlins** [comment]
@lxShaDoWxl The CI UTTEST failed, please fix it.

**Review by chlins — APPROVED** [review]
lgtm

**Review by wy65701436 — APPROVED** [review]
lgtm

**Pull request merged**
