### PR TITLE
Added Tag Retention Permission to Developer 

### PR DESCRIPTION
**Pull request by DarthBlair**
**Observed Bug:**
According to according to the ["User Pemission by Role" Table](https://goharbor.io/docs/2.4.0/administration/managing-users/user-permissions-by-role/) the Developer should have the right to "Create/delete tag retention rules" and "Enable/disable tag retention rules". Nevertheless the Developer cannot see the Policy tab in the Harbor Portal, so he cannot work with retention rules.

**Troubleshooting:**
While looking for the source of this difference we found that the Policy tab is shown if the [user has TagRetentionPermission](https://github.com/goharbor/harbor/blob/44f477e965e57ba619d494a7122c69a636906666/src/portal/src/app/base/project/project-detail/project-detail.component.ts#L104). This Information is provided by the backend under "GET api/v2.0/users/current/permissions?scope=/project/2&relative=true"

**Output for Developer:**
```json
[{"action":"read","resource":"."},{"action":"read","resource":"quota"},{"action":"list","resource":"repository"},{"action":"pull","resource":"repository"},{"action":"read","resource":"helm-chart"},{"action":"list","resource":"helm-chart"},{"action":"read","resource":"helm-chart-version"},{"action":"list","resource":"helm-chart-version"},{"action":"read","resource":"configuration"},{"action":"read","resource":"scan"},{"action":"read","resource":"scanner"},{"action":"list","resource":"tag"},{"action":"read","resource":"artifact"},{"action":"list","resource":"artifact"},{"action":"read","resource":"artifact-addition"},{"action":"read","resource":"member"},{"action":"list","resource":"member"},{"action":"list","resource":"log"},{"action":"read","resource":"label"},{"action":"list","resource":"label"},{"action":"create","resource":"repository"},{"action":"read","resource":"repository"},{"action":"update","resource":"repository"},{"action":"push","resource":"repository"},{"action":"create","resource":"helm-chart"},{"action":"create","resource":"helm-chart-version"},{"action":"create","resource":"helm-chart-version-label"},{"action":"delete","resource":"helm-chart-version-label"},{"action":"read","resource":"robot"},{"action":"list","resource":"robot"},{"action":"create","resource":"artifact"},{"action":"create","resource":"tag"},{"action":"create","resource":"artifact-label"},{"action":"delete","resource":"artifact-label"}]
```
**Output for Project Admin**
```json
[{"action":"read","resource":"."},{"action":"update","resource":"."},{"action":"delete","resource":"."},{"action":"create","resource":"member"},{"action":"read","resource":"member"},{"action":"update","resource":"member"},{"action":"delete","resource":"member"},{"action":"list","resource":"member"},{"action":"create","resource":"metadata"},{"action":"read","resource":"metadata"},{"action":"update","resource":"metadata"},{"action":"delete","resource":"metadata"},{"action":"list","resource":"log"},{"action":"create","resource":"label"},{"action":"read","resource":"label"},{"action":"update","resource":"label"},{"action":"delete","resource":"label"},{"action":"list","resource":"label"},{"action":"read","resource":"quota"},{"action":"create","resource":"repository"},{"action":"read","resource":"repository"},{"action":"update","resource":"repository"},{"action":"delete","resource":"repository"},{"action":"list","resource":"repository"},{"action":"pull","resource":"repository"},{"action":"push","resource":"repository"},{"action":"create","resource":"tag-retention"},{"action":"read","resource":"tag-retention"},{"action":"update","resource":"tag-retention"},{"action":"delete","resource":"tag-retention"},{"action":"list","resource":"tag-retention"},{"action":"operate","resource":"tag-retention"},{"action":"create","resource":"immutable-tag"},{"action":"update","resource":"immutable-tag"},{"action":"delete","resource":"immutable-tag"},{"action":"list","resource":"immutable-tag"},{"action":"create","resource":"helm-chart"},{"action":"read","resource":"helm-chart"},{"action":"delete","resource":"helm-chart"},{"action":"list","resource":"helm-chart"},{"action":"create","resource":"helm-chart-version"},{"action":"read","resource":"helm-chart-version"},{"action":"delete","resource":"helm-chart-version"},{"action":"list","resource":"helm-chart-version"},{"action":"create","resource":"helm-chart-version-label"},{"action":"delete","resource":"helm-chart-version-label"},{"action":"read","resource":"configuration"},{"action":"update","resource":"configuration"},{"action":"create","resource":"robot"},{"action":"read","resource":"robot"},{"action":"update","resource":"robot"},{"action":"delete","resource":"robot"},{"action":"list","resource":"robot"},{"action":"create","resource":"notification-policy"},{"action":"update","resource":"notification-policy"},{"action":"delete","resource":"notification-policy"},{"action":"list","resource":"notification-policy"},{"action":"read","resource":"notification-policy"},{"action":"create","resource":"scan"},{"action":"read","resource":"scan"},{"action":"stop","resource":"scan"},{"action":"read","resource":"scanner"},{"action":"create","resource":"scanner"},{"action":"create","resource":"artifact"},{"action":"read","resource":"artifact"},{"action":"delete","resource":"artifact"},{"action":"list","resource":"artifact"},{"action":"read","resource":"artifact-addition"},{"action":"list","resource":"tag"},{"action":"create","resource":"tag"},{"action":"delete","resource":"tag"},{"action":"create","resource":"artifact-label"},{"action":"delete","resource":"artifact-label"},{"action":"create","resource":"preheat-policy"},{"action":"read","resource":"preheat-policy"},{"action":"update","resource":"preheat-policy"},{"action":"delete","resource":"preheat-policy"},{"action":"list","resource":"preheat-policy"}]
```
In Answer for the developer ist tag-retention missing. Therefore we found out that the assignment ist missing in the rbac_role itself.

Added Permissions to Developer to according to the ["User Pemission by Role" Table](https://goharbor.io/docs/2.4.0/administration/managing-users/user-permissions-by-role/)

### CODE REVIEW

**Comment by kpeteln** [comment]
The fix looks correct. It would be really good to get this merged - could you add the required sign off?

**Review by kpeteln — APPROVED** [review]

**Comment by Vad1mo** [comment]
@DarthBlair is the PR still relevant?
Can we get some pair of eyes on that again @goharbor/maintainers.

**Comment by DarthBlair** [comment]
Yes it is. It is a wrong implementation of the documented role permission and should be a quick fix. Would be nice if someone might look at it again. 
Thx

**Comment by zyyw** [comment]
Hi @DarthBlair , the CI failed due to the following reason:
```
04:04:39 common/rbac/project/rbac_role.go:232: File is not `gofmt`-ed (gofmt)
```
Could you please remove the extra whitespace of common/rbac/project/rbac_role.go:230 (not 232)? Note: we only need to remove extra/leading whitespace of `rbac_role.go:230` and keep the line 230 (don't remove the whole line).
Screen Shot 2022-07-06 at 12 32 41

Thanks for your contribution!

**Comment by zyyw** [comment]
BTW, could you please also rebase latest main into your branch?  Thanks

**Review by zyyw — APPROVED** [review]

**Pull request merged**
