### PR TITLE
Remove old and unused tags in repositories

### PR DESCRIPTION
**Pull request by s-mansouri**
related #6032 
Keep X number of tags and remove other by date created 
usage: 
`./cli.py --username admin --password mypass --registry_endpoint http://myregistryendpoint tag remove_list --number 2 `

options:
**--number**: number of tags wants to keep in each repository
**--dryrun**: run command without removing any tags

### CODE REVIEW

**Comment by clouderati** [comment]
@nlowe can you please comment on how this relates to your [tag retention proposal](https://github.com/goharbor/community/pull/4)?

**Comment by nlowe** [comment]
@s-mansouri Thanks for sending this, It's good to here that there are others interested in this feature!

This is effectively a different implementation of [HylandSoftware/Harbor.Tagd](https://github.com/hylandsoftware/Harbor.Tagd) which is what inspired me to write goharbor/community#4. This is covered under the proposal which should be merged soon unless any major issues are raised. I'm not sure on an implementation timeline, I'm planning on implementing it in my free time and devoting a small portion of my work week to it.

Since `tagd` is linked in the [Additional Tools](https://github.com/goharbor/harbor#additional-tools) section of the README already and a proposal is in the works for built-in support for this, I don't know that we need to change the python CLI, especially since it was last touched 2 Years ago. Is your environment more suited to running python scripts instead of a docker container for this task?

**Comment by s-mansouri** [comment]
@steven-zou @nlowe Thanks for your feedback 

I found out that python CLI is more secure and fastest way for cleaning tags, there is no need to install or clone other unknown repositories as I have sensitive data on my registry. 

But you said this CLI is deprecated, so I'm glad to help @nlowe to complete that work.

**Comment by clouderati** [comment]
Thanks @s-mansouri and @nlowe; please keep us updated on how things progress.

Let's keep this open in the meantime.

**Comment by nlowe** [comment]
I'm going to close this as the tag retention policy proposal has been merged and work has started on it.

@s-mansouri feel free to watch goharbor/harbor#6654 and jump in on any of the sub-tasks. We'd gladly take any help we can get!

**Pull request closed without merging**
