### PR TITLE
Turn off server_tokens for nginx http->https redirect vhost

### PR DESCRIPTION
**Pull request by sizowie**
This change turns off server_tokens (NGINX version in the HTTP response header) for the http->https redirect vhost in the NGINX configuration template.

### Why?
NGINX "security" options like server_tokens should be the same in the http redirect vhost as for the https vhost, otherwise hiding the NGINX release in https vhost wouldn't make sense.

**http**
```
# curl -v http://localhost        
....     
< Server: nginx/1.22.0      
```                           

**https**
```
# curl -v https://localhost
...      
< Server: nginx          
```  

Please indicate you've done the following:
- [X] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [X] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

### CODE REVIEW

**Comment by Vad1mo** [comment]
@sizowie can you indicate, in your PR the benefits for Harbor and their users?

**Comment by sizowie** [comment]
> @sizowie can you indicate, in your PR the benefits for Harbor and their users?

sure, description updated.

**Review by Vad1mo — APPROVED** [review]

**Comment by Vad1mo** [comment]
Makes sense, it is common practice and security advice to not print tokens

**Comment by wy65701436** [comment]
hi @sizowie would you mind to provide some references for this change? 

And the similar comments with this [change](https://github.com/goharbor/harbor/pull/18269), 

`Harbor provides a default configuration for Nginx, but users can enable or disable any configurations based on their specific requirements. However, this default configuration is only applicable for online/offline installations. What if a user installs Harbor on Kubernetes and prefers to use Contour as the proxy?`

**Comment by sizowie** [comment]
> hi @sizowie would you mind to provide some references for this change?
> 
> And the similar comments with this [change](https://github.com/goharbor/harbor/pull/18269),
> 
> `Harbor provides a default configuration for Nginx, but users can enable or disable any configurations based on their specific requirements. However, this default configuration is only applicable for online/offline installations. What if a user installs Harbor on Kubernetes and prefers to use Contour as the proxy?`

http://nginx.org/en/docs/http/ngx_http_core_module.html#server_tokens
Enables or disables emitting nginx version on error pages and in the “Server” response header field.

This change only applies to users that are using the nginx container from the harbor online/offline-installer to ensure a minimum default hardened reverse proxy.

**Comment by Vad1mo** [comment]
Hey @goharbor/maintainers  can we get this merged? this is a sensible basic configuration setting for Harbor.

**Pull request closed without merging**
