### PR TITLE
add parseCPUInfo for Loongarch in procfs

### PR DESCRIPTION
**Pull request by zhangwenlong8911**
Signed-off-by: zhangwenlong <zhangwenlong@loongson.cn>

### CODE REVIEW

**Comment by heww** [comment]
I don't think it's a good way to modify the source code in the vendor. Please open PR in the Prometheus project.

**Comment by zhangwenlong8911** [comment]
Ok, I will submit the code to the upstream first

**Comment by zhangwenlong8911** [comment]
Ok, I will submit the code to the upstream first

**Comment by reasonerjt** [comment]
Updating the vendor is highly unsustainable, I'm closing this PR.

**Pull request closed without merging**
